# -*- coding: utf-8 -*-
# Donnees partagees des 101 departements francais (metropole + 5 DOM).
# GENERE (geojson gregoiredavid + Wikidata P41/P94/P2586). Noms ASCII ; fichiers Commons decodes.
# DEPS=[(code,nom_ascii,region_ascii,tier 0/1)] ; tier 0=Facile 1=Moyen ; Difficile(2)=tous pixelise.
# DEPT_FLAG_FILE={code:'fichier Wikimedia'} (drapeau sinon blason).

DEPS = [
    ('01', 'Ain', 'Auvergne-Rhone-Alpes', 1),
    ('02', 'Aisne', 'Hauts-de-France', 1),
    ('03', 'Allier', 'Auvergne-Rhone-Alpes', 1),
    ('04', 'Alpes-de-Haute-Provence', "Provence-Alpes-Cote d'Azur", 1),
    ('05', 'Hautes-Alpes', "Provence-Alpes-Cote d'Azur", 1),
    ('06', 'Alpes-Maritimes', "Provence-Alpes-Cote d'Azur", 0),
    ('07', 'Ardeche', 'Auvergne-Rhone-Alpes', 1),
    ('08', 'Ardennes', 'Grand Est', 1),
    ('09', 'Ariege', 'Occitanie', 1),
    ('10', 'Aube', 'Grand Est', 1),
    ('11', 'Aude', 'Occitanie', 1),
    ('12', 'Aveyron', 'Occitanie', 1),
    ('13', 'Bouches-du-Rhone', "Provence-Alpes-Cote d'Azur", 0),
    ('14', 'Calvados', 'Normandie', 0),
    ('15', 'Cantal', 'Auvergne-Rhone-Alpes', 1),
    ('16', 'Charente', 'Nouvelle-Aquitaine', 1),
    ('17', 'Charente-Maritime', 'Nouvelle-Aquitaine', 0),
    ('18', 'Cher', 'Centre-Val de Loire', 1),
    ('19', 'Correze', 'Nouvelle-Aquitaine', 1),
    ('21', "Cote-d'Or", 'Bourgogne-Franche-Comte', 0),
    ('22', "Cotes-d'Armor", 'Bretagne', 1),
    ('23', 'Creuse', 'Nouvelle-Aquitaine', 1),
    ('24', 'Dordogne', 'Nouvelle-Aquitaine', 1),
    ('25', 'Doubs', 'Bourgogne-Franche-Comte', 0),
    ('26', 'Drome', 'Auvergne-Rhone-Alpes', 1),
    ('27', 'Eure', 'Normandie', 1),
    ('28', 'Eure-et-Loir', 'Centre-Val de Loire', 1),
    ('29', 'Finistere', 'Bretagne', 0),
    ('2A', 'Corse-du-Sud', 'Corse', 0),
    ('2B', 'Haute-Corse', 'Corse', 0),
    ('30', 'Gard', 'Occitanie', 0),
    ('31', 'Haute-Garonne', 'Occitanie', 0),
    ('32', 'Gers', 'Occitanie', 1),
    ('33', 'Gironde', 'Nouvelle-Aquitaine', 0),
    ('34', 'Herault', 'Occitanie', 0),
    ('35', 'Ille-et-Vilaine', 'Bretagne', 0),
    ('36', 'Indre', 'Centre-Val de Loire', 1),
    ('37', 'Indre-et-Loire', 'Centre-Val de Loire', 0),
    ('38', 'Isere', 'Auvergne-Rhone-Alpes', 0),
    ('39', 'Jura', 'Bourgogne-Franche-Comte', 1),
    ('40', 'Landes', 'Nouvelle-Aquitaine', 1),
    ('41', 'Loir-et-Cher', 'Centre-Val de Loire', 1),
    ('42', 'Loire', 'Auvergne-Rhone-Alpes', 1),
    ('43', 'Haute-Loire', 'Auvergne-Rhone-Alpes', 1),
    ('44', 'Loire-Atlantique', 'Pays de la Loire', 0),
    ('45', 'Loiret', 'Centre-Val de Loire', 1),
    ('46', 'Lot', 'Occitanie', 1),
    ('47', 'Lot-et-Garonne', 'Nouvelle-Aquitaine', 1),
    ('48', 'Lozere', 'Occitanie', 1),
    ('49', 'Maine-et-Loire', 'Pays de la Loire', 0),
    ('50', 'Manche', 'Normandie', 1),
    ('51', 'Marne', 'Grand Est', 0),
    ('52', 'Haute-Marne', 'Grand Est', 1),
    ('53', 'Mayenne', 'Pays de la Loire', 1),
    ('54', 'Meurthe-et-Moselle', 'Grand Est', 0),
    ('55', 'Meuse', 'Grand Est', 1),
    ('56', 'Morbihan', 'Bretagne', 0),
    ('57', 'Moselle', 'Grand Est', 0),
    ('58', 'Nievre', 'Bourgogne-Franche-Comte', 1),
    ('59', 'Nord', 'Hauts-de-France', 0),
    ('60', 'Oise', 'Hauts-de-France', 1),
    ('61', 'Orne', 'Normandie', 1),
    ('62', 'Pas-de-Calais', 'Hauts-de-France', 1),
    ('63', 'Puy-de-Dome', 'Auvergne-Rhone-Alpes', 0),
    ('64', 'Pyrenees-Atlantiques', 'Nouvelle-Aquitaine', 0),
    ('65', 'Hautes-Pyrenees', 'Occitanie', 1),
    ('66', 'Pyrenees-Orientales', 'Occitanie', 0),
    ('67', 'Bas-Rhin', 'Grand Est', 0),
    ('68', 'Haut-Rhin', 'Grand Est', 0),
    ('69', 'Rhone', 'Auvergne-Rhone-Alpes', 0),
    ('70', 'Haute-Saone', 'Bourgogne-Franche-Comte', 1),
    ('71', 'Saone-et-Loire', 'Bourgogne-Franche-Comte', 1),
    ('72', 'Sarthe', 'Pays de la Loire', 1),
    ('73', 'Savoie', 'Auvergne-Rhone-Alpes', 0),
    ('74', 'Haute-Savoie', 'Auvergne-Rhone-Alpes', 0),
    ('75', 'Paris', 'Ile-de-France', 0),
    ('76', 'Seine-Maritime', 'Normandie', 0),
    ('77', 'Seine-et-Marne', 'Ile-de-France', 1),
    ('78', 'Yvelines', 'Ile-de-France', 1),
    ('79', 'Deux-Sevres', 'Nouvelle-Aquitaine', 1),
    ('80', 'Somme', 'Hauts-de-France', 1),
    ('81', 'Tarn', 'Occitanie', 1),
    ('82', 'Tarn-et-Garonne', 'Occitanie', 1),
    ('83', 'Var', "Provence-Alpes-Cote d'Azur", 0),
    ('84', 'Vaucluse', "Provence-Alpes-Cote d'Azur", 0),
    ('85', 'Vendee', 'Pays de la Loire', 1),
    ('86', 'Vienne', 'Nouvelle-Aquitaine', 1),
    ('87', 'Haute-Vienne', 'Nouvelle-Aquitaine', 1),
    ('88', 'Vosges', 'Grand Est', 1),
    ('89', 'Yonne', 'Bourgogne-Franche-Comte', 1),
    ('90', 'Territoire de Belfort', 'Bourgogne-Franche-Comte', 1),
    ('91', 'Essonne', 'Ile-de-France', 1),
    ('92', 'Hauts-de-Seine', 'Ile-de-France', 1),
    ('93', 'Seine-Saint-Denis', 'Ile-de-France', 1),
    ('94', 'Val-de-Marne', 'Ile-de-France', 1),
    ('95', "Val-d'Oise", 'Ile-de-France', 1),
    ('971', 'Guadeloupe', 'Outre-mer', 0),
    ('972', 'Martinique', 'Outre-mer', 0),
    ('973', 'Guyane', 'Outre-mer', 0),
    ('974', 'La Reunion', 'Outre-mer', 0),
    ('976', 'Mayotte', 'Outre-mer', 0),
]

NAME = {c: n for c, n, _, _ in DEPS}
REGION = {c: r for c, _, r, _ in DEPS}
TIER = {c: t for c, _, _, t in DEPS}

DEPT_FLAG_FILE = {
    '01': 'Flag of Ain.svg',
    '02': 'Drapeau fr département Aisne.svg',
    '03': 'Drapeau fr département Allier.svg',
    '04': 'Drapeau fr département Alpes-de-Haute-Provence.svg',
    '05': 'Flag of Hautes-Alpes.svg',
    '06': 'Drapèu de la Contèa de Niça.svg',
    '07': 'Drapeau fr département Ardèche.svg',
    '08': 'Drapeau fr département Ardennes.svg',
    '09': "Proposition de drapeau pour le département de l'Ariège.svg",
    '10': 'Drapeau fr département Aube.svg',
    '11': 'Drapeau non-officiel fr département Aude.svg',
    '12': 'Flag of Rouergue.svg',
    '13': 'Proposition de drapeau fr département Bouches-du-Rhône.svg',
    '14': 'Flag of Calvados.svg',
    '15': 'Drapeau fr département Cantal.svg',
    '16': 'Flag of Charente.svg',
    '17': 'CharenteMaritimeFlag.svg',
    '18': 'Drapeau fr département Cher.svg',
    '19': 'Drapeau département fr Corrèze.svg',
    '21': "Drapeau non-officiel fr département Côte-d'Or.svg",
    '22': "Flag of the Department of Côtes-d'Armor.svg",
    '23': 'Drapeau fr département Creuse.svg',
    '24': 'Drapeau fr département Dordogne.svg',
    '25': 'Proposed flag of Doubs.svg',
    '26': 'Drapeau département fr Drôme.svg',
    '27': 'Blason département fr Eure.svg',
    '28': 'Flag of Eure-et-Loir.svg',
    '29': 'Drapeau Finistère.svg',
    '2A': 'Flag of Corsica.svg',
    '2B': 'Flag of Corsica.svg',
    '30': 'Drapeau non-officiel fr département Gard.svg',
    '31': 'Drapeau non-officiel fr département Haute-Garonne.svg',
    '32': 'Flag of Gers.svg',
    '33': 'Flag of Gironde.svg',
    '34': 'Drapeau culturel fr département Hérault.svg',
    '35': 'Drapeau non-officiel fr département Ille-et-Vilaine.svg',
    '36': 'Drapeau département fr Indre.svg',
    '37': 'Drapeau non-officiel fr département Indre-et-Loire.svg',
    '38': 'Flag of Isère.svg',
    '39': 'Flag of Jura (department).svg',
    '40': 'Drapeau fr département Landes.svg',
    '41': 'Drapeau fr département Loir-et-Cher.svg',
    '42': 'Drapeau fr département Loire.svg',
    '43': 'Drapeau département fr Haute-Loire.svg',
    '44': 'Drapeau fr département Loire-Atlantique.svg',
    '45': 'Flag of the Department of Loiret.svg',
    '46': 'Cultural flag of Lot.svg',
    '47': 'Blason département fr Lot-et-Garonne2.svg',
    '48': 'Drapeau non-officiel fr département Lozère.svg',
    '49': 'Flag of Anjou.svg',
    '50': 'Drapeau non-officiel fr département Manche.svg',
    '51': 'Drapeau fr département Marne.svg',
    '52': 'Drapeau fr département Haute-Marne.svg',
    '53': 'Drapeau fr département Mayenne.svg',
    '54': 'Drapeau fr département Meurthe-et-Moselle.svg',
    '55': 'Drapeau fr département Meuse.svg',
    '56': 'Drapeau fr département Morbihan.svg',
    '57': 'MoselleFlag.gif',
    '58': 'Drapeau fr département Nièvre.svg',
    '59': 'Blason Nord-Pas-De-Calais.svg',
    '60': 'Drapeau fr département Oise.svg',
    '61': 'Flag of Orne.svg',
    '62': 'Unofficial Flag of Pas-De-Calais.svg',
    '63': 'Drapeau proposé pour le département Puy-de-Dôme.svg',
    '64': 'Drapeau proposé pour les Pyrenees-atlantiques.svg',
    '65': 'Proposed flag for Hautes-Pyrénées.svg',
    '66': 'Drapeau proposé pour le département des Pyrénées-Orientales.svg',
    '67': 'Flag of Basse-Alsace.svg',
    '68': 'Flag of Haute-Alsace.svg',
    '69': 'Circonscription départementale du Rhône.svg',
    '70': 'Drapeau fr département Haute-Saône.svg',
    '71': 'Proposition de drapeau pour le département de Saône-et-Loire.svg',
    '72': 'Drapeau fr département Sarthe.svg',
    '73': 'Flag of Savoie.svg',
    '74': 'Blason département fr Haute-Savoie.svg',
    '75': 'Drapeau des armes de la ville de Paris.svg',
    '76': 'Proposed flag for Seine-Maritime.svg',
    '77': 'Drapeau culturel pour le département de Seine-et-Marne.svg',
    '78': 'Drapeau fr département Yvelines.svg',
    '79': 'Drapeau fr département Deux-Sèvres.svg',
    '80': 'Drapeau fr département Somme.svg',
    '81': 'Drapeau fr département Tarn.svg',
    '82': 'Proposed flag for Tarn-et-Garonne.gif',
    '83': 'Proposition de drapeau pour le Var.svg',
    '84': 'Drapeau fr département Vaucluse.svg',
    '85': 'Flag of Vendée.svg',
    '86': 'Drapeau fr département Vienne.svg',
    '87': 'Drapeau fr département Haute-Vienne.svg',
    '88': 'Flag of Vosges.svg',
    '89': 'Drapeau fr département Yonne.svg',
    '90': 'Drapeau fr département Territoire de Belfort.svg',
    '91': 'Drapeau fr département Essonne.svg',
    '92': 'Drapeau fr département Hauts-de-Seine.svg',
    '93': 'Proposition de drapeau fr département Seine-Saint-Denis.svg',
    '94': 'Drapeau fr département Val-de-Marne.svg',
    '95': "Drapeau fr département Val-d'Oise.svg",
    '971': 'Coat of arms of Guadeloupe.svg',
    '972': 'Flag-of-Martinique.svg',
    '973': 'Coat of arms of French Guiana, according to the original displayed at the Museum Franconie, at Cayenne.svg',
    '974': 'Proposed flag of Réunion (VAR).svg',
    '976': 'Flag of Mayotte (Local).svg',
}
