using { /Verse.org/Assets }

# athletes_bank.verse — Quizz ATHLETES (photos Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

AthletesDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeAthletesQuestionsFR() : []question =
    array:
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0001 }
            Reponses := array{"Lionel Messi", "Mike Tyson", "Neymar", "Zlatan Ibrahimovic"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0002 }
            Reponses := array{"Cristiano Ronaldo", "Tom Brady", "Max Verstappen", "Karim Benzema"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0003 }
            Reponses := array{"Kylian Mbappe", "Stephen Curry", "Muhammad Ali", "Usain Bolt"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0004 }
            Reponses := array{"Diego Maradona", "Neymar", "Novak Djokovic", "Lionel Messi"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0005 }
            Reponses := array{"Roger Federer", "Michael Phelps", "Zlatan Ibrahimovic", "Kobe Bryant"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0006 }
            Reponses := array{"Usain Bolt", "Karim Benzema", "Muhammad Ali", "Teddy Riner"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0007 }
            Reponses := array{"Erling Haaland", "Shaquille O'Neal", "Cristiano Ronaldo", "Pele"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0008 }
            Reponses := array{"Mohamed Salah", "Lewis Hamilton", "Lionel Messi", "Zlatan Ibrahimovic"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0009 }
            Reponses := array{"Usain Bolt", "Michael Phelps", "Zlatan Ibrahimovic", "LeBron James"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0010 }
            Reponses := array{"Michael Jordan", "Max Verstappen", "Cristiano Ronaldo", "Shaquille O'Neal"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0011 }
            Reponses := array{"LeBron James", "Shaquille O'Neal", "Ronaldinho", "Teddy Riner"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0012 }
            Reponses := array{"Shaquille O'Neal", "Teddy Riner", "Serena Williams", "Kobe Bryant"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0013 }
            Reponses := array{"Roger Federer", "Stephen Curry", "Kylian Mbappe", "Diego Maradona"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0014 }
            Reponses := array{"Muhammad Ali", "Lewis Hamilton", "Shaquille O'Neal", "Novak Djokovic"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0015 }
            Reponses := array{"Teddy Riner", "Tiger Woods", "Muhammad Ali", "LeBron James"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0016 }
            Reponses := array{"Pele", "Tom Brady", "Lionel Messi", "Mike Tyson"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0017 }
            Reponses := array{"Roger Federer", "Shaquille O'Neal", "Lionel Messi", "Max Verstappen"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0018 }
            Reponses := array{"Kylian Mbappe", "Zlatan Ibrahimovic", "Rafael Nadal", "Serena Williams"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0019 }
            Reponses := array{"Novak Djokovic", "Teddy Riner", "Usain Bolt", "Kylian Mbappe"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0020 }
            Reponses := array{"Ronaldinho", "Pele", "Serena Williams", "Lewis Hamilton"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0021 }
            Reponses := array{"Pele", "Michael Schumacher", "Tiger Woods", "Diego Maradona"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0022 }
            Reponses := array{"Michael Phelps", "Diego Maradona", "Neymar", "Rafael Nadal"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0023 }
            Reponses := array{"Neymar", "Zlatan Ibrahimovic", "Shaquille O'Neal", "Lewis Hamilton"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0024 }
            Reponses := array{"Tiger Woods", "Max Verstappen", "Michael Schumacher", "Ronaldinho"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0025 }
            Reponses := array{"Roger Federer", "Max Verstappen", "Mohamed Salah", "Mike Tyson"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0026 }
            Reponses := array{"Neymar", "Serena Williams", "Tom Brady", "Stephen Curry"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0027 }
            Reponses := array{"Michael Phelps", "Usain Bolt", "Pele", "Zlatan Ibrahimovic"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0028 }
            Reponses := array{"Lewis Hamilton", "Lionel Messi", "Diego Maradona", "Rafael Nadal"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0029 }
            Reponses := array{"Stephen Curry", "Pele", "Rafael Nadal", "Ronaldinho"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0030 }
            Reponses := array{"Teddy Riner", "Mike Tyson", "Rafael Nadal", "Kobe Bryant"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0031 }
            Reponses := array{"Antoine Griezmann", "Tony Parker", "Andrea Pirlo", "Naomi Osaka"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0032 }
            Reponses := array{"Andrea Pirlo", "Sadio Mane", "Dirk Nowitzki", "Paul Pogba"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0033 }
            Reponses := array{"Naomi Osaka", "Wayne Rooney", "N'Golo Kante", "Toni Kroos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0034 }
            Reponses := array{"Andy Murray", "Kevin De Bruyne", "Olivier Giroud", "David Beckham"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0035 }
            Reponses := array{"Marc Marquez", "Giannis Antetokounmpo", "Hugo Lloris", "Carlos Alcaraz"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0036 }
            Reponses := array{"Andy Murray", "Didier Drogba", "Magic Johnson", "Luis Suarez"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0037 }
            Reponses := array{"Gareth Bale", "Samuel Eto'o", "Marc Marquez", "Sergio Ramos"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0038 }
            Reponses := array{"Hugo Lloris", "Antoine Griezmann", "Sadio Mane", "Luka Modric"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0039 }
            Reponses := array{"Gareth Bale", "N'Golo Kante", "Magic Johnson", "Luka Modric"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0040 }
            Reponses := array{"Vinicius Junior", "Tony Parker", "Robert Lewandowski", "Toni Kroos"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0041 }
            Reponses := array{"Robert Lewandowski", "Kevin Durant", "Andres Iniesta", "Victor Wembanyama"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0042 }
            Reponses := array{"Harry Kane", "Magic Johnson", "Kevin De Bruyne", "Paul Pogba"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0043 }
            Reponses := array{"Kevin Durant", "Kevin De Bruyne", "Paul Pogba", "Toni Kroos"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0044 }
            Reponses := array{"Magic Johnson", "Luis Suarez", "Sadio Mane", "Vinicius Junior"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0045 }
            Reponses := array{"Wayne Rooney", "Vinicius Junior", "Lamine Yamal", "Jude Bellingham"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0046 }
            Reponses := array{"Tony Parker", "Lamine Yamal", "Eden Hazard", "Dirk Nowitzki"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0047 }
            Reponses := array{"Sergio Ramos", "Carlos Alcaraz", "Andrea Pirlo", "Tony Parker"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0048 }
            Reponses := array{"Magic Johnson", "Antoine Griezmann", "Andres Iniesta", "Toni Kroos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0049 }
            Reponses := array{"Harry Kane", "Sadio Mane", "Victor Wembanyama", "Andrea Pirlo"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0050 }
            Reponses := array{"Vinicius Junior", "Andres Iniesta", "Carlos Alcaraz", "David Beckham"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0051 }
            Reponses := array{"Marc Marquez", "Luis Suarez", "Giannis Antetokounmpo", "Wayne Rooney"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0052 }
            Reponses := array{"Andres Iniesta", "Luis Suarez", "Thierry Henry", "Harry Kane"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0053 }
            Reponses := array{"Marc Marquez", "Thierry Henry", "Alain Prost", "Eden Hazard"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0054 }
            Reponses := array{"Magic Johnson", "Kevin Durant", "Robert Lewandowski", "Gareth Bale"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0055 }
            Reponses := array{"Andy Murray", "Kevin De Bruyne", "Dirk Nowitzki", "Luis Suarez"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0056 }
            Reponses := array{"Carlos Alcaraz", "Sebastian Vettel", "Giannis Antetokounmpo", "Fernando Alonso"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0057 }
            Reponses := array{"Sadio Mane", "Didier Drogba", "Gareth Bale", "Sebastian Vettel"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0058 }
            Reponses := array{"Lamine Yamal", "Gareth Bale", "Harry Kane", "Ayrton Senna"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0059 }
            Reponses := array{"Robert Lewandowski", "Luis Suarez", "Alain Prost", "Ayrton Senna"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0060 }
            Reponses := array{"Sergio Ramos", "Kevin Durant", "Valentino Rossi", "Ayrton Senna"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0061 }
            Reponses := array{"Andrea Pirlo", "Marc Marquez", "Andy Murray", "Harry Kane"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0062 }
            Reponses := array{"Dirk Nowitzki", "Jude Bellingham", "Lamine Yamal", "Andy Murray"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0063 }
            Reponses := array{"Giannis Antetokounmpo", "Carlos Alcaraz", "Sadio Mane", "Eden Hazard"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0064 }
            Reponses := array{"Luis Suarez", "Antoine Griezmann", "Gareth Bale", "Naomi Osaka"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0065 }
            Reponses := array{"Samuel Eto'o", "Kevin Durant", "Valentino Rossi", "Victor Wembanyama"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0066 }
            Reponses := array{"Vinicius Junior", "Olivier Giroud", "Giannis Antetokounmpo", "Antoine Griezmann"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0067 }
            Reponses := array{"Valentino Rossi", "Fernando Alonso", "Victor Wembanyama", "Kevin Durant"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0068 }
            Reponses := array{"Didier Drogba", "Tony Parker", "Ayrton Senna", "Kevin De Bruyne"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0069 }
            Reponses := array{"Vinicius Junior", "Kevin De Bruyne", "Andrea Pirlo", "Dirk Nowitzki"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0070 }
            Reponses := array{"Dirk Nowitzki", "Victor Wembanyama", "Magic Johnson", "Luka Modric"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0071 }
            Reponses := array{"Carl Lewis", "Oliver Kahn", "Floyd Mayweather", "Tadej Pogacar"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0072 }
            Reponses := array{"Babe Ruth", "Steffi Graf", "Jonas Vingegaard", "Jesse Owens"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0073 }
            Reponses := array{"Dan Carter", "Wayne Gretzky", "Cafu", "Mo Farah"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0074 }
            Reponses := array{"Eliud Kipchoge", "Johan Cruyff", "Paolo Maldini", "Khabib Nurmagomedov"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0075 }
            Reponses := array{"Armand Duplantis", "Martina Navratilova", "Leon Marchand", "Franz Beckenbauer"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0076 }
            Reponses := array{"Katie Ledecky", "Wayne Gretzky", "Carl Lewis", "Leon Marchand"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0077 }
            Reponses := array{"Leon Marchand", "Venus Williams", "Carl Lewis", "Tadej Pogacar"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0078 }
            Reponses := array{"Wayne Gretzky", "Tadej Pogacar", "Simone Biles", "Oliver Kahn"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0079 }
            Reponses := array{"Pete Sampras", "Fabio Cannavaro", "Nadia Comaneci", "Jonas Vingegaard"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0080 }
            Reponses := array{"Mo Farah", "Canelo Alvarez", "Katie Ledecky", "Floyd Mayweather"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0081 }
            Reponses := array{"Manny Pacquiao", "Eddy Merckx", "Leon Marchand", "Oliver Kahn"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0082 }
            Reponses := array{"Armand Duplantis", "John McEnroe", "Floyd Mayweather", "Canelo Alvarez"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0083 }
            Reponses := array{"John McEnroe", "Tyson Fury", "Oliver Kahn", "Tadej Pogacar"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0084 }
            Reponses := array{"Johan Cruyff", "Conor McGregor", "Jesse Owens", "Steffi Graf"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0085 }
            Reponses := array{"Bernard Hinault", "Dan Carter", "Khabib Nurmagomedov", "Roberto Carlos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0086 }
            Reponses := array{"Oliver Kahn", "Jonas Vingegaard", "Paolo Maldini", "Georges St-Pierre"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0087 }
            Reponses := array{"Patrick Mahomes", "Eddy Merckx", "Jesse Owens", "Oliver Kahn"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0088 }
            Reponses := array{"Tadej Pogacar", "Canelo Alvarez", "Fabio Cannavaro", "Armand Duplantis"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0089 }
            Reponses := array{"Tyson Fury", "Jonas Vingegaard", "Steffi Graf", "Martina Navratilova"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0090 }
            Reponses := array{"Wayne Gretzky", "Bernard Hinault", "Iker Casillas", "Antoine Dupont"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0091 }
            Reponses := array{"Franz Beckenbauer", "Oliver Kahn", "Mo Farah", "Antoine Dupont"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0092 }
            Reponses := array{"Fabio Cannavaro", "Jonah Lomu", "Martina Navratilova", "Canelo Alvarez"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0093 }
            Reponses := array{"Tadej Pogacar", "Nadia Comaneci", "Venus Williams", "Dan Carter"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0094 }
            Reponses := array{"Rory McIlroy", "Khabib Nurmagomedov", "Jesse Owens", "Jonas Vingegaard"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0095 }
            Reponses := array{"Patrick Mahomes", "Wayne Gretzky", "Nadia Comaneci", "Andre Agassi"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0096 }
            Reponses := array{"Patrick Mahomes", "Jesse Owens", "Leon Marchand", "Babe Ruth"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0097 }
            Reponses := array{"Iker Casillas", "Martina Navratilova", "Rory McIlroy", "Wayne Gretzky"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0098 }
            Reponses := array{"Bjorn Borg", "Manny Pacquiao", "Nadia Comaneci", "Tyson Fury"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0099 }
            Reponses := array{"Roberto Carlos", "Martina Navratilova", "John McEnroe", "Carl Lewis"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0100 }
            Reponses := array{"Fabio Cannavaro", "Cafu", "Pete Sampras", "Babe Ruth"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0101 }
            Reponses := array{"Pete Sampras", "Andre Agassi", "Paolo Maldini", "Cafu"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0102 }
            Reponses := array{"Wayne Gretzky", "Johan Cruyff", "Eddy Merckx", "Steffi Graf"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0103 }
            Reponses := array{"Martina Navratilova", "Nadia Comaneci", "Eddy Merckx", "Canelo Alvarez"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0104 }
            Reponses := array{"John McEnroe", "Steffi Graf", "Venus Williams", "Rory McIlroy"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0105 }
            Reponses := array{"Johan Cruyff", "Tadej Pogacar", "Mo Farah", "Martina Navratilova"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0106 }
            Reponses := array{"Franz Beckenbauer", "Georges St-Pierre", "Rory McIlroy", "Dan Carter"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0107 }
            Reponses := array{"Roberto Carlos", "Paolo Maldini", "Georges St-Pierre", "Leon Marchand"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0108 }
            Reponses := array{"Roberto Carlos", "Iker Casillas", "Paolo Maldini", "Martina Navratilova"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0109 }
            Reponses := array{"Cafu", "Paolo Maldini", "Fabio Cannavaro", "Tadej Pogacar"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0110 }
            Reponses := array{"Johan Cruyff", "Fabio Cannavaro", "Paolo Maldini", "Eric Cantona"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0111 }
            Reponses := array{"Pete Sampras", "Rory McIlroy", "Gianluigi Buffon", "Carl Lewis"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0112 }
            Reponses := array{"Iker Casillas", "Andre Agassi", "Georges St-Pierre", "Martina Navratilova"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0113 }
            Reponses := array{"Oliver Kahn", "Patrick Mahomes", "Jesse Owens", "Rory McIlroy"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cet athlete ?"
            Image := option{ athletes.ath_0114 }
            Reponses := array{"Eric Cantona", "Fabio Cannavaro", "Dan Carter", "Andre Agassi"}
            BonneReponse := 0

MakeAthletesQuestions() : []question =
    MakeAthletesQuestionsFR()

MakeAthletesQuestionsEN() : []question =
    Base := MakeAthletesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Who is this athlete?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeAthletesQuestionsES() : []question =
    Base := MakeAthletesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Quien es este atleta?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeAthletesQuestionsDE() : []question =
    Base := MakeAthletesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Wer ist dieser Sportler?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeAthletesQuestionsIT() : []question =
    Base := MakeAthletesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Chi e questo atleta?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }
