using { /Verse.org/Assets }

# clubs_bank.verse — Quizz CLUBS DE FOOT (blasons via Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

ClubsDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeClubsQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0001 }
            Reponses := array{"Paris Saint-Germain", "Manchester City", "Real Madrid", "Olympique de Marseille"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0002 }
            Reponses := array{"Arsenal", "Rangers", "Napoli", "FC Barcelone"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0003 }
            Reponses := array{"Olympique de Marseille", "Manchester United", "FC Barcelone", "AC Milan"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0004 }
            Reponses := array{"FC Barcelone", "Liverpool", "Manchester United", "FC Porto"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0005 }
            Reponses := array{"Chelsea", "Manchester United", "Benfica", "Napoli"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0006 }
            Reponses := array{"Arsenal", "Liverpool", "Rangers", "Napoli"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0007 }
            Reponses := array{"Arsenal", "Tottenham", "Atletico Madrid", "Manchester City"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0008 }
            Reponses := array{"AS Monaco", "Manchester United", "Paris Saint-Germain", "AC Milan"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0009 }
            Reponses := array{"Arsenal", "Bayern Munich", "AC Milan", "Ajax Amsterdam"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0010 }
            Reponses := array{"Atletico Madrid", "AS Roma", "Rangers", "Borussia Dortmund"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0011 }
            Reponses := array{"Juventus", "Napoli", "Inter Milan", "Paris Saint-Germain"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0012 }
            Reponses := array{"AC Milan", "Liverpool", "Arsenal", "Bayern Munich"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0013 }
            Reponses := array{"FC Porto", "Al Nassr", "Inter Milan", "Borussia Dortmund"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0014 }
            Reponses := array{"Atletico Madrid", "AS Roma", "Manchester United", "Arsenal"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0015 }
            Reponses := array{"AC Milan", "Tottenham", "Chelsea", "Celtic"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0016 }
            Reponses := array{"FC Porto", "Chelsea", "Olympique de Marseille", "Olympique Lyonnais"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0017 }
            Reponses := array{"Paris Saint-Germain", "Borussia Dortmund", "Olympique Lyonnais", "Arsenal"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0018 }
            Reponses := array{"Paris Saint-Germain", "Manchester City", "AS Monaco", "Bayern Munich"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0019 }
            Reponses := array{"Inter Miami", "FC Porto", "Al Nassr", "Ajax Amsterdam"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0020 }
            Reponses := array{"Juventus", "FC Porto", "AS Monaco", "FC Barcelone"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0021 }
            Reponses := array{"Benfica", "Napoli", "Real Madrid", "Inter Milan"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0022 }
            Reponses := array{"Manchester City", "Tottenham", "Celtic", "Benfica"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0023 }
            Reponses := array{"Bayern Munich", "Rangers", "Inter Milan", "Napoli"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0024 }
            Reponses := array{"Tottenham", "Bayern Munich", "Napoli", "Real Madrid"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0025 }
            Reponses := array{"Borussia Dortmund", "Tottenham", "AS Roma", "Juventus"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0026 }
            Reponses := array{"Al Nassr", "Tottenham", "Inter Milan", "AS Monaco"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0027 }
            Reponses := array{"Benfica", "Inter Miami", "Liverpool", "Napoli"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0028 }
            Reponses := array{"Eintracht Francfort", "Atalanta", "West Ham United", "FC Seville"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0029 }
            Reponses := array{"Aston Villa", "Valence CF", "Fiorentina", "VfB Stuttgart"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0030 }
            Reponses := array{"Fenerbahce", "Galatasaray", "Real Betis", "Villarreal"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0031 }
            Reponses := array{"LA Galaxy", "VfB Stuttgart", "Everton", "Real Sociedad"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0032 }
            Reponses := array{"Leicester City", "VfB Stuttgart", "Athletic Bilbao", "Flamengo"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0033 }
            Reponses := array{"West Ham United", "Eintracht Francfort", "Real Betis", "LOSC Lille"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0034 }
            Reponses := array{"Galatasaray", "Stade Rennais", "Bayer Leverkusen", "OGC Nice"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0035 }
            Reponses := array{"RC Lens", "FC Nantes", "Schalke 04", "RB Leipzig"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0036 }
            Reponses := array{"Athletic Bilbao", "Fenerbahce", "Schalke 04", "Feyenoord"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0037 }
            Reponses := array{"Leicester City", "River Plate", "VfB Stuttgart", "Flamengo"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0038 }
            Reponses := array{"Feyenoord", "River Plate", "Bayer Leverkusen", "Eintracht Francfort"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0039 }
            Reponses := array{"Santos FC", "Palmeiras", "West Ham United", "Newcastle United"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0040 }
            Reponses := array{"Real Sociedad", "West Ham United", "Leicester City", "Valence CF"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0041 }
            Reponses := array{"RC Lens", "OGC Nice", "Valence CF", "Everton"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0042 }
            Reponses := array{"Boca Juniors", "Aston Villa", "Galatasaray", "AS Saint-Etienne"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0043 }
            Reponses := array{"Aston Villa", "Newcastle United", "Stade Rennais", "Leicester City"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0044 }
            Reponses := array{"Leeds United", "Lazio Rome", "FC Seville", "Leicester City"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0045 }
            Reponses := array{"LOSC Lille", "Stade Rennais", "FC Nantes", "Everton"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0046 }
            Reponses := array{"Schalke 04", "FC Nantes", "Fiorentina", "VfB Stuttgart"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0047 }
            Reponses := array{"Besiktas", "AS Saint-Etienne", "Everton", "OGC Nice"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0048 }
            Reponses := array{"Aston Villa", "Fenerbahce", "Stade Rennais", "Eintracht Francfort"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0049 }
            Reponses := array{"Galatasaray", "Schalke 04", "RC Lens", "Santos FC"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0050 }
            Reponses := array{"PSV Eindhoven", "AS Saint-Etienne", "Leeds United", "Sporting Portugal"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0051 }
            Reponses := array{"Flamengo", "Valence CF", "Lazio Rome", "Sporting Portugal"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0052 }
            Reponses := array{"Schalke 04", "Fiorentina", "Fenerbahce", "Leicester City"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0053 }
            Reponses := array{"Newcastle United", "Atalanta", "Bayer Leverkusen", "Fiorentina"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0054 }
            Reponses := array{"PSV Eindhoven", "Besiktas", "Valence CF", "Eintracht Francfort"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0055 }
            Reponses := array{"Eintracht Francfort", "Santos FC", "FC Seville", "Feyenoord"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0056 }
            Reponses := array{"Boca Juniors", "Sporting Portugal", "Everton", "Atalanta"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0057 }
            Reponses := array{"Feyenoord", "Eintracht Francfort", "Boca Juniors", "Real Betis"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0058 }
            Reponses := array{"Besiktas", "River Plate", "Atalanta", "Boca Juniors"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0059 }
            Reponses := array{"OGC Nice", "Flamengo", "LA Galaxy", "Real Sociedad"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0060 }
            Reponses := array{"Santos FC", "Stade Rennais", "Eintracht Francfort", "Real Betis"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0061 }
            Reponses := array{"Stade Rennais", "Palmeiras", "RC Lens", "Feyenoord"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0062 }
            Reponses := array{"Sporting Portugal", "OGC Nice", "AS Saint-Etienne", "LA Galaxy"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0063 }
            Reponses := array{"Bayer Leverkusen", "River Plate", "Feyenoord", "Galatasaray"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0064 }
            Reponses := array{"Fenerbahce", "Galatasaray", "RB Leipzig", "Lazio Rome"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0065 }
            Reponses := array{"Besiktas", "VfB Stuttgart", "Fiorentina", "West Ham United"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0066 }
            Reponses := array{"Union Berlin", "Toulouse FC", "Shakhtar Donetsk", "Espanyol Barcelone"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0067 }
            Reponses := array{"Olympiakos", "Dynamo Kiev", "Getafe", "RC Strasbourg"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0068 }
            Reponses := array{"Osasuna", "Sampdoria", "Espanyol Barcelone", "Celta Vigo"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0069 }
            Reponses := array{"Anderlecht", "Getafe", "FC Cologne", "Osasuna"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0070 }
            Reponses := array{"Getafe", "Hambourg SV", "Osasuna", "FC Cologne"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0071 }
            Reponses := array{"Cagliari", "Genoa", "Club America", "Borussia Monchengladbach"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0072 }
            Reponses := array{"Seattle Sounders", "Werder Breme", "Olympiakos", "Brentford"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0073 }
            Reponses := array{"Angers SCO", "Udinese", "Cruz Azul", "Hambourg SV"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0074 }
            Reponses := array{"Crystal Palace", "Union Berlin", "Olympiakos", "Brentford"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0075 }
            Reponses := array{"FC Cologne", "Bologne FC", "Cagliari", "Crystal Palace"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0076 }
            Reponses := array{"Seattle Sounders", "Borussia Monchengladbach", "Brighton", "AJ Auxerre"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0077 }
            Reponses := array{"AJ Auxerre", "Nottingham Forest", "Wolverhampton", "Hambourg SV"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0078 }
            Reponses := array{"Hambourg SV", "Anderlecht", "Celta Vigo", "Fulham"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0079 }
            Reponses := array{"Wolverhampton", "Brentford", "Dynamo Kiev", "Union Berlin"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0080 }
            Reponses := array{"Parme", "Werder Breme", "Southampton", "Cruz Azul"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0081 }
            Reponses := array{"Bologne FC", "Red Bull Salzbourg", "Sampdoria", "Nottingham Forest"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0082 }
            Reponses := array{"RC Strasbourg", "Southampton", "Red Bull Salzbourg", "Hambourg SV"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0083 }
            Reponses := array{"RC Strasbourg", "Nottingham Forest", "Bologne FC", "Montpellier HSC"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0084 }
            Reponses := array{"Sao Paulo FC", "Brentford", "FC Metz", "Espanyol Barcelone"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0085 }
            Reponses := array{"Panathinaikos", "Stade Brestois", "Brighton", "Genoa"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0086 }
            Reponses := array{"Toulouse FC", "Espanyol Barcelone", "Stade Brestois", "Panathinaikos"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0087 }
            Reponses := array{"Osasuna", "Olympiakos", "AJ Auxerre", "Genoa"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0088 }
            Reponses := array{"Angers SCO", "Borussia Monchengladbach", "Werder Breme", "Sampdoria"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0089 }
            Reponses := array{"Bologne FC", "Olympiakos", "Brighton", "Le Havre AC"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0090 }
            Reponses := array{"Bologne FC", "Fulham", "Udinese", "Werder Breme"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0091 }
            Reponses := array{"Bologne FC", "Anderlecht", "Genoa", "Brighton"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0092 }
            Reponses := array{"Getafe", "Seattle Sounders", "FC Cologne", "Genoa"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0093 }
            Reponses := array{"Sao Paulo FC", "Udinese", "Genoa", "Sampdoria"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0094 }
            Reponses := array{"Crystal Palace", "Fulham", "Brighton", "Cagliari"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0095 }
            Reponses := array{"Anderlecht", "Genoa", "Club Bruges", "Parme"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0096 }
            Reponses := array{"Club America", "Angers SCO", "Cagliari", "Red Bull Salzbourg"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0097 }
            Reponses := array{"Club Bruges", "RC Strasbourg", "Brentford", "Crystal Palace"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0098 }
            Reponses := array{"Crystal Palace", "Anderlecht", "Club Bruges", "Wolverhampton"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0099 }
            Reponses := array{"Olympiakos", "Club America", "Shakhtar Donetsk", "Panathinaikos"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0100 }
            Reponses := array{"Panathinaikos", "Angers SCO", "AJ Auxerre", "Union Berlin"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0101 }
            Reponses := array{"Werder Breme", "Hambourg SV", "Espanyol Barcelone", "Shakhtar Donetsk"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0102 }
            Reponses := array{"Seattle Sounders", "Nottingham Forest", "Dynamo Kiev", "Sampdoria"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0103 }
            Reponses := array{"Fulham", "Anderlecht", "Union Berlin", "Sao Paulo FC"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0104 }
            Reponses := array{"Seattle Sounders", "Sao Paulo FC", "Cruz Azul", "AJ Auxerre"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0105 }
            Reponses := array{"Borussia Monchengladbach", "Montpellier HSC", "Club America", "Werder Breme"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce club de foot ?"
            Image := option{ clubs.club_0106 }
            Reponses := array{"Crystal Palace", "AJ Auxerre", "Seattle Sounders", "Anderlecht"}
            BonneReponse := 2

MakeClubsQuestions() : []question =
    MakeClubsQuestionsFR()

MakeClubsQuestionsEN() : []question =
    Base := MakeClubsQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Which football club is this?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeClubsQuestionsES() : []question =
    Base := MakeClubsQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Que club de futbol es este?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeClubsQuestionsDE() : []question =
    Base := MakeClubsQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Welcher Fussballverein ist das?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeClubsQuestionsIT() : []question =
    Base := MakeClubsQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Quale squadra di calcio e questa?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }
