# tableaux_bank style — Quizz ELEMENTS CHIMIQUES (118, texte)
# GENERE par tools/build_elements.py — NE PAS EDITER A LA MAIN.

ElementsDiff : []int = array{0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeElementsQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quel element a le symbole H ?"
            Reponses := array{"Mercure", "Hydrogene", "Potassium", "Sodium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole He ?"
            Reponses := array{"Silicium", "Nickel", "Helium", "Uranium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Li ?"
            Reponses := array{"Bismuth", "Lithium", "Arsenic", "Palladium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Be ?"
            Reponses := array{"Antimoine", "Iode", "Iridium", "Beryllium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole B ?"
            Reponses := array{"Palladium", "Germanium", "Zirconium", "Bore"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole C ?"
            Reponses := array{"Carbone", "Fer", "Sodium", "Or"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole N ?"
            Reponses := array{"Calcium", "Aluminium", "Uranium", "Azote"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole O ?"
            Reponses := array{"Calcium", "Oxygene", "Helium", "Chlore"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole F ?"
            Reponses := array{"Fluor", "Chlore", "Sodium", "Azote"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ne ?"
            Reponses := array{"Neon", "Soufre", "Sodium", "Etain"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Na ?"
            Reponses := array{"Mercure", "Oxygene", "Sodium", "Helium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Mg ?"
            Reponses := array{"Mercure", "Aluminium", "Magnesium", "Silicium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Al ?"
            Reponses := array{"Potassium", "Aluminium", "Oxygene", "Plomb"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Si ?"
            Reponses := array{"Calcium", "Soufre", "Zinc", "Silicium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole P ?"
            Reponses := array{"Phosphore", "Helium", "Fer", "Aluminium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole S ?"
            Reponses := array{"Potassium", "Hydrogene", "Soufre", "Magnesium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Cl ?"
            Reponses := array{"Chlore", "Neon", "Zinc", "Fluor"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ar ?"
            Reponses := array{"Zirconium", "Dysprosium", "Argon", "Lanthane"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole K ?"
            Reponses := array{"Or", "Aluminium", "Potassium", "Hydrogene"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Ca ?"
            Reponses := array{"Chlore", "Argent", "Azote", "Calcium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Sc ?"
            Reponses := array{"Europium", "Scandium", "Argon", "Baryum"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Ti ?"
            Reponses := array{"Cadmium", "Indium", "Yttrium", "Titane"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole V ?"
            Reponses := array{"Vanadium", "Europium", "Promethium", "Strontium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cr ?"
            Reponses := array{"Praseodyme", "Chrome", "Titane", "Beryllium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Mn ?"
            Reponses := array{"Rubidium", "Manganese", "Zirconium", "Tellure"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Fe ?"
            Reponses := array{"Phosphore", "Soufre", "Fer", "Fluor"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Co ?"
            Reponses := array{"Strontium", "Baryum", "Cobalt", "Titane"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Ni ?"
            Reponses := array{"Nickel", "Carbone", "Aluminium", "Phosphore"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cu ?"
            Reponses := array{"Magnesium", "Neon", "Cuivre", "Phosphore"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Zn ?"
            Reponses := array{"Zinc", "Carbone", "Hydrogene", "Cuivre"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ga ?"
            Reponses := array{"Zirconium", "Chrome", "Gallium", "Ruthenium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Ge ?"
            Reponses := array{"Hafnium", "Germanium", "Indium", "Tantale"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole As ?"
            Reponses := array{"Arsenic", "Samarium", "Rubidium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Se ?"
            Reponses := array{"Indium", "Iridium", "Ruthenium", "Selenium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Br ?"
            Reponses := array{"Brome", "Niobium", "Cadmium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Kr ?"
            Reponses := array{"Krypton", "Lanthane", "Ytterbium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Rb ?"
            Reponses := array{"Rubidium", "Rhodium", "Ruthenium", "Titane"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Sr ?"
            Reponses := array{"Vanadium", "Strontium", "Cadmium", "Erbium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Y ?"
            Reponses := array{"Yttrium", "Cobalt", "Iridium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Zr ?"
            Reponses := array{"Zirconium", "Tellure", "Erbium", "Praseodyme"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Nb ?"
            Reponses := array{"Brome", "Iridium", "Niobium", "Titane"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Mo ?"
            Reponses := array{"Chrome", "Cadmium", "Molybdene", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Tc ?"
            Reponses := array{"Cerium", "Cadmium", "Vanadium", "Technetium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Ru ?"
            Reponses := array{"Cesium", "Rhenium", "Ruthenium", "Thallium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Rh ?"
            Reponses := array{"Rhodium", "Europium", "Ruthenium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Pd ?"
            Reponses := array{"Osmium", "Palladium", "Lanthane", "Germanium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Ag ?"
            Reponses := array{"Argent", "Neon", "Fer", "Mercure"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cd ?"
            Reponses := array{"Antimoine", "Technetium", "Brome", "Cadmium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole In ?"
            Reponses := array{"Tungstene", "Titane", "Indium", "Bismuth"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Sn ?"
            Reponses := array{"Etain", "Helium", "Zinc", "Argent"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Sb ?"
            Reponses := array{"Erbium", "Vanadium", "Gadolinium", "Antimoine"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Te ?"
            Reponses := array{"Ruthenium", "Zirconium", "Tellure", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole I ?"
            Reponses := array{"Iode", "Dysprosium", "Ytterbium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Xe ?"
            Reponses := array{"Xenon", "Brome", "Palladium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cs ?"
            Reponses := array{"Cesium", "Cadmium", "Europium", "Cerium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ba ?"
            Reponses := array{"Lutecium", "Gallium", "Baryum", "Selenium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole La ?"
            Reponses := array{"Lanthane", "Xenon", "Rhenium", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ce ?"
            Reponses := array{"Vanadium", "Osmium", "Iode", "Cerium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Pr ?"
            Reponses := array{"Praseodyme", "Thallium", "Rubidium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Nd ?"
            Reponses := array{"Technetium", "Tungstene", "Molybdene", "Neodyme"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Pm ?"
            Reponses := array{"Beryllium", "Promethium", "Iridium", "Lutecium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Sm ?"
            Reponses := array{"Cadmium", "Promethium", "Samarium", "Arsenic"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Eu ?"
            Reponses := array{"Gadolinium", "Cadmium", "Europium", "Technetium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Gd ?"
            Reponses := array{"Krypton", "Lutecium", "Gadolinium", "Strontium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Tb ?"
            Reponses := array{"Terbium", "Brome", "Selenium", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Dy ?"
            Reponses := array{"Dysprosium", "Yttrium", "Iridium", "Molybdene"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ho ?"
            Reponses := array{"Strontium", "Cobalt", "Holmium", "Osmium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Er ?"
            Reponses := array{"Indium", "Dysprosium", "Erbium", "Vanadium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Tm ?"
            Reponses := array{"Thulium", "Iode", "Neodyme", "Terbium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Yb ?"
            Reponses := array{"Bismuth", "Ytterbium", "Vanadium", "Molybdene"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Lu ?"
            Reponses := array{"Erbium", "Praseodyme", "Lutecium", "Argon"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Hf ?"
            Reponses := array{"Lithium", "Promethium", "Palladium", "Hafnium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Ta ?"
            Reponses := array{"Tantale", "Scandium", "Strontium", "Yttrium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole W ?"
            Reponses := array{"Tungstene", "Palladium", "Ytterbium", "Neodyme"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Re ?"
            Reponses := array{"Rhenium", "Samarium", "Europium", "Lanthane"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Os ?"
            Reponses := array{"Thulium", "Argon", "Thallium", "Osmium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Ir ?"
            Reponses := array{"Rubidium", "Arsenic", "Iridium", "Praseodyme"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Pt ?"
            Reponses := array{"Helium", "Phosphore", "Platine", "Uranium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Au ?"
            Reponses := array{"Carbone", "Or", "Helium", "Nickel"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Hg ?"
            Reponses := array{"Mercure", "Calcium", "Chlore", "Magnesium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Tl ?"
            Reponses := array{"Thallium", "Arsenic", "Zirconium", "Scandium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Pb ?"
            Reponses := array{"Aluminium", "Plomb", "Nickel", "Azote"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Bi ?"
            Reponses := array{"Bismuth", "Ruthenium", "Cobalt", "Thallium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Po ?"
            Reponses := array{"Dubnium", "Actinium", "Polonium", "Americium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole At ?"
            Reponses := array{"Copernicium", "Hassium", "Dubnium", "Astate"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Rn ?"
            Reponses := array{"Livermorium", "Francium", "Radon", "Curium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Fr ?"
            Reponses := array{"Radon", "Francium", "Californium", "Lawrencium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Ra ?"
            Reponses := array{"Nobelium", "Protactinium", "Radon", "Radium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Ac ?"
            Reponses := array{"Roentgenium", "Actinium", "Hassium", "Astate"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Th ?"
            Reponses := array{"Thorium", "Curium", "Californium", "Bohrium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Pa ?"
            Reponses := array{"Copernicium", "Radium", "Livermorium", "Protactinium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole U ?"
            Reponses := array{"Or", "Nickel", "Uranium", "Argent"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Np ?"
            Reponses := array{"Hassium", "Bohrium", "Neptunium", "Thorium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Pu ?"
            Reponses := array{"Oganesson", "Fermium", "Plutonium", "Copernicium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Am ?"
            Reponses := array{"Americium", "Moscovium", "Protactinium", "Astate"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cm ?"
            Reponses := array{"Curium", "Livermorium", "Radon", "Rutherfordium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Bk ?"
            Reponses := array{"Berkelium", "Thorium", "Nihonium", "Mendelevium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Cf ?"
            Reponses := array{"Oganesson", "Californium", "Bohrium", "Fermium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Es ?"
            Reponses := array{"Copernicium", "Einsteinium", "Roentgenium", "Curium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Fm ?"
            Reponses := array{"Fermium", "Meitnerium", "Copernicium", "Moscovium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Md ?"
            Reponses := array{"Mendelevium", "Nihonium", "Livermorium", "Lawrencium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole No ?"
            Reponses := array{"Americium", "Fermium", "Nobelium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Lr ?"
            Reponses := array{"Rutherfordium", "Lawrencium", "Livermorium", "Mendelevium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Rf ?"
            Reponses := array{"Bohrium", "Rutherfordium", "Fermium", "Radon"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Db ?"
            Reponses := array{"Livermorium", "Roentgenium", "Dubnium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Sg ?"
            Reponses := array{"Dubnium", "Bohrium", "Seaborgium", "Radium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Bh ?"
            Reponses := array{"Lawrencium", "Astate", "Bohrium", "Oganesson"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Hs ?"
            Reponses := array{"Neptunium", "Radon", "Hassium", "Fermium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Mt ?"
            Reponses := array{"Meitnerium", "Roentgenium", "Dubnium", "Thorium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ds ?"
            Reponses := array{"Radon", "Roentgenium", "Hassium", "Darmstadtium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Rg ?"
            Reponses := array{"Rutherfordium", "Oganesson", "Francium", "Roentgenium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Cn ?"
            Reponses := array{"Hassium", "Astate", "Moscovium", "Copernicium"}
            BonneReponse := 3
        question:
            Enonce := "Quel element a le symbole Nh ?"
            Reponses := array{"Nihonium", "Dubnium", "Bohrium", "Francium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Fl ?"
            Reponses := array{"Radon", "Flerovium", "Dubnium", "Protactinium"}
            BonneReponse := 1
        question:
            Enonce := "Quel element a le symbole Mc ?"
            Reponses := array{"Copernicium", "Lawrencium", "Moscovium", "Bohrium"}
            BonneReponse := 2
        question:
            Enonce := "Quel element a le symbole Lv ?"
            Reponses := array{"Livermorium", "Nobelium", "Einsteinium", "Plutonium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Ts ?"
            Reponses := array{"Tennesse", "Lawrencium", "Seaborgium", "Darmstadtium"}
            BonneReponse := 0
        question:
            Enonce := "Quel element a le symbole Og ?"
            Reponses := array{"Oganesson", "Dubnium", "Actinium", "Roentgenium"}
            BonneReponse := 0

MakeElementsQuestionsEN() : []question =
    array:
        question:
            Enonce := "Which element has the symbol H?"
            Reponses := array{"Mercury", "Hydrogen", "Potassium", "Sodium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol He?"
            Reponses := array{"Silicon", "Nickel", "Helium", "Uranium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Li?"
            Reponses := array{"Bismuth", "Lithium", "Arsenic", "Palladium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Be?"
            Reponses := array{"Antimony", "Iodine", "Iridium", "Beryllium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol B?"
            Reponses := array{"Palladium", "Germanium", "Zirconium", "Boron"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol C?"
            Reponses := array{"Carbon", "Iron", "Sodium", "Gold"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol N?"
            Reponses := array{"Calcium", "Aluminium", "Uranium", "Nitrogen"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol O?"
            Reponses := array{"Calcium", "Oxygen", "Helium", "Chlorine"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol F?"
            Reponses := array{"Fluorine", "Chlorine", "Sodium", "Nitrogen"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ne?"
            Reponses := array{"Neon", "Sulfur", "Sodium", "Tin"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Na?"
            Reponses := array{"Mercury", "Oxygen", "Sodium", "Helium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Mg?"
            Reponses := array{"Mercury", "Aluminium", "Magnesium", "Silicon"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Al?"
            Reponses := array{"Potassium", "Aluminium", "Oxygen", "Lead"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Si?"
            Reponses := array{"Calcium", "Sulfur", "Zinc", "Silicon"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol P?"
            Reponses := array{"Phosphorus", "Helium", "Iron", "Aluminium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol S?"
            Reponses := array{"Potassium", "Hydrogen", "Sulfur", "Magnesium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Cl?"
            Reponses := array{"Chlorine", "Neon", "Zinc", "Fluorine"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ar?"
            Reponses := array{"Zirconium", "Dysprosium", "Argon", "Lanthanum"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol K?"
            Reponses := array{"Gold", "Aluminium", "Potassium", "Hydrogen"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Ca?"
            Reponses := array{"Chlorine", "Silver", "Nitrogen", "Calcium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Sc?"
            Reponses := array{"Europium", "Scandium", "Argon", "Barium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Ti?"
            Reponses := array{"Cadmium", "Indium", "Yttrium", "Titanium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol V?"
            Reponses := array{"Vanadium", "Europium", "Promethium", "Strontium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cr?"
            Reponses := array{"Praseodymium", "Chromium", "Titanium", "Beryllium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Mn?"
            Reponses := array{"Rubidium", "Manganese", "Zirconium", "Tellurium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Fe?"
            Reponses := array{"Phosphorus", "Sulfur", "Iron", "Fluorine"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Co?"
            Reponses := array{"Strontium", "Barium", "Cobalt", "Titanium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Ni?"
            Reponses := array{"Nickel", "Carbon", "Aluminium", "Phosphorus"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cu?"
            Reponses := array{"Magnesium", "Neon", "Copper", "Phosphorus"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Zn?"
            Reponses := array{"Zinc", "Carbon", "Hydrogen", "Copper"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ga?"
            Reponses := array{"Zirconium", "Chromium", "Gallium", "Ruthenium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Ge?"
            Reponses := array{"Hafnium", "Germanium", "Indium", "Tantalum"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol As?"
            Reponses := array{"Arsenic", "Samarium", "Rubidium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Se?"
            Reponses := array{"Indium", "Iridium", "Ruthenium", "Selenium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Br?"
            Reponses := array{"Bromine", "Niobium", "Cadmium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Kr?"
            Reponses := array{"Krypton", "Lanthanum", "Ytterbium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Rb?"
            Reponses := array{"Rubidium", "Rhodium", "Ruthenium", "Titanium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Sr?"
            Reponses := array{"Vanadium", "Strontium", "Cadmium", "Erbium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Y?"
            Reponses := array{"Yttrium", "Cobalt", "Iridium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Zr?"
            Reponses := array{"Zirconium", "Tellurium", "Erbium", "Praseodymium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Nb?"
            Reponses := array{"Bromine", "Iridium", "Niobium", "Titanium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Mo?"
            Reponses := array{"Chromium", "Cadmium", "Molybdenum", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Tc?"
            Reponses := array{"Cerium", "Cadmium", "Vanadium", "Technetium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Ru?"
            Reponses := array{"Caesium", "Rhenium", "Ruthenium", "Thallium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Rh?"
            Reponses := array{"Rhodium", "Europium", "Ruthenium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Pd?"
            Reponses := array{"Osmium", "Palladium", "Lanthanum", "Germanium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Ag?"
            Reponses := array{"Silver", "Neon", "Iron", "Mercury"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cd?"
            Reponses := array{"Antimony", "Technetium", "Bromine", "Cadmium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol In?"
            Reponses := array{"Tungsten", "Titanium", "Indium", "Bismuth"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Sn?"
            Reponses := array{"Tin", "Helium", "Zinc", "Silver"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Sb?"
            Reponses := array{"Erbium", "Vanadium", "Gadolinium", "Antimony"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Te?"
            Reponses := array{"Ruthenium", "Zirconium", "Tellurium", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol I?"
            Reponses := array{"Iodine", "Dysprosium", "Ytterbium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Xe?"
            Reponses := array{"Xenon", "Bromine", "Palladium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cs?"
            Reponses := array{"Caesium", "Cadmium", "Europium", "Cerium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ba?"
            Reponses := array{"Lutetium", "Gallium", "Barium", "Selenium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol La?"
            Reponses := array{"Lanthanum", "Xenon", "Rhenium", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ce?"
            Reponses := array{"Vanadium", "Osmium", "Iodine", "Cerium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Pr?"
            Reponses := array{"Praseodymium", "Thallium", "Rubidium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Nd?"
            Reponses := array{"Technetium", "Tungsten", "Molybdenum", "Neodymium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Pm?"
            Reponses := array{"Beryllium", "Promethium", "Iridium", "Lutetium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Sm?"
            Reponses := array{"Cadmium", "Promethium", "Samarium", "Arsenic"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Eu?"
            Reponses := array{"Gadolinium", "Cadmium", "Europium", "Technetium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Gd?"
            Reponses := array{"Krypton", "Lutetium", "Gadolinium", "Strontium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Tb?"
            Reponses := array{"Terbium", "Bromine", "Selenium", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Dy?"
            Reponses := array{"Dysprosium", "Yttrium", "Iridium", "Molybdenum"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ho?"
            Reponses := array{"Strontium", "Cobalt", "Holmium", "Osmium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Er?"
            Reponses := array{"Indium", "Dysprosium", "Erbium", "Vanadium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Tm?"
            Reponses := array{"Thulium", "Iodine", "Neodymium", "Terbium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Yb?"
            Reponses := array{"Bismuth", "Ytterbium", "Vanadium", "Molybdenum"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Lu?"
            Reponses := array{"Erbium", "Praseodymium", "Lutetium", "Argon"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Hf?"
            Reponses := array{"Lithium", "Promethium", "Palladium", "Hafnium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Ta?"
            Reponses := array{"Tantalum", "Scandium", "Strontium", "Yttrium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol W?"
            Reponses := array{"Tungsten", "Palladium", "Ytterbium", "Neodymium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Re?"
            Reponses := array{"Rhenium", "Samarium", "Europium", "Lanthanum"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Os?"
            Reponses := array{"Thulium", "Argon", "Thallium", "Osmium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Ir?"
            Reponses := array{"Rubidium", "Arsenic", "Iridium", "Praseodymium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Pt?"
            Reponses := array{"Helium", "Phosphorus", "Platinum", "Uranium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Au?"
            Reponses := array{"Carbon", "Gold", "Helium", "Nickel"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Hg?"
            Reponses := array{"Mercury", "Calcium", "Chlorine", "Magnesium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Tl?"
            Reponses := array{"Thallium", "Arsenic", "Zirconium", "Scandium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Pb?"
            Reponses := array{"Aluminium", "Lead", "Nickel", "Nitrogen"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Bi?"
            Reponses := array{"Bismuth", "Ruthenium", "Cobalt", "Thallium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Po?"
            Reponses := array{"Dubnium", "Actinium", "Polonium", "Americium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol At?"
            Reponses := array{"Copernicium", "Hassium", "Dubnium", "Astatine"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Rn?"
            Reponses := array{"Livermorium", "Francium", "Radon", "Curium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Fr?"
            Reponses := array{"Radon", "Francium", "Californium", "Lawrencium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Ra?"
            Reponses := array{"Nobelium", "Protactinium", "Radon", "Radium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Ac?"
            Reponses := array{"Roentgenium", "Actinium", "Hassium", "Astatine"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Th?"
            Reponses := array{"Thorium", "Curium", "Californium", "Bohrium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Pa?"
            Reponses := array{"Copernicium", "Radium", "Livermorium", "Protactinium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol U?"
            Reponses := array{"Gold", "Nickel", "Uranium", "Silver"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Np?"
            Reponses := array{"Hassium", "Bohrium", "Neptunium", "Thorium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Pu?"
            Reponses := array{"Oganesson", "Fermium", "Plutonium", "Copernicium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Am?"
            Reponses := array{"Americium", "Moscovium", "Protactinium", "Astatine"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cm?"
            Reponses := array{"Curium", "Livermorium", "Radon", "Rutherfordium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Bk?"
            Reponses := array{"Berkelium", "Thorium", "Nihonium", "Mendelevium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Cf?"
            Reponses := array{"Oganesson", "Californium", "Bohrium", "Fermium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Es?"
            Reponses := array{"Copernicium", "Einsteinium", "Roentgenium", "Curium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Fm?"
            Reponses := array{"Fermium", "Meitnerium", "Copernicium", "Moscovium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Md?"
            Reponses := array{"Mendelevium", "Nihonium", "Livermorium", "Lawrencium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol No?"
            Reponses := array{"Americium", "Fermium", "Nobelium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Lr?"
            Reponses := array{"Rutherfordium", "Lawrencium", "Livermorium", "Mendelevium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Rf?"
            Reponses := array{"Bohrium", "Rutherfordium", "Fermium", "Radon"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Db?"
            Reponses := array{"Livermorium", "Roentgenium", "Dubnium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Sg?"
            Reponses := array{"Dubnium", "Bohrium", "Seaborgium", "Radium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Bh?"
            Reponses := array{"Lawrencium", "Astatine", "Bohrium", "Oganesson"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Hs?"
            Reponses := array{"Neptunium", "Radon", "Hassium", "Fermium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Mt?"
            Reponses := array{"Meitnerium", "Roentgenium", "Dubnium", "Thorium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ds?"
            Reponses := array{"Radon", "Roentgenium", "Hassium", "Darmstadtium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Rg?"
            Reponses := array{"Rutherfordium", "Oganesson", "Francium", "Roentgenium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Cn?"
            Reponses := array{"Hassium", "Astatine", "Moscovium", "Copernicium"}
            BonneReponse := 3
        question:
            Enonce := "Which element has the symbol Nh?"
            Reponses := array{"Nihonium", "Dubnium", "Bohrium", "Francium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Fl?"
            Reponses := array{"Radon", "Flerovium", "Dubnium", "Protactinium"}
            BonneReponse := 1
        question:
            Enonce := "Which element has the symbol Mc?"
            Reponses := array{"Copernicium", "Lawrencium", "Moscovium", "Bohrium"}
            BonneReponse := 2
        question:
            Enonce := "Which element has the symbol Lv?"
            Reponses := array{"Livermorium", "Nobelium", "Einsteinium", "Plutonium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Ts?"
            Reponses := array{"Tennessine", "Lawrencium", "Seaborgium", "Darmstadtium"}
            BonneReponse := 0
        question:
            Enonce := "Which element has the symbol Og?"
            Reponses := array{"Oganesson", "Dubnium", "Actinium", "Roentgenium"}
            BonneReponse := 0

MakeElementsQuestionsES() : []question =
    array:
        question:
            Enonce := "Que elemento tiene el simbolo H?"
            Reponses := array{"Mercurio", "Hidrogeno", "Potasio", "Sodio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo He?"
            Reponses := array{"Silicio", "Niquel", "Helio", "Uranio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Li?"
            Reponses := array{"Bismuto", "Litio", "Arsenico", "Paladio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Be?"
            Reponses := array{"Antimonio", "Yodo", "Iridio", "Berilio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo B?"
            Reponses := array{"Paladio", "Germanio", "Circonio", "Boro"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo C?"
            Reponses := array{"Carbono", "Hierro", "Sodio", "Oro"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo N?"
            Reponses := array{"Calcio", "Aluminio", "Uranio", "Nitrogeno"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo O?"
            Reponses := array{"Calcio", "Oxigeno", "Helio", "Cloro"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo F?"
            Reponses := array{"Fluor", "Cloro", "Sodio", "Nitrogeno"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ne?"
            Reponses := array{"Neon", "Azufre", "Sodio", "Estano"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Na?"
            Reponses := array{"Mercurio", "Oxigeno", "Sodio", "Helio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Mg?"
            Reponses := array{"Mercurio", "Aluminio", "Magnesio", "Silicio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Al?"
            Reponses := array{"Potasio", "Aluminio", "Oxigeno", "Plomo"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Si?"
            Reponses := array{"Calcio", "Azufre", "Cinc", "Silicio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo P?"
            Reponses := array{"Fosforo", "Helio", "Hierro", "Aluminio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo S?"
            Reponses := array{"Potasio", "Hidrogeno", "Azufre", "Magnesio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Cl?"
            Reponses := array{"Cloro", "Neon", "Cinc", "Fluor"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ar?"
            Reponses := array{"Circonio", "Disprosio", "Argon", "Lantano"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo K?"
            Reponses := array{"Oro", "Aluminio", "Potasio", "Hidrogeno"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Ca?"
            Reponses := array{"Cloro", "Plata", "Nitrogeno", "Calcio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Sc?"
            Reponses := array{"Europio", "Escandio", "Argon", "Bario"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Ti?"
            Reponses := array{"Cadmio", "Indio", "Itrio", "Titanio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo V?"
            Reponses := array{"Vanadio", "Europio", "Prometio", "Estroncio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cr?"
            Reponses := array{"Praseodimio", "Cromo", "Titanio", "Berilio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Mn?"
            Reponses := array{"Rubidio", "Manganeso", "Circonio", "Telurio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Fe?"
            Reponses := array{"Fosforo", "Azufre", "Hierro", "Fluor"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Co?"
            Reponses := array{"Estroncio", "Bario", "Cobalto", "Titanio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Ni?"
            Reponses := array{"Niquel", "Carbono", "Aluminio", "Fosforo"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cu?"
            Reponses := array{"Magnesio", "Neon", "Cobre", "Fosforo"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Zn?"
            Reponses := array{"Cinc", "Carbono", "Hidrogeno", "Cobre"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ga?"
            Reponses := array{"Circonio", "Cromo", "Galio", "Rutenio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Ge?"
            Reponses := array{"Hafnio", "Germanio", "Indio", "Tantalo"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo As?"
            Reponses := array{"Arsenico", "Samario", "Rubidio", "Indio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Se?"
            Reponses := array{"Indio", "Iridio", "Rutenio", "Selenio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Br?"
            Reponses := array{"Bromo", "Niobio", "Cadmio", "Prometio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Kr?"
            Reponses := array{"Cripton", "Lantano", "Iterbio", "Germanio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Rb?"
            Reponses := array{"Rubidio", "Rodio", "Rutenio", "Titanio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Sr?"
            Reponses := array{"Vanadio", "Estroncio", "Cadmio", "Erbio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Y?"
            Reponses := array{"Itrio", "Cobalto", "Iridio", "Germanio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Zr?"
            Reponses := array{"Circonio", "Telurio", "Erbio", "Praseodimio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Nb?"
            Reponses := array{"Bromo", "Iridio", "Niobio", "Titanio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Mo?"
            Reponses := array{"Cromo", "Cadmio", "Molibdeno", "Rubidio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Tc?"
            Reponses := array{"Cerio", "Cadmio", "Vanadio", "Tecnecio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Ru?"
            Reponses := array{"Cesio", "Renio", "Rutenio", "Talio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Rh?"
            Reponses := array{"Rodio", "Europio", "Rutenio", "Litio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Pd?"
            Reponses := array{"Osmio", "Paladio", "Lantano", "Germanio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Ag?"
            Reponses := array{"Plata", "Neon", "Hierro", "Mercurio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cd?"
            Reponses := array{"Antimonio", "Tecnecio", "Bromo", "Cadmio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo In?"
            Reponses := array{"Wolframio", "Titanio", "Indio", "Bismuto"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Sn?"
            Reponses := array{"Estano", "Helio", "Cinc", "Plata"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Sb?"
            Reponses := array{"Erbio", "Vanadio", "Gadolinio", "Antimonio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Te?"
            Reponses := array{"Rutenio", "Circonio", "Telurio", "Rubidio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo I?"
            Reponses := array{"Yodo", "Disprosio", "Iterbio", "Litio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Xe?"
            Reponses := array{"Xenon", "Bromo", "Paladio", "Indio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cs?"
            Reponses := array{"Cesio", "Cadmio", "Europio", "Cerio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ba?"
            Reponses := array{"Lutecio", "Galio", "Bario", "Selenio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo La?"
            Reponses := array{"Lantano", "Xenon", "Renio", "Paladio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ce?"
            Reponses := array{"Vanadio", "Osmio", "Yodo", "Cerio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Pr?"
            Reponses := array{"Praseodimio", "Talio", "Rubidio", "Prometio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Nd?"
            Reponses := array{"Tecnecio", "Wolframio", "Molibdeno", "Neodimio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Pm?"
            Reponses := array{"Berilio", "Prometio", "Iridio", "Lutecio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Sm?"
            Reponses := array{"Cadmio", "Prometio", "Samario", "Arsenico"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Eu?"
            Reponses := array{"Gadolinio", "Cadmio", "Europio", "Tecnecio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Gd?"
            Reponses := array{"Cripton", "Lutecio", "Gadolinio", "Estroncio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Tb?"
            Reponses := array{"Terbio", "Bromo", "Selenio", "Paladio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Dy?"
            Reponses := array{"Disprosio", "Itrio", "Iridio", "Molibdeno"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ho?"
            Reponses := array{"Estroncio", "Cobalto", "Holmio", "Osmio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Er?"
            Reponses := array{"Indio", "Disprosio", "Erbio", "Vanadio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Tm?"
            Reponses := array{"Tulio", "Yodo", "Neodimio", "Terbio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Yb?"
            Reponses := array{"Bismuto", "Iterbio", "Vanadio", "Molibdeno"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Lu?"
            Reponses := array{"Erbio", "Praseodimio", "Lutecio", "Argon"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Hf?"
            Reponses := array{"Litio", "Prometio", "Paladio", "Hafnio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Ta?"
            Reponses := array{"Tantalo", "Escandio", "Estroncio", "Itrio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo W?"
            Reponses := array{"Wolframio", "Paladio", "Iterbio", "Neodimio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Re?"
            Reponses := array{"Renio", "Samario", "Europio", "Lantano"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Os?"
            Reponses := array{"Tulio", "Argon", "Talio", "Osmio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Ir?"
            Reponses := array{"Rubidio", "Arsenico", "Iridio", "Praseodimio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Pt?"
            Reponses := array{"Helio", "Fosforo", "Platino", "Uranio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Au?"
            Reponses := array{"Carbono", "Oro", "Helio", "Niquel"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Hg?"
            Reponses := array{"Mercurio", "Calcio", "Cloro", "Magnesio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Tl?"
            Reponses := array{"Talio", "Arsenico", "Circonio", "Escandio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Pb?"
            Reponses := array{"Aluminio", "Plomo", "Niquel", "Nitrogeno"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Bi?"
            Reponses := array{"Bismuto", "Rutenio", "Cobalto", "Talio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Po?"
            Reponses := array{"Dubnio", "Actinio", "Polonio", "Americio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo At?"
            Reponses := array{"Copernicio", "Hassio", "Dubnio", "Astato"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Rn?"
            Reponses := array{"Livermorio", "Francio", "Radon", "Curio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Fr?"
            Reponses := array{"Radon", "Francio", "Californio", "Laurencio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Ra?"
            Reponses := array{"Nobelio", "Protactinio", "Radon", "Radio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Ac?"
            Reponses := array{"Roentgenio", "Actinio", "Hassio", "Astato"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Th?"
            Reponses := array{"Torio", "Curio", "Californio", "Bohrio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Pa?"
            Reponses := array{"Copernicio", "Radio", "Livermorio", "Protactinio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo U?"
            Reponses := array{"Oro", "Niquel", "Uranio", "Plata"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Np?"
            Reponses := array{"Hassio", "Bohrio", "Neptunio", "Torio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Pu?"
            Reponses := array{"Oganeson", "Fermio", "Plutonio", "Copernicio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Am?"
            Reponses := array{"Americio", "Moscovio", "Protactinio", "Astato"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cm?"
            Reponses := array{"Curio", "Livermorio", "Radon", "Rutherfordio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Bk?"
            Reponses := array{"Berkelio", "Torio", "Nihonio", "Mendelevio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Cf?"
            Reponses := array{"Oganeson", "Californio", "Bohrio", "Fermio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Es?"
            Reponses := array{"Copernicio", "Einstenio", "Roentgenio", "Curio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Fm?"
            Reponses := array{"Fermio", "Meitnerio", "Copernicio", "Moscovio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Md?"
            Reponses := array{"Mendelevio", "Nihonio", "Livermorio", "Laurencio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo No?"
            Reponses := array{"Americio", "Fermio", "Nobelio", "Moscovio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Lr?"
            Reponses := array{"Rutherfordio", "Laurencio", "Livermorio", "Mendelevio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Rf?"
            Reponses := array{"Bohrio", "Rutherfordio", "Fermio", "Radon"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Db?"
            Reponses := array{"Livermorio", "Roentgenio", "Dubnio", "Moscovio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Sg?"
            Reponses := array{"Dubnio", "Bohrio", "Seaborgio", "Radio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Bh?"
            Reponses := array{"Laurencio", "Astato", "Bohrio", "Oganeson"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Hs?"
            Reponses := array{"Neptunio", "Radon", "Hassio", "Fermio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Mt?"
            Reponses := array{"Meitnerio", "Roentgenio", "Dubnio", "Torio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ds?"
            Reponses := array{"Radon", "Roentgenio", "Hassio", "Darmstatio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Rg?"
            Reponses := array{"Rutherfordio", "Oganeson", "Francio", "Roentgenio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Cn?"
            Reponses := array{"Hassio", "Astato", "Moscovio", "Copernicio"}
            BonneReponse := 3
        question:
            Enonce := "Que elemento tiene el simbolo Nh?"
            Reponses := array{"Nihonio", "Dubnio", "Bohrio", "Francio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Fl?"
            Reponses := array{"Radon", "Flerovio", "Dubnio", "Protactinio"}
            BonneReponse := 1
        question:
            Enonce := "Que elemento tiene el simbolo Mc?"
            Reponses := array{"Copernicio", "Laurencio", "Moscovio", "Bohrio"}
            BonneReponse := 2
        question:
            Enonce := "Que elemento tiene el simbolo Lv?"
            Reponses := array{"Livermorio", "Nobelio", "Einstenio", "Plutonio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Ts?"
            Reponses := array{"Teneso", "Laurencio", "Seaborgio", "Darmstatio"}
            BonneReponse := 0
        question:
            Enonce := "Que elemento tiene el simbolo Og?"
            Reponses := array{"Oganeson", "Dubnio", "Actinio", "Roentgenio"}
            BonneReponse := 0

MakeElementsQuestionsDE() : []question =
    array:
        question:
            Enonce := "Welches Element hat das Symbol H?"
            Reponses := array{"Quecksilber", "Wasserstoff", "Kalium", "Natrium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol He?"
            Reponses := array{"Silizium", "Nickel", "Helium", "Uran"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Li?"
            Reponses := array{"Bismut", "Lithium", "Arsen", "Palladium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Be?"
            Reponses := array{"Antimon", "Iod", "Iridium", "Beryllium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol B?"
            Reponses := array{"Palladium", "Germanium", "Zirkonium", "Bor"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol C?"
            Reponses := array{"Kohlenstoff", "Eisen", "Natrium", "Gold"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol N?"
            Reponses := array{"Kalzium", "Aluminium", "Uran", "Stickstoff"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol O?"
            Reponses := array{"Kalzium", "Sauerstoff", "Helium", "Chlor"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol F?"
            Reponses := array{"Fluor", "Chlor", "Natrium", "Stickstoff"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ne?"
            Reponses := array{"Neon", "Schwefel", "Natrium", "Zinn"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Na?"
            Reponses := array{"Quecksilber", "Sauerstoff", "Natrium", "Helium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Mg?"
            Reponses := array{"Quecksilber", "Aluminium", "Magnesium", "Silizium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Al?"
            Reponses := array{"Kalium", "Aluminium", "Sauerstoff", "Blei"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Si?"
            Reponses := array{"Kalzium", "Schwefel", "Zink", "Silizium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol P?"
            Reponses := array{"Phosphor", "Helium", "Eisen", "Aluminium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol S?"
            Reponses := array{"Kalium", "Wasserstoff", "Schwefel", "Magnesium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Cl?"
            Reponses := array{"Chlor", "Neon", "Zink", "Fluor"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ar?"
            Reponses := array{"Zirkonium", "Dysprosium", "Argon", "Lanthan"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol K?"
            Reponses := array{"Gold", "Aluminium", "Kalium", "Wasserstoff"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Ca?"
            Reponses := array{"Chlor", "Silber", "Stickstoff", "Kalzium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Sc?"
            Reponses := array{"Europium", "Scandium", "Argon", "Barium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Ti?"
            Reponses := array{"Cadmium", "Indium", "Yttrium", "Titan"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol V?"
            Reponses := array{"Vanadium", "Europium", "Promethium", "Strontium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cr?"
            Reponses := array{"Praseodym", "Chrom", "Titan", "Beryllium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Mn?"
            Reponses := array{"Rubidium", "Mangan", "Zirkonium", "Tellur"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Fe?"
            Reponses := array{"Phosphor", "Schwefel", "Eisen", "Fluor"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Co?"
            Reponses := array{"Strontium", "Barium", "Cobalt", "Titan"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Ni?"
            Reponses := array{"Nickel", "Kohlenstoff", "Aluminium", "Phosphor"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cu?"
            Reponses := array{"Magnesium", "Neon", "Kupfer", "Phosphor"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Zn?"
            Reponses := array{"Zink", "Kohlenstoff", "Wasserstoff", "Kupfer"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ga?"
            Reponses := array{"Zirkonium", "Chrom", "Gallium", "Ruthenium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Ge?"
            Reponses := array{"Hafnium", "Germanium", "Indium", "Tantal"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol As?"
            Reponses := array{"Arsen", "Samarium", "Rubidium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Se?"
            Reponses := array{"Indium", "Iridium", "Ruthenium", "Selen"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Br?"
            Reponses := array{"Brom", "Niob", "Cadmium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Kr?"
            Reponses := array{"Krypton", "Lanthan", "Ytterbium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Rb?"
            Reponses := array{"Rubidium", "Rhodium", "Ruthenium", "Titan"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Sr?"
            Reponses := array{"Vanadium", "Strontium", "Cadmium", "Erbium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Y?"
            Reponses := array{"Yttrium", "Cobalt", "Iridium", "Germanium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Zr?"
            Reponses := array{"Zirkonium", "Tellur", "Erbium", "Praseodym"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Nb?"
            Reponses := array{"Brom", "Iridium", "Niob", "Titan"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Mo?"
            Reponses := array{"Chrom", "Cadmium", "Molybdaen", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Tc?"
            Reponses := array{"Cer", "Cadmium", "Vanadium", "Technetium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Ru?"
            Reponses := array{"Caesium", "Rhenium", "Ruthenium", "Thallium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Rh?"
            Reponses := array{"Rhodium", "Europium", "Ruthenium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Pd?"
            Reponses := array{"Osmium", "Palladium", "Lanthan", "Germanium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Ag?"
            Reponses := array{"Silber", "Neon", "Eisen", "Quecksilber"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cd?"
            Reponses := array{"Antimon", "Technetium", "Brom", "Cadmium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol In?"
            Reponses := array{"Wolfram", "Titan", "Indium", "Bismut"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Sn?"
            Reponses := array{"Zinn", "Helium", "Zink", "Silber"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Sb?"
            Reponses := array{"Erbium", "Vanadium", "Gadolinium", "Antimon"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Te?"
            Reponses := array{"Ruthenium", "Zirkonium", "Tellur", "Rubidium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol I?"
            Reponses := array{"Iod", "Dysprosium", "Ytterbium", "Lithium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Xe?"
            Reponses := array{"Xenon", "Brom", "Palladium", "Indium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cs?"
            Reponses := array{"Caesium", "Cadmium", "Europium", "Cer"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ba?"
            Reponses := array{"Lutetium", "Gallium", "Barium", "Selen"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol La?"
            Reponses := array{"Lanthan", "Xenon", "Rhenium", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ce?"
            Reponses := array{"Vanadium", "Osmium", "Iod", "Cer"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Pr?"
            Reponses := array{"Praseodym", "Thallium", "Rubidium", "Promethium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Nd?"
            Reponses := array{"Technetium", "Wolfram", "Molybdaen", "Neodym"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Pm?"
            Reponses := array{"Beryllium", "Promethium", "Iridium", "Lutetium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Sm?"
            Reponses := array{"Cadmium", "Promethium", "Samarium", "Arsen"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Eu?"
            Reponses := array{"Gadolinium", "Cadmium", "Europium", "Technetium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Gd?"
            Reponses := array{"Krypton", "Lutetium", "Gadolinium", "Strontium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Tb?"
            Reponses := array{"Terbium", "Brom", "Selen", "Palladium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Dy?"
            Reponses := array{"Dysprosium", "Yttrium", "Iridium", "Molybdaen"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ho?"
            Reponses := array{"Strontium", "Cobalt", "Holmium", "Osmium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Er?"
            Reponses := array{"Indium", "Dysprosium", "Erbium", "Vanadium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Tm?"
            Reponses := array{"Thulium", "Iod", "Neodym", "Terbium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Yb?"
            Reponses := array{"Bismut", "Ytterbium", "Vanadium", "Molybdaen"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Lu?"
            Reponses := array{"Erbium", "Praseodym", "Lutetium", "Argon"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Hf?"
            Reponses := array{"Lithium", "Promethium", "Palladium", "Hafnium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Ta?"
            Reponses := array{"Tantal", "Scandium", "Strontium", "Yttrium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol W?"
            Reponses := array{"Wolfram", "Palladium", "Ytterbium", "Neodym"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Re?"
            Reponses := array{"Rhenium", "Samarium", "Europium", "Lanthan"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Os?"
            Reponses := array{"Thulium", "Argon", "Thallium", "Osmium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Ir?"
            Reponses := array{"Rubidium", "Arsen", "Iridium", "Praseodym"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Pt?"
            Reponses := array{"Helium", "Phosphor", "Platin", "Uran"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Au?"
            Reponses := array{"Kohlenstoff", "Gold", "Helium", "Nickel"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Hg?"
            Reponses := array{"Quecksilber", "Kalzium", "Chlor", "Magnesium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Tl?"
            Reponses := array{"Thallium", "Arsen", "Zirkonium", "Scandium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Pb?"
            Reponses := array{"Aluminium", "Blei", "Nickel", "Stickstoff"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Bi?"
            Reponses := array{"Bismut", "Ruthenium", "Cobalt", "Thallium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Po?"
            Reponses := array{"Dubnium", "Actinium", "Polonium", "Americium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol At?"
            Reponses := array{"Copernicium", "Hassium", "Dubnium", "Astat"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Rn?"
            Reponses := array{"Livermorium", "Francium", "Radon", "Curium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Fr?"
            Reponses := array{"Radon", "Francium", "Californium", "Lawrencium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Ra?"
            Reponses := array{"Nobelium", "Protactinium", "Radon", "Radium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Ac?"
            Reponses := array{"Roentgenium", "Actinium", "Hassium", "Astat"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Th?"
            Reponses := array{"Thorium", "Curium", "Californium", "Bohrium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Pa?"
            Reponses := array{"Copernicium", "Radium", "Livermorium", "Protactinium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol U?"
            Reponses := array{"Gold", "Nickel", "Uran", "Silber"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Np?"
            Reponses := array{"Hassium", "Bohrium", "Neptunium", "Thorium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Pu?"
            Reponses := array{"Oganesson", "Fermium", "Plutonium", "Copernicium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Am?"
            Reponses := array{"Americium", "Moscovium", "Protactinium", "Astat"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cm?"
            Reponses := array{"Curium", "Livermorium", "Radon", "Rutherfordium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Bk?"
            Reponses := array{"Berkelium", "Thorium", "Nihonium", "Mendelevium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Cf?"
            Reponses := array{"Oganesson", "Californium", "Bohrium", "Fermium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Es?"
            Reponses := array{"Copernicium", "Einsteinium", "Roentgenium", "Curium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Fm?"
            Reponses := array{"Fermium", "Meitnerium", "Copernicium", "Moscovium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Md?"
            Reponses := array{"Mendelevium", "Nihonium", "Livermorium", "Lawrencium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol No?"
            Reponses := array{"Americium", "Fermium", "Nobelium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Lr?"
            Reponses := array{"Rutherfordium", "Lawrencium", "Livermorium", "Mendelevium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Rf?"
            Reponses := array{"Bohrium", "Rutherfordium", "Fermium", "Radon"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Db?"
            Reponses := array{"Livermorium", "Roentgenium", "Dubnium", "Moscovium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Sg?"
            Reponses := array{"Dubnium", "Bohrium", "Seaborgium", "Radium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Bh?"
            Reponses := array{"Lawrencium", "Astat", "Bohrium", "Oganesson"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Hs?"
            Reponses := array{"Neptunium", "Radon", "Hassium", "Fermium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Mt?"
            Reponses := array{"Meitnerium", "Roentgenium", "Dubnium", "Thorium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ds?"
            Reponses := array{"Radon", "Roentgenium", "Hassium", "Darmstadtium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Rg?"
            Reponses := array{"Rutherfordium", "Oganesson", "Francium", "Roentgenium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Cn?"
            Reponses := array{"Hassium", "Astat", "Moscovium", "Copernicium"}
            BonneReponse := 3
        question:
            Enonce := "Welches Element hat das Symbol Nh?"
            Reponses := array{"Nihonium", "Dubnium", "Bohrium", "Francium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Fl?"
            Reponses := array{"Radon", "Flerovium", "Dubnium", "Protactinium"}
            BonneReponse := 1
        question:
            Enonce := "Welches Element hat das Symbol Mc?"
            Reponses := array{"Copernicium", "Lawrencium", "Moscovium", "Bohrium"}
            BonneReponse := 2
        question:
            Enonce := "Welches Element hat das Symbol Lv?"
            Reponses := array{"Livermorium", "Nobelium", "Einsteinium", "Plutonium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Ts?"
            Reponses := array{"Tenness", "Lawrencium", "Seaborgium", "Darmstadtium"}
            BonneReponse := 0
        question:
            Enonce := "Welches Element hat das Symbol Og?"
            Reponses := array{"Oganesson", "Dubnium", "Actinium", "Roentgenium"}
            BonneReponse := 0

MakeElementsQuestionsIT() : []question =
    array:
        question:
            Enonce := "Quale elemento ha il simbolo H?"
            Reponses := array{"Mercurio", "Idrogeno", "Potassio", "Sodio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo He?"
            Reponses := array{"Silicio", "Nichel", "Elio", "Uranio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Li?"
            Reponses := array{"Bismuto", "Litio", "Arsenico", "Palladio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Be?"
            Reponses := array{"Antimonio", "Iodio", "Iridio", "Berillio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo B?"
            Reponses := array{"Palladio", "Germanio", "Zirconio", "Boro"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo C?"
            Reponses := array{"Carbonio", "Ferro", "Sodio", "Oro"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo N?"
            Reponses := array{"Calcio", "Alluminio", "Uranio", "Azoto"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo O?"
            Reponses := array{"Calcio", "Ossigeno", "Elio", "Cloro"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo F?"
            Reponses := array{"Fluoro", "Cloro", "Sodio", "Azoto"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ne?"
            Reponses := array{"Neon", "Zolfo", "Sodio", "Stagno"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Na?"
            Reponses := array{"Mercurio", "Ossigeno", "Sodio", "Elio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Mg?"
            Reponses := array{"Mercurio", "Alluminio", "Magnesio", "Silicio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Al?"
            Reponses := array{"Potassio", "Alluminio", "Ossigeno", "Piombo"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Si?"
            Reponses := array{"Calcio", "Zolfo", "Zinco", "Silicio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo P?"
            Reponses := array{"Fosforo", "Elio", "Ferro", "Alluminio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo S?"
            Reponses := array{"Potassio", "Idrogeno", "Zolfo", "Magnesio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Cl?"
            Reponses := array{"Cloro", "Neon", "Zinco", "Fluoro"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ar?"
            Reponses := array{"Zirconio", "Disprosio", "Argon", "Lantanio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo K?"
            Reponses := array{"Oro", "Alluminio", "Potassio", "Idrogeno"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Ca?"
            Reponses := array{"Cloro", "Argento", "Azoto", "Calcio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Sc?"
            Reponses := array{"Europio", "Scandio", "Argon", "Bario"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Ti?"
            Reponses := array{"Cadmio", "Indio", "Ittrio", "Titanio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo V?"
            Reponses := array{"Vanadio", "Europio", "Promezio", "Stronzio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cr?"
            Reponses := array{"Praseodimio", "Cromo", "Titanio", "Berillio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Mn?"
            Reponses := array{"Rubidio", "Manganese", "Zirconio", "Tellurio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Fe?"
            Reponses := array{"Fosforo", "Zolfo", "Ferro", "Fluoro"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Co?"
            Reponses := array{"Stronzio", "Bario", "Cobalto", "Titanio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Ni?"
            Reponses := array{"Nichel", "Carbonio", "Alluminio", "Fosforo"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cu?"
            Reponses := array{"Magnesio", "Neon", "Rame", "Fosforo"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Zn?"
            Reponses := array{"Zinco", "Carbonio", "Idrogeno", "Rame"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ga?"
            Reponses := array{"Zirconio", "Cromo", "Gallio", "Rutenio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Ge?"
            Reponses := array{"Afnio", "Germanio", "Indio", "Tantalio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo As?"
            Reponses := array{"Arsenico", "Samario", "Rubidio", "Indio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Se?"
            Reponses := array{"Indio", "Iridio", "Rutenio", "Selenio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Br?"
            Reponses := array{"Bromo", "Niobio", "Cadmio", "Promezio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Kr?"
            Reponses := array{"Kripton", "Lantanio", "Itterbio", "Germanio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Rb?"
            Reponses := array{"Rubidio", "Rodio", "Rutenio", "Titanio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Sr?"
            Reponses := array{"Vanadio", "Stronzio", "Cadmio", "Erbio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Y?"
            Reponses := array{"Ittrio", "Cobalto", "Iridio", "Germanio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Zr?"
            Reponses := array{"Zirconio", "Tellurio", "Erbio", "Praseodimio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Nb?"
            Reponses := array{"Bromo", "Iridio", "Niobio", "Titanio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Mo?"
            Reponses := array{"Cromo", "Cadmio", "Molibdeno", "Rubidio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Tc?"
            Reponses := array{"Cerio", "Cadmio", "Vanadio", "Tecnezio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Ru?"
            Reponses := array{"Cesio", "Renio", "Rutenio", "Tallio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Rh?"
            Reponses := array{"Rodio", "Europio", "Rutenio", "Litio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Pd?"
            Reponses := array{"Osmio", "Palladio", "Lantanio", "Germanio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Ag?"
            Reponses := array{"Argento", "Neon", "Ferro", "Mercurio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cd?"
            Reponses := array{"Antimonio", "Tecnezio", "Bromo", "Cadmio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo In?"
            Reponses := array{"Tungsteno", "Titanio", "Indio", "Bismuto"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Sn?"
            Reponses := array{"Stagno", "Elio", "Zinco", "Argento"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Sb?"
            Reponses := array{"Erbio", "Vanadio", "Gadolinio", "Antimonio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Te?"
            Reponses := array{"Rutenio", "Zirconio", "Tellurio", "Rubidio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo I?"
            Reponses := array{"Iodio", "Disprosio", "Itterbio", "Litio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Xe?"
            Reponses := array{"Xeno", "Bromo", "Palladio", "Indio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cs?"
            Reponses := array{"Cesio", "Cadmio", "Europio", "Cerio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ba?"
            Reponses := array{"Lutezio", "Gallio", "Bario", "Selenio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo La?"
            Reponses := array{"Lantanio", "Xeno", "Renio", "Palladio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ce?"
            Reponses := array{"Vanadio", "Osmio", "Iodio", "Cerio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Pr?"
            Reponses := array{"Praseodimio", "Tallio", "Rubidio", "Promezio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Nd?"
            Reponses := array{"Tecnezio", "Tungsteno", "Molibdeno", "Neodimio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Pm?"
            Reponses := array{"Berillio", "Promezio", "Iridio", "Lutezio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Sm?"
            Reponses := array{"Cadmio", "Promezio", "Samario", "Arsenico"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Eu?"
            Reponses := array{"Gadolinio", "Cadmio", "Europio", "Tecnezio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Gd?"
            Reponses := array{"Kripton", "Lutezio", "Gadolinio", "Stronzio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Tb?"
            Reponses := array{"Terbio", "Bromo", "Selenio", "Palladio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Dy?"
            Reponses := array{"Disprosio", "Ittrio", "Iridio", "Molibdeno"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ho?"
            Reponses := array{"Stronzio", "Cobalto", "Olmio", "Osmio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Er?"
            Reponses := array{"Indio", "Disprosio", "Erbio", "Vanadio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Tm?"
            Reponses := array{"Tulio", "Iodio", "Neodimio", "Terbio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Yb?"
            Reponses := array{"Bismuto", "Itterbio", "Vanadio", "Molibdeno"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Lu?"
            Reponses := array{"Erbio", "Praseodimio", "Lutezio", "Argon"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Hf?"
            Reponses := array{"Litio", "Promezio", "Palladio", "Afnio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Ta?"
            Reponses := array{"Tantalio", "Scandio", "Stronzio", "Ittrio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo W?"
            Reponses := array{"Tungsteno", "Palladio", "Itterbio", "Neodimio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Re?"
            Reponses := array{"Renio", "Samario", "Europio", "Lantanio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Os?"
            Reponses := array{"Tulio", "Argon", "Tallio", "Osmio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Ir?"
            Reponses := array{"Rubidio", "Arsenico", "Iridio", "Praseodimio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Pt?"
            Reponses := array{"Elio", "Fosforo", "Platino", "Uranio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Au?"
            Reponses := array{"Carbonio", "Oro", "Elio", "Nichel"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Hg?"
            Reponses := array{"Mercurio", "Calcio", "Cloro", "Magnesio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Tl?"
            Reponses := array{"Tallio", "Arsenico", "Zirconio", "Scandio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Pb?"
            Reponses := array{"Alluminio", "Piombo", "Nichel", "Azoto"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Bi?"
            Reponses := array{"Bismuto", "Rutenio", "Cobalto", "Tallio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Po?"
            Reponses := array{"Dubnio", "Attinio", "Polonio", "Americio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo At?"
            Reponses := array{"Copernicio", "Hassio", "Dubnio", "Astato"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Rn?"
            Reponses := array{"Livermorio", "Francio", "Radon", "Curio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Fr?"
            Reponses := array{"Radon", "Francio", "Californio", "Laurenzio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Ra?"
            Reponses := array{"Nobelio", "Protoattinio", "Radon", "Radio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Ac?"
            Reponses := array{"Roentgenio", "Attinio", "Hassio", "Astato"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Th?"
            Reponses := array{"Torio", "Curio", "Californio", "Bohrio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Pa?"
            Reponses := array{"Copernicio", "Radio", "Livermorio", "Protoattinio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo U?"
            Reponses := array{"Oro", "Nichel", "Uranio", "Argento"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Np?"
            Reponses := array{"Hassio", "Bohrio", "Nettunio", "Torio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Pu?"
            Reponses := array{"Oganesson", "Fermio", "Plutonio", "Copernicio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Am?"
            Reponses := array{"Americio", "Moscovio", "Protoattinio", "Astato"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cm?"
            Reponses := array{"Curio", "Livermorio", "Radon", "Rutherfordio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Bk?"
            Reponses := array{"Berkelio", "Torio", "Nihonio", "Mendelevio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Cf?"
            Reponses := array{"Oganesson", "Californio", "Bohrio", "Fermio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Es?"
            Reponses := array{"Copernicio", "Einsteinio", "Roentgenio", "Curio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Fm?"
            Reponses := array{"Fermio", "Meitnerio", "Copernicio", "Moscovio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Md?"
            Reponses := array{"Mendelevio", "Nihonio", "Livermorio", "Laurenzio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo No?"
            Reponses := array{"Americio", "Fermio", "Nobelio", "Moscovio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Lr?"
            Reponses := array{"Rutherfordio", "Laurenzio", "Livermorio", "Mendelevio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Rf?"
            Reponses := array{"Bohrio", "Rutherfordio", "Fermio", "Radon"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Db?"
            Reponses := array{"Livermorio", "Roentgenio", "Dubnio", "Moscovio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Sg?"
            Reponses := array{"Dubnio", "Bohrio", "Seaborgio", "Radio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Bh?"
            Reponses := array{"Laurenzio", "Astato", "Bohrio", "Oganesson"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Hs?"
            Reponses := array{"Nettunio", "Radon", "Hassio", "Fermio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Mt?"
            Reponses := array{"Meitnerio", "Roentgenio", "Dubnio", "Torio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ds?"
            Reponses := array{"Radon", "Roentgenio", "Hassio", "Darmstadtio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Rg?"
            Reponses := array{"Rutherfordio", "Oganesson", "Francio", "Roentgenio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Cn?"
            Reponses := array{"Hassio", "Astato", "Moscovio", "Copernicio"}
            BonneReponse := 3
        question:
            Enonce := "Quale elemento ha il simbolo Nh?"
            Reponses := array{"Nihonio", "Dubnio", "Bohrio", "Francio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Fl?"
            Reponses := array{"Radon", "Flerovio", "Dubnio", "Protoattinio"}
            BonneReponse := 1
        question:
            Enonce := "Quale elemento ha il simbolo Mc?"
            Reponses := array{"Copernicio", "Laurenzio", "Moscovio", "Bohrio"}
            BonneReponse := 2
        question:
            Enonce := "Quale elemento ha il simbolo Lv?"
            Reponses := array{"Livermorio", "Nobelio", "Einsteinio", "Plutonio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Ts?"
            Reponses := array{"Tennessinio", "Laurenzio", "Seaborgio", "Darmstadtio"}
            BonneReponse := 0
        question:
            Enonce := "Quale elemento ha il simbolo Og?"
            Reponses := array{"Oganesson", "Dubnio", "Attinio", "Roentgenio"}
            BonneReponse := 0

MakeElementsQuestions() : []question =
    MakeElementsQuestionsFR()
