using { /Verse.org/Assets }

# espace_bank.verse — Quizz ESPACE (photos NASA/Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

EspaceDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeEspaceQuestionsFR() : []question =
    array:
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0001 }
            Reponses := array{"Big Bang", "Neptune", "Soleil", "Uranus"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0002 }
            Reponses := array{"Mercure", "Big Bang", "Terre", "Neptune"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0003 }
            Reponses := array{"Venus", "Lune", "Terre", "Voie lactee"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0004 }
            Reponses := array{"Apollo 11", "Terre", "Trou noir", "Hubble"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0005 }
            Reponses := array{"Venus", "Lune", "Hubble", "Pluton"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0006 }
            Reponses := array{"Mars", "Pluton", "Jupiter", "Trou noir"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0007 }
            Reponses := array{"Soleil", "Jupiter", "Comete", "Curiosity"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0008 }
            Reponses := array{"ISS", "Asteroide", "Mars", "Saturne"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0009 }
            Reponses := array{"Big Bang", "Uranus", "Apollo 11", "Trou noir"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0010 }
            Reponses := array{"Neptune", "Jupiter", "Curiosity", "Trou noir"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0011 }
            Reponses := array{"Eclipse solaire", "Navette spatiale", "Pluton", "Starship"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0012 }
            Reponses := array{"Asteroide", "Neptune", "Apollo 11", "Voie lactee"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0013 }
            Reponses := array{"Terre", "Trou noir", "Falcon 9", "Soleil"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0014 }
            Reponses := array{"Mercure", "Asteroide", "Lune", "Comete"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0015 }
            Reponses := array{"Neptune", "Curiosity", "Asteroide", "Navette spatiale"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0016 }
            Reponses := array{"Venus", "ISS", "Starship", "Saturne"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0017 }
            Reponses := array{"Hubble", "Soleil", "Saturn V", "Mars"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0018 }
            Reponses := array{"Apollo 11", "Voie lactee", "Venus", "Curiosity"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0019 }
            Reponses := array{"Neptune", "Lune", "Starship", "Saturn V"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0020 }
            Reponses := array{"Navette spatiale", "Hubble", "Big Bang", "Aurore boreale"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0021 }
            Reponses := array{"Lune", "Falcon 9", "Aurore boreale", "Apollo 11"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0022 }
            Reponses := array{"Trou noir", "Lune", "Uranus", "Curiosity"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0023 }
            Reponses := array{"Mars", "Neptune", "Eclipse solaire", "Soleil"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0024 }
            Reponses := array{"Aurore boreale", "Trou noir", "Navette spatiale", "Eclipse solaire"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0025 }
            Reponses := array{"Aurore boreale", "Trou noir", "Uranus", "Big Bang"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0026 }
            Reponses := array{"Eclipse solaire", "Falcon 9", "Starship", "Apollo 11"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0027 }
            Reponses := array{"Io", "Perseverance", "Ceres", "James Webb"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0028 }
            Reponses := array{"Orion", "Callisto", "Comete de Halley", "Europe"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0029 }
            Reponses := array{"Supernova", "Europe", "James Webb", "Ganymede"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0030 }
            Reponses := array{"Naine blanche", "Etoile a neutrons", "Callisto", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0031 }
            Reponses := array{"Titan", "Anneaux de Saturne", "Triton", "Deimos"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0032 }
            Reponses := array{"Encelade", "Ariane 5", "Etoile a neutrons", "Comete de Halley"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0033 }
            Reponses := array{"Callisto", "Nebuleuse d'Orion", "Triton", "Ariane 5"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0034 }
            Reponses := array{"Perseverance", "Callisto", "Phobos", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0035 }
            Reponses := array{"Io", "Orion", "Deimos", "Ganymede"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0036 }
            Reponses := array{"Ariane 5", "Voyager 1", "James Webb", "Ceres"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0037 }
            Reponses := array{"Naine blanche", "Comete de Halley", "Grande Ourse", "Phobos"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0038 }
            Reponses := array{"Mir", "Ceres", "Galaxie d'Andromede", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0039 }
            Reponses := array{"Soyouz", "Europe", "Callisto", "Nebuleuse d'Orion"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0040 }
            Reponses := array{"Io", "Europe", "Supernova", "Nebuleuse d'Orion"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0041 }
            Reponses := array{"Titan", "Voyager 1", "Naine blanche", "Encelade"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0042 }
            Reponses := array{"Etoile a neutrons", "Io", "Phobos", "Comete de Halley"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0043 }
            Reponses := array{"Deimos", "Ariane 5", "James Webb", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0044 }
            Reponses := array{"Nebuleuse d'Orion", "Titan", "Etoile a neutrons", "Voyager 1"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0045 }
            Reponses := array{"Etoile a neutrons", "Titan", "Nebuleuse d'Orion", "Sputnik 1"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0046 }
            Reponses := array{"Mir", "Naine blanche", "Nebuleuse d'Orion", "Soyouz"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0047 }
            Reponses := array{"Soyouz", "Grande Ourse", "Galaxie d'Andromede", "Ariane 5"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0048 }
            Reponses := array{"Mir", "Orion", "Ariane 5", "Grande Ourse"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0049 }
            Reponses := array{"Deimos", "Comete de Halley", "Perseverance", "Etoile a neutrons"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0050 }
            Reponses := array{"Orion", "Voyager 1", "Nebuleuse d'Orion", "Callisto"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0051 }
            Reponses := array{"Grande Ourse", "Supernova", "Deimos", "Naine blanche"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0052 }
            Reponses := array{"Ceres", "Phobos", "Anneaux de Saturne", "Supernova"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0053 }
            Reponses := array{"Ceinture de Kuiper", "Sagittarius A*", "Olympus Mons", "Grande tache rouge"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0054 }
            Reponses := array{"Valles Marineris", "Cratere Tycho", "Cassini", "Eris"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0055 }
            Reponses := array{"Grande tache rouge", "Vesta", "Objet de Hoag", "Ceinture d'asteroides"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0056 }
            Reponses := array{"Nuage d'Oort", "Comete Hale-Bopp", "Cratere Tycho", "Charon"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0057 }
            Reponses := array{"Comete Hale-Bopp", "Pulsar", "Sedna", "Eris"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0058 }
            Reponses := array{"Makemake", "Comete Hale-Bopp", "Sirius", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0059 }
            Reponses := array{"Haumea", "Rosetta", "Disque d'or de Voyager", "Nebuleuse de la Tete de cheval"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0060 }
            Reponses := array{"Quasar", "Comete NEOWISE", "Sedna", "New Horizons"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0061 }
            Reponses := array{"Charon", "Proxima du Centaure", "Galaxie du Tourbillon", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0062 }
            Reponses := array{"Eris", "Nebuleuse de la Tete de cheval", "Betelgeuse", "Piliers de la creation"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0063 }
            Reponses := array{"Sagittarius A*", "Cratere Tycho", "Sirius", "Galaxie du Sombrero"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0064 }
            Reponses := array{"Etoile polaire", "Sagittarius A*", "Vesta", "Cassini"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0065 }
            Reponses := array{"Galaxie du Sombrero", "Sirius", "Pulsar", "Objet de Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0066 }
            Reponses := array{"Vesta", "Quasar", "Nebuleuse du Crabe", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0067 }
            Reponses := array{"Valles Marineris", "Objet de Hoag", "Trou de ver", "Charon"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0068 }
            Reponses := array{"Nebuleuse de l'Aigle", "Haumea", "Charon", "Ceinture d'asteroides"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0069 }
            Reponses := array{"Grande tache rouge", "Ceinture de Kuiper", "Sagittarius A*", "Nebuleuse de la Tete de cheval"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0070 }
            Reponses := array{"Nuage d'Oort", "Comete Hale-Bopp", "Cratere Tycho", "New Horizons"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0071 }
            Reponses := array{"Nebuleuse du Crabe", "Ceinture de Kuiper", "Valles Marineris", "Haumea"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0072 }
            Reponses := array{"New Horizons", "Nuage d'Oort", "Cratere Tycho", "Piliers de la creation"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0073 }
            Reponses := array{"Sagittarius A*", "Nebuleuse de la Tete de cheval", "Bennu", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0074 }
            Reponses := array{"Sagittarius A*", "Proxima du Centaure", "Makemake", "Rosetta"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0075 }
            Reponses := array{"Eris", "Ceinture d'asteroides", "Bennu", "Cassini"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0076 }
            Reponses := array{"Cassini", "Ryugu", "New Horizons", "Nebuleuse de la Tete de cheval"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0077 }
            Reponses := array{"Rosetta", "Disque d'or de Voyager", "Grande tache rouge", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0078 }
            Reponses := array{"Objet de Hoag", "Eris", "Rosetta", "Etoile polaire"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0079 }
            Reponses := array{"Eris", "Comete NEOWISE", "Cratere Tycho", "Quasar"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0080 }
            Reponses := array{"Comete Hale-Bopp", "Ceinture de Kuiper", "Vesta", "Objet de Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0081 }
            Reponses := array{"Grande tache rouge", "Haumea", "Proxima du Centaure", "Bennu"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0082 }
            Reponses := array{"Sagittarius A*", "Cassini", "Trou de ver", "Ryugu"}
            BonneReponse := 3
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0083 }
            Reponses := array{"Cassini", "Pulsar", "Comete Hale-Bopp", "Ceinture de Kuiper"}
            BonneReponse := 2
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0084 }
            Reponses := array{"Comete NEOWISE", "Bennu", "Charon", "Sedna"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0085 }
            Reponses := array{"Betelgeuse", "Galaxie du Tourbillon", "Disque d'or de Voyager", "Nebuleuse du Crabe"}
            BonneReponse := 1
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0086 }
            Reponses := array{"Galaxie du Sombrero", "Etoile polaire", "Cratere Tycho", "Nebuleuse de la Tete de cheval"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0087 }
            Reponses := array{"Nebuleuse de l'Aigle", "Etoile polaire", "Comete Hale-Bopp", "Charon"}
            BonneReponse := 0
        question:
            Enonce := "Qu'est-ce que c'est ?"
            Image := option{ espace.spc_0088 }
            Reponses := array{"Olympus Mons", "New Horizons", "Cratere Tycho", "Nebuleuse de la Tete de cheval"}
            BonneReponse := 3

MakeEspaceQuestionsEN() : []question =
    array:
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0001 }
            Reponses := array{"Big Bang", "Neptune", "Sun", "Uranus"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0002 }
            Reponses := array{"Mercury", "Big Bang", "Earth", "Neptune"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0003 }
            Reponses := array{"Venus", "Moon", "Earth", "Milky Way"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0004 }
            Reponses := array{"Apollo 11", "Earth", "Black hole", "Hubble"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0005 }
            Reponses := array{"Venus", "Moon", "Hubble", "Pluto"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0006 }
            Reponses := array{"Mars", "Pluto", "Jupiter", "Black hole"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0007 }
            Reponses := array{"Sun", "Jupiter", "Comet", "Curiosity"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0008 }
            Reponses := array{"ISS", "Asteroid", "Mars", "Saturn"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0009 }
            Reponses := array{"Big Bang", "Uranus", "Apollo 11", "Black hole"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0010 }
            Reponses := array{"Neptune", "Jupiter", "Curiosity", "Black hole"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0011 }
            Reponses := array{"Solar eclipse", "Space Shuttle", "Pluto", "Starship"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0012 }
            Reponses := array{"Asteroid", "Neptune", "Apollo 11", "Milky Way"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0013 }
            Reponses := array{"Earth", "Black hole", "Falcon 9", "Sun"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0014 }
            Reponses := array{"Mercury", "Asteroid", "Moon", "Comet"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0015 }
            Reponses := array{"Neptune", "Curiosity", "Asteroid", "Space Shuttle"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0016 }
            Reponses := array{"Venus", "ISS", "Starship", "Saturn"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0017 }
            Reponses := array{"Hubble", "Sun", "Saturn V", "Mars"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0018 }
            Reponses := array{"Apollo 11", "Milky Way", "Venus", "Curiosity"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0019 }
            Reponses := array{"Neptune", "Moon", "Starship", "Saturn V"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0020 }
            Reponses := array{"Space Shuttle", "Hubble", "Big Bang", "Aurora"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0021 }
            Reponses := array{"Moon", "Falcon 9", "Aurora", "Apollo 11"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0022 }
            Reponses := array{"Black hole", "Moon", "Uranus", "Curiosity"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0023 }
            Reponses := array{"Mars", "Neptune", "Solar eclipse", "Sun"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0024 }
            Reponses := array{"Aurora", "Black hole", "Space Shuttle", "Solar eclipse"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0025 }
            Reponses := array{"Aurora", "Black hole", "Uranus", "Big Bang"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0026 }
            Reponses := array{"Solar eclipse", "Falcon 9", "Starship", "Apollo 11"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0027 }
            Reponses := array{"Io", "Perseverance", "Ceres", "James Webb"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0028 }
            Reponses := array{"Orion", "Callisto", "Halley's Comet", "Europa"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0029 }
            Reponses := array{"Supernova", "Europa", "James Webb", "Ganymede"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0030 }
            Reponses := array{"White dwarf", "Neutron star", "Callisto", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0031 }
            Reponses := array{"Titan", "Rings of Saturn", "Triton", "Deimos"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0032 }
            Reponses := array{"Enceladus", "Ariane 5", "Neutron star", "Halley's Comet"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0033 }
            Reponses := array{"Callisto", "Orion Nebula", "Triton", "Ariane 5"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0034 }
            Reponses := array{"Perseverance", "Callisto", "Phobos", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0035 }
            Reponses := array{"Io", "Orion", "Deimos", "Ganymede"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0036 }
            Reponses := array{"Ariane 5", "Voyager 1", "James Webb", "Ceres"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0037 }
            Reponses := array{"White dwarf", "Halley's Comet", "Big Dipper", "Phobos"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0038 }
            Reponses := array{"Mir", "Ceres", "Andromeda Galaxy", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0039 }
            Reponses := array{"Soyuz", "Europa", "Callisto", "Orion Nebula"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0040 }
            Reponses := array{"Io", "Europa", "Supernova", "Orion Nebula"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0041 }
            Reponses := array{"Titan", "Voyager 1", "White dwarf", "Enceladus"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0042 }
            Reponses := array{"Neutron star", "Io", "Phobos", "Halley's Comet"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0043 }
            Reponses := array{"Deimos", "Ariane 5", "James Webb", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0044 }
            Reponses := array{"Orion Nebula", "Titan", "Neutron star", "Voyager 1"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0045 }
            Reponses := array{"Neutron star", "Titan", "Orion Nebula", "Sputnik 1"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0046 }
            Reponses := array{"Mir", "White dwarf", "Orion Nebula", "Soyuz"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0047 }
            Reponses := array{"Soyuz", "Big Dipper", "Andromeda Galaxy", "Ariane 5"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0048 }
            Reponses := array{"Mir", "Orion", "Ariane 5", "Big Dipper"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0049 }
            Reponses := array{"Deimos", "Halley's Comet", "Perseverance", "Neutron star"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0050 }
            Reponses := array{"Orion", "Voyager 1", "Orion Nebula", "Callisto"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0051 }
            Reponses := array{"Big Dipper", "Supernova", "Deimos", "White dwarf"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0052 }
            Reponses := array{"Ceres", "Phobos", "Rings of Saturn", "Supernova"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0053 }
            Reponses := array{"Kuiper belt", "Sagittarius A*", "Olympus Mons", "Great Red Spot"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0054 }
            Reponses := array{"Valles Marineris", "Tycho crater", "Cassini", "Eris"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0055 }
            Reponses := array{"Great Red Spot", "Vesta", "Hoag's Object", "Asteroid belt"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0056 }
            Reponses := array{"Oort cloud", "Hale-Bopp", "Tycho crater", "Charon"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0057 }
            Reponses := array{"Hale-Bopp", "Pulsar", "Sedna", "Eris"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0058 }
            Reponses := array{"Makemake", "Hale-Bopp", "Sirius", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0059 }
            Reponses := array{"Haumea", "Rosetta", "Voyager Golden Record", "Horsehead Nebula"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0060 }
            Reponses := array{"Quasar", "NEOWISE", "Sedna", "New Horizons"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0061 }
            Reponses := array{"Charon", "Proxima Centauri", "Whirlpool Galaxy", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0062 }
            Reponses := array{"Eris", "Horsehead Nebula", "Betelgeuse", "Pillars of Creation"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0063 }
            Reponses := array{"Sagittarius A*", "Tycho crater", "Sirius", "Sombrero Galaxy"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0064 }
            Reponses := array{"Polaris", "Sagittarius A*", "Vesta", "Cassini"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0065 }
            Reponses := array{"Sombrero Galaxy", "Sirius", "Pulsar", "Hoag's Object"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0066 }
            Reponses := array{"Vesta", "Quasar", "Crab Nebula", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0067 }
            Reponses := array{"Valles Marineris", "Hoag's Object", "Wormhole", "Charon"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0068 }
            Reponses := array{"Eagle Nebula", "Haumea", "Charon", "Asteroid belt"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0069 }
            Reponses := array{"Great Red Spot", "Kuiper belt", "Sagittarius A*", "Horsehead Nebula"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0070 }
            Reponses := array{"Oort cloud", "Hale-Bopp", "Tycho crater", "New Horizons"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0071 }
            Reponses := array{"Crab Nebula", "Kuiper belt", "Valles Marineris", "Haumea"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0072 }
            Reponses := array{"New Horizons", "Oort cloud", "Tycho crater", "Pillars of Creation"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0073 }
            Reponses := array{"Sagittarius A*", "Horsehead Nebula", "Bennu", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0074 }
            Reponses := array{"Sagittarius A*", "Proxima Centauri", "Makemake", "Rosetta"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0075 }
            Reponses := array{"Eris", "Asteroid belt", "Bennu", "Cassini"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0076 }
            Reponses := array{"Cassini", "Ryugu", "New Horizons", "Horsehead Nebula"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0077 }
            Reponses := array{"Rosetta", "Voyager Golden Record", "Great Red Spot", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0078 }
            Reponses := array{"Hoag's Object", "Eris", "Rosetta", "Polaris"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0079 }
            Reponses := array{"Eris", "NEOWISE", "Tycho crater", "Quasar"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0080 }
            Reponses := array{"Hale-Bopp", "Kuiper belt", "Vesta", "Hoag's Object"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0081 }
            Reponses := array{"Great Red Spot", "Haumea", "Proxima Centauri", "Bennu"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0082 }
            Reponses := array{"Sagittarius A*", "Cassini", "Wormhole", "Ryugu"}
            BonneReponse := 3
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0083 }
            Reponses := array{"Cassini", "Pulsar", "Hale-Bopp", "Kuiper belt"}
            BonneReponse := 2
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0084 }
            Reponses := array{"NEOWISE", "Bennu", "Charon", "Sedna"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0085 }
            Reponses := array{"Betelgeuse", "Whirlpool Galaxy", "Voyager Golden Record", "Crab Nebula"}
            BonneReponse := 1
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0086 }
            Reponses := array{"Sombrero Galaxy", "Polaris", "Tycho crater", "Horsehead Nebula"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0087 }
            Reponses := array{"Eagle Nebula", "Polaris", "Hale-Bopp", "Charon"}
            BonneReponse := 0
        question:
            Enonce := "What is this?"
            Image := option{ espace.spc_0088 }
            Reponses := array{"Olympus Mons", "New Horizons", "Tycho crater", "Horsehead Nebula"}
            BonneReponse := 3

MakeEspaceQuestionsES() : []question =
    array:
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0001 }
            Reponses := array{"Big Bang", "Neptuno", "Sol", "Urano"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0002 }
            Reponses := array{"Mercurio", "Big Bang", "Tierra", "Neptuno"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0003 }
            Reponses := array{"Venus", "Luna", "Tierra", "Via Lactea"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0004 }
            Reponses := array{"Apollo 11", "Tierra", "Agujero negro", "Hubble"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0005 }
            Reponses := array{"Venus", "Luna", "Hubble", "Pluton"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0006 }
            Reponses := array{"Marte", "Pluton", "Jupiter", "Agujero negro"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0007 }
            Reponses := array{"Sol", "Jupiter", "Cometa", "Curiosity"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0008 }
            Reponses := array{"ISS", "Asteroide", "Marte", "Saturno"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0009 }
            Reponses := array{"Big Bang", "Urano", "Apollo 11", "Agujero negro"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0010 }
            Reponses := array{"Neptuno", "Jupiter", "Curiosity", "Agujero negro"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0011 }
            Reponses := array{"Eclipse solar", "Transbordador espacial", "Pluton", "Starship"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0012 }
            Reponses := array{"Asteroide", "Neptuno", "Apollo 11", "Via Lactea"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0013 }
            Reponses := array{"Tierra", "Agujero negro", "Falcon 9", "Sol"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0014 }
            Reponses := array{"Mercurio", "Asteroide", "Luna", "Cometa"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0015 }
            Reponses := array{"Neptuno", "Curiosity", "Asteroide", "Transbordador espacial"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0016 }
            Reponses := array{"Venus", "ISS", "Starship", "Saturno"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0017 }
            Reponses := array{"Hubble", "Sol", "Saturn V", "Marte"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0018 }
            Reponses := array{"Apollo 11", "Via Lactea", "Venus", "Curiosity"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0019 }
            Reponses := array{"Neptuno", "Luna", "Starship", "Saturn V"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0020 }
            Reponses := array{"Transbordador espacial", "Hubble", "Big Bang", "Aurora boreal"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0021 }
            Reponses := array{"Luna", "Falcon 9", "Aurora boreal", "Apollo 11"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0022 }
            Reponses := array{"Agujero negro", "Luna", "Urano", "Curiosity"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0023 }
            Reponses := array{"Marte", "Neptuno", "Eclipse solar", "Sol"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0024 }
            Reponses := array{"Aurora boreal", "Agujero negro", "Transbordador espacial", "Eclipse solar"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0025 }
            Reponses := array{"Aurora boreal", "Agujero negro", "Urano", "Big Bang"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0026 }
            Reponses := array{"Eclipse solar", "Falcon 9", "Starship", "Apollo 11"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0027 }
            Reponses := array{"Io", "Perseverance", "Ceres", "James Webb"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0028 }
            Reponses := array{"Orion", "Callisto", "Cometa Halley", "Europa"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0029 }
            Reponses := array{"Supernova", "Europa", "James Webb", "Ganimedes"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0030 }
            Reponses := array{"Enana blanca", "Estrella de neutrones", "Callisto", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0031 }
            Reponses := array{"Titan", "Anillos de Saturno", "Triton", "Deimos"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0032 }
            Reponses := array{"Encelado", "Ariane 5", "Estrella de neutrones", "Cometa Halley"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0033 }
            Reponses := array{"Callisto", "Nebulosa de Orion", "Triton", "Ariane 5"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0034 }
            Reponses := array{"Perseverance", "Callisto", "Phobos", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0035 }
            Reponses := array{"Io", "Orion", "Deimos", "Ganimedes"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0036 }
            Reponses := array{"Ariane 5", "Voyager 1", "James Webb", "Ceres"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0037 }
            Reponses := array{"Enana blanca", "Cometa Halley", "Osa Mayor", "Phobos"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0038 }
            Reponses := array{"Mir", "Ceres", "Galaxia de Andromeda", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0039 }
            Reponses := array{"Soyuz", "Europa", "Callisto", "Nebulosa de Orion"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0040 }
            Reponses := array{"Io", "Europa", "Supernova", "Nebulosa de Orion"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0041 }
            Reponses := array{"Titan", "Voyager 1", "Enana blanca", "Encelado"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0042 }
            Reponses := array{"Estrella de neutrones", "Io", "Phobos", "Cometa Halley"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0043 }
            Reponses := array{"Deimos", "Ariane 5", "James Webb", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0044 }
            Reponses := array{"Nebulosa de Orion", "Titan", "Estrella de neutrones", "Voyager 1"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0045 }
            Reponses := array{"Estrella de neutrones", "Titan", "Nebulosa de Orion", "Sputnik 1"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0046 }
            Reponses := array{"Mir", "Enana blanca", "Nebulosa de Orion", "Soyuz"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0047 }
            Reponses := array{"Soyuz", "Osa Mayor", "Galaxia de Andromeda", "Ariane 5"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0048 }
            Reponses := array{"Mir", "Orion", "Ariane 5", "Osa Mayor"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0049 }
            Reponses := array{"Deimos", "Cometa Halley", "Perseverance", "Estrella de neutrones"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0050 }
            Reponses := array{"Orion", "Voyager 1", "Nebulosa de Orion", "Callisto"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0051 }
            Reponses := array{"Osa Mayor", "Supernova", "Deimos", "Enana blanca"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0052 }
            Reponses := array{"Ceres", "Phobos", "Anillos de Saturno", "Supernova"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0053 }
            Reponses := array{"Cinturon de Kuiper", "Sagittarius A*", "Olympus Mons", "Gran Mancha Roja"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0054 }
            Reponses := array{"Valles Marineris", "Crater Tycho", "Cassini", "Eris"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0055 }
            Reponses := array{"Gran Mancha Roja", "Vesta", "Objeto de Hoag", "Cinturon de asteroides"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0056 }
            Reponses := array{"Nube de Oort", "Hale-Bopp", "Crater Tycho", "Caronte"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0057 }
            Reponses := array{"Hale-Bopp", "Pulsar", "Sedna", "Eris"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0058 }
            Reponses := array{"Makemake", "Hale-Bopp", "Sirio", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0059 }
            Reponses := array{"Haumea", "Rosetta", "Disco de oro de las Voyager", "Nebulosa Cabeza de Caballo"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0060 }
            Reponses := array{"Quasar", "NEOWISE", "Sedna", "New Horizons"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0061 }
            Reponses := array{"Caronte", "Proxima Centauri", "Galaxia del Remolino", "Sirio"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0062 }
            Reponses := array{"Eris", "Nebulosa Cabeza de Caballo", "Betelgeuse", "Pilares de la Creacion"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0063 }
            Reponses := array{"Sagittarius A*", "Crater Tycho", "Sirio", "Galaxia del Sombrero"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0064 }
            Reponses := array{"Estrella Polar", "Sagittarius A*", "Vesta", "Cassini"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0065 }
            Reponses := array{"Galaxia del Sombrero", "Sirio", "Pulsar", "Objeto de Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0066 }
            Reponses := array{"Vesta", "Quasar", "Nebulosa del Cangrejo", "Sirio"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0067 }
            Reponses := array{"Valles Marineris", "Objeto de Hoag", "Agujero de gusano", "Caronte"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0068 }
            Reponses := array{"Nebulosa del Aguila", "Haumea", "Caronte", "Cinturon de asteroides"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0069 }
            Reponses := array{"Gran Mancha Roja", "Cinturon de Kuiper", "Sagittarius A*", "Nebulosa Cabeza de Caballo"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0070 }
            Reponses := array{"Nube de Oort", "Hale-Bopp", "Crater Tycho", "New Horizons"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0071 }
            Reponses := array{"Nebulosa del Cangrejo", "Cinturon de Kuiper", "Valles Marineris", "Haumea"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0072 }
            Reponses := array{"New Horizons", "Nube de Oort", "Crater Tycho", "Pilares de la Creacion"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0073 }
            Reponses := array{"Sagittarius A*", "Nebulosa Cabeza de Caballo", "Bennu", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0074 }
            Reponses := array{"Sagittarius A*", "Proxima Centauri", "Makemake", "Rosetta"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0075 }
            Reponses := array{"Eris", "Cinturon de asteroides", "Bennu", "Cassini"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0076 }
            Reponses := array{"Cassini", "Ryugu", "New Horizons", "Nebulosa Cabeza de Caballo"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0077 }
            Reponses := array{"Rosetta", "Disco de oro de las Voyager", "Gran Mancha Roja", "Caronte"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0078 }
            Reponses := array{"Objeto de Hoag", "Eris", "Rosetta", "Estrella Polar"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0079 }
            Reponses := array{"Eris", "NEOWISE", "Crater Tycho", "Quasar"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0080 }
            Reponses := array{"Hale-Bopp", "Cinturon de Kuiper", "Vesta", "Objeto de Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0081 }
            Reponses := array{"Gran Mancha Roja", "Haumea", "Proxima Centauri", "Bennu"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0082 }
            Reponses := array{"Sagittarius A*", "Cassini", "Agujero de gusano", "Ryugu"}
            BonneReponse := 3
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0083 }
            Reponses := array{"Cassini", "Pulsar", "Hale-Bopp", "Cinturon de Kuiper"}
            BonneReponse := 2
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0084 }
            Reponses := array{"NEOWISE", "Bennu", "Caronte", "Sedna"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0085 }
            Reponses := array{"Betelgeuse", "Galaxia del Remolino", "Disco de oro de las Voyager", "Nebulosa del Cangrejo"}
            BonneReponse := 1
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0086 }
            Reponses := array{"Galaxia del Sombrero", "Estrella Polar", "Crater Tycho", "Nebulosa Cabeza de Caballo"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0087 }
            Reponses := array{"Nebulosa del Aguila", "Estrella Polar", "Hale-Bopp", "Caronte"}
            BonneReponse := 0
        question:
            Enonce := "Que es esto?"
            Image := option{ espace.spc_0088 }
            Reponses := array{"Olympus Mons", "New Horizons", "Crater Tycho", "Nebulosa Cabeza de Caballo"}
            BonneReponse := 3

MakeEspaceQuestionsDE() : []question =
    array:
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0001 }
            Reponses := array{"Big Bang", "Neptun", "Sonne", "Uranus"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0002 }
            Reponses := array{"Merkur", "Big Bang", "Erde", "Neptun"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0003 }
            Reponses := array{"Venus", "Mond", "Erde", "Milchstrasse"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0004 }
            Reponses := array{"Apollo 11", "Erde", "Schwarzes Loch", "Hubble"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0005 }
            Reponses := array{"Venus", "Mond", "Hubble", "Pluto"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0006 }
            Reponses := array{"Mars", "Pluto", "Jupiter", "Schwarzes Loch"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0007 }
            Reponses := array{"Sonne", "Jupiter", "Komet", "Curiosity"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0008 }
            Reponses := array{"ISS", "Asteroid", "Mars", "Saturn"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0009 }
            Reponses := array{"Big Bang", "Uranus", "Apollo 11", "Schwarzes Loch"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0010 }
            Reponses := array{"Neptun", "Jupiter", "Curiosity", "Schwarzes Loch"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0011 }
            Reponses := array{"Sonnenfinsternis", "Space Shuttle", "Pluto", "Starship"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0012 }
            Reponses := array{"Asteroid", "Neptun", "Apollo 11", "Milchstrasse"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0013 }
            Reponses := array{"Erde", "Schwarzes Loch", "Falcon 9", "Sonne"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0014 }
            Reponses := array{"Merkur", "Asteroid", "Mond", "Komet"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0015 }
            Reponses := array{"Neptun", "Curiosity", "Asteroid", "Space Shuttle"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0016 }
            Reponses := array{"Venus", "ISS", "Starship", "Saturn"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0017 }
            Reponses := array{"Hubble", "Sonne", "Saturn V", "Mars"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0018 }
            Reponses := array{"Apollo 11", "Milchstrasse", "Venus", "Curiosity"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0019 }
            Reponses := array{"Neptun", "Mond", "Starship", "Saturn V"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0020 }
            Reponses := array{"Space Shuttle", "Hubble", "Big Bang", "Polarlicht"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0021 }
            Reponses := array{"Mond", "Falcon 9", "Polarlicht", "Apollo 11"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0022 }
            Reponses := array{"Schwarzes Loch", "Mond", "Uranus", "Curiosity"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0023 }
            Reponses := array{"Mars", "Neptun", "Sonnenfinsternis", "Sonne"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0024 }
            Reponses := array{"Polarlicht", "Schwarzes Loch", "Space Shuttle", "Sonnenfinsternis"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0025 }
            Reponses := array{"Polarlicht", "Schwarzes Loch", "Uranus", "Big Bang"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0026 }
            Reponses := array{"Sonnenfinsternis", "Falcon 9", "Starship", "Apollo 11"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0027 }
            Reponses := array{"Io", "Perseverance", "Ceres", "James Webb"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0028 }
            Reponses := array{"Orion", "Callisto", "Halleyscher Komet", "Europa"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0029 }
            Reponses := array{"Supernova", "Europa", "James Webb", "Ganymed"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0030 }
            Reponses := array{"Weisser Zwerg", "Neutronenstern", "Callisto", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0031 }
            Reponses := array{"Titan", "Saturnringe", "Triton", "Deimos"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0032 }
            Reponses := array{"Enceladus", "Ariane 5", "Neutronenstern", "Halleyscher Komet"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0033 }
            Reponses := array{"Callisto", "Orionnebel", "Triton", "Ariane 5"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0034 }
            Reponses := array{"Perseverance", "Callisto", "Phobos", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0035 }
            Reponses := array{"Io", "Orion", "Deimos", "Ganymed"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0036 }
            Reponses := array{"Ariane 5", "Voyager 1", "James Webb", "Ceres"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0037 }
            Reponses := array{"Weisser Zwerg", "Halleyscher Komet", "Grosser Wagen", "Phobos"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0038 }
            Reponses := array{"Mir", "Ceres", "Andromedagalaxie", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0039 }
            Reponses := array{"Sojus", "Europa", "Callisto", "Orionnebel"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0040 }
            Reponses := array{"Io", "Europa", "Supernova", "Orionnebel"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0041 }
            Reponses := array{"Titan", "Voyager 1", "Weisser Zwerg", "Enceladus"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0042 }
            Reponses := array{"Neutronenstern", "Io", "Phobos", "Halleyscher Komet"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0043 }
            Reponses := array{"Deimos", "Ariane 5", "James Webb", "Orion"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0044 }
            Reponses := array{"Orionnebel", "Titan", "Neutronenstern", "Voyager 1"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0045 }
            Reponses := array{"Neutronenstern", "Titan", "Orionnebel", "Sputnik 1"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0046 }
            Reponses := array{"Mir", "Weisser Zwerg", "Orionnebel", "Sojus"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0047 }
            Reponses := array{"Sojus", "Grosser Wagen", "Andromedagalaxie", "Ariane 5"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0048 }
            Reponses := array{"Mir", "Orion", "Ariane 5", "Grosser Wagen"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0049 }
            Reponses := array{"Deimos", "Halleyscher Komet", "Perseverance", "Neutronenstern"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0050 }
            Reponses := array{"Orion", "Voyager 1", "Orionnebel", "Callisto"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0051 }
            Reponses := array{"Grosser Wagen", "Supernova", "Deimos", "Weisser Zwerg"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0052 }
            Reponses := array{"Ceres", "Phobos", "Saturnringe", "Supernova"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0053 }
            Reponses := array{"Kuiperguertel", "Sagittarius A*", "Olympus Mons", "Grosser Roter Fleck"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0054 }
            Reponses := array{"Valles Marineris", "Tycho-Krater", "Cassini", "Eris"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0055 }
            Reponses := array{"Grosser Roter Fleck", "Vesta", "Hoags Objekt", "Asteroidenguertel"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0056 }
            Reponses := array{"Oortsche Wolke", "Hale-Bopp", "Tycho-Krater", "Charon"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0057 }
            Reponses := array{"Hale-Bopp", "Pulsar", "Sedna", "Eris"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0058 }
            Reponses := array{"Makemake", "Hale-Bopp", "Sirius", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0059 }
            Reponses := array{"Haumea", "Rosetta", "Voyager Golden Record", "Pferdekopfnebel"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0060 }
            Reponses := array{"Quasar", "NEOWISE", "Sedna", "New Horizons"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0061 }
            Reponses := array{"Charon", "Proxima Centauri", "Strudelgalaxie", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0062 }
            Reponses := array{"Eris", "Pferdekopfnebel", "Betelgeuse", "Saeulen der Schoepfung"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0063 }
            Reponses := array{"Sagittarius A*", "Tycho-Krater", "Sirius", "Sombrerogalaxie"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0064 }
            Reponses := array{"Polarstern", "Sagittarius A*", "Vesta", "Cassini"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0065 }
            Reponses := array{"Sombrerogalaxie", "Sirius", "Pulsar", "Hoags Objekt"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0066 }
            Reponses := array{"Vesta", "Quasar", "Krebsnebel", "Sirius"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0067 }
            Reponses := array{"Valles Marineris", "Hoags Objekt", "Wurmloch", "Charon"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0068 }
            Reponses := array{"Adlernebel", "Haumea", "Charon", "Asteroidenguertel"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0069 }
            Reponses := array{"Grosser Roter Fleck", "Kuiperguertel", "Sagittarius A*", "Pferdekopfnebel"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0070 }
            Reponses := array{"Oortsche Wolke", "Hale-Bopp", "Tycho-Krater", "New Horizons"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0071 }
            Reponses := array{"Krebsnebel", "Kuiperguertel", "Valles Marineris", "Haumea"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0072 }
            Reponses := array{"New Horizons", "Oortsche Wolke", "Tycho-Krater", "Saeulen der Schoepfung"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0073 }
            Reponses := array{"Sagittarius A*", "Pferdekopfnebel", "Bennu", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0074 }
            Reponses := array{"Sagittarius A*", "Proxima Centauri", "Makemake", "Rosetta"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0075 }
            Reponses := array{"Eris", "Asteroidenguertel", "Bennu", "Cassini"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0076 }
            Reponses := array{"Cassini", "Ryugu", "New Horizons", "Pferdekopfnebel"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0077 }
            Reponses := array{"Rosetta", "Voyager Golden Record", "Grosser Roter Fleck", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0078 }
            Reponses := array{"Hoags Objekt", "Eris", "Rosetta", "Polarstern"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0079 }
            Reponses := array{"Eris", "NEOWISE", "Tycho-Krater", "Quasar"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0080 }
            Reponses := array{"Hale-Bopp", "Kuiperguertel", "Vesta", "Hoags Objekt"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0081 }
            Reponses := array{"Grosser Roter Fleck", "Haumea", "Proxima Centauri", "Bennu"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0082 }
            Reponses := array{"Sagittarius A*", "Cassini", "Wurmloch", "Ryugu"}
            BonneReponse := 3
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0083 }
            Reponses := array{"Cassini", "Pulsar", "Hale-Bopp", "Kuiperguertel"}
            BonneReponse := 2
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0084 }
            Reponses := array{"NEOWISE", "Bennu", "Charon", "Sedna"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0085 }
            Reponses := array{"Betelgeuse", "Strudelgalaxie", "Voyager Golden Record", "Krebsnebel"}
            BonneReponse := 1
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0086 }
            Reponses := array{"Sombrerogalaxie", "Polarstern", "Tycho-Krater", "Pferdekopfnebel"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0087 }
            Reponses := array{"Adlernebel", "Polarstern", "Hale-Bopp", "Charon"}
            BonneReponse := 0
        question:
            Enonce := "Was ist das?"
            Image := option{ espace.spc_0088 }
            Reponses := array{"Olympus Mons", "New Horizons", "Tycho-Krater", "Pferdekopfnebel"}
            BonneReponse := 3

MakeEspaceQuestionsIT() : []question =
    array:
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0001 }
            Reponses := array{"Big Bang", "Nettuno", "Sole", "Urano"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0002 }
            Reponses := array{"Mercurio", "Big Bang", "Terra", "Nettuno"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0003 }
            Reponses := array{"Venus", "Luna", "Terra", "Via Lattea"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0004 }
            Reponses := array{"Apollo 11", "Terra", "Buco nero", "Hubble"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0005 }
            Reponses := array{"Venus", "Luna", "Hubble", "Plutone"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0006 }
            Reponses := array{"Marte", "Plutone", "Giove", "Buco nero"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0007 }
            Reponses := array{"Sole", "Giove", "Cometa", "Curiosity"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0008 }
            Reponses := array{"ISS", "Asteroide", "Marte", "Saturno"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0009 }
            Reponses := array{"Big Bang", "Urano", "Apollo 11", "Buco nero"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0010 }
            Reponses := array{"Nettuno", "Giove", "Curiosity", "Buco nero"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0011 }
            Reponses := array{"Eclissi solare", "Space Shuttle", "Plutone", "Starship"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0012 }
            Reponses := array{"Asteroide", "Nettuno", "Apollo 11", "Via Lattea"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0013 }
            Reponses := array{"Terra", "Buco nero", "Falcon 9", "Sole"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0014 }
            Reponses := array{"Mercurio", "Asteroide", "Luna", "Cometa"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0015 }
            Reponses := array{"Nettuno", "Curiosity", "Asteroide", "Space Shuttle"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0016 }
            Reponses := array{"Venus", "ISS", "Starship", "Saturno"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0017 }
            Reponses := array{"Hubble", "Sole", "Saturn V", "Marte"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0018 }
            Reponses := array{"Apollo 11", "Via Lattea", "Venus", "Curiosity"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0019 }
            Reponses := array{"Nettuno", "Luna", "Starship", "Saturn V"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0020 }
            Reponses := array{"Space Shuttle", "Hubble", "Big Bang", "Aurora boreale"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0021 }
            Reponses := array{"Luna", "Falcon 9", "Aurora boreale", "Apollo 11"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0022 }
            Reponses := array{"Buco nero", "Luna", "Urano", "Curiosity"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0023 }
            Reponses := array{"Marte", "Nettuno", "Eclissi solare", "Sole"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0024 }
            Reponses := array{"Aurora boreale", "Buco nero", "Space Shuttle", "Eclissi solare"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0025 }
            Reponses := array{"Aurora boreale", "Buco nero", "Urano", "Big Bang"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0026 }
            Reponses := array{"Eclissi solare", "Falcon 9", "Starship", "Apollo 11"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0027 }
            Reponses := array{"Io", "Perseverance", "Cerere", "James Webb"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0028 }
            Reponses := array{"Orione", "Callisto", "Cometa di Halley", "Europa"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0029 }
            Reponses := array{"Supernova", "Europa", "James Webb", "Ganimede"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0030 }
            Reponses := array{"Nana bianca", "Stella di neutroni", "Callisto", "Orione"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0031 }
            Reponses := array{"Titano", "Anelli di Saturno", "Tritone", "Deimos"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0032 }
            Reponses := array{"Encelado", "Ariane 5", "Stella di neutroni", "Cometa di Halley"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0033 }
            Reponses := array{"Callisto", "Nebulosa di Orione", "Tritone", "Ariane 5"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0034 }
            Reponses := array{"Perseverance", "Callisto", "Phobos", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0035 }
            Reponses := array{"Io", "Orione", "Deimos", "Ganimede"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0036 }
            Reponses := array{"Ariane 5", "Voyager 1", "James Webb", "Cerere"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0037 }
            Reponses := array{"Nana bianca", "Cometa di Halley", "Grande Carro", "Phobos"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0038 }
            Reponses := array{"Mir", "Cerere", "Galassia di Andromeda", "Deimos"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0039 }
            Reponses := array{"Soyuz", "Europa", "Callisto", "Nebulosa di Orione"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0040 }
            Reponses := array{"Io", "Europa", "Supernova", "Nebulosa di Orione"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0041 }
            Reponses := array{"Titano", "Voyager 1", "Nana bianca", "Encelado"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0042 }
            Reponses := array{"Stella di neutroni", "Io", "Phobos", "Cometa di Halley"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0043 }
            Reponses := array{"Deimos", "Ariane 5", "James Webb", "Orione"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0044 }
            Reponses := array{"Nebulosa di Orione", "Titano", "Stella di neutroni", "Voyager 1"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0045 }
            Reponses := array{"Stella di neutroni", "Titano", "Nebulosa di Orione", "Sputnik 1"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0046 }
            Reponses := array{"Mir", "Nana bianca", "Nebulosa di Orione", "Soyuz"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0047 }
            Reponses := array{"Soyuz", "Grande Carro", "Galassia di Andromeda", "Ariane 5"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0048 }
            Reponses := array{"Mir", "Orione", "Ariane 5", "Grande Carro"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0049 }
            Reponses := array{"Deimos", "Cometa di Halley", "Perseverance", "Stella di neutroni"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0050 }
            Reponses := array{"Orione", "Voyager 1", "Nebulosa di Orione", "Callisto"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0051 }
            Reponses := array{"Grande Carro", "Supernova", "Deimos", "Nana bianca"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0052 }
            Reponses := array{"Cerere", "Phobos", "Anelli di Saturno", "Supernova"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0053 }
            Reponses := array{"Fascia di Kuiper", "Sagittarius A*", "Olympus Mons", "Grande Macchia Rossa"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0054 }
            Reponses := array{"Valles Marineris", "Cratere Tycho", "Cassini", "Eris"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0055 }
            Reponses := array{"Grande Macchia Rossa", "Vesta", "Oggetto di Hoag", "Fascia degli asteroidi"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0056 }
            Reponses := array{"Nube di Oort", "Hale-Bopp", "Cratere Tycho", "Caronte"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0057 }
            Reponses := array{"Hale-Bopp", "Pulsar", "Sedna", "Eris"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0058 }
            Reponses := array{"Makemake", "Hale-Bopp", "Sirio", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0059 }
            Reponses := array{"Haumea", "Rosetta", "Voyager Golden Record", "Nebulosa Testa di Cavallo"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0060 }
            Reponses := array{"Quasar", "NEOWISE", "Sedna", "New Horizons"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0061 }
            Reponses := array{"Caronte", "Proxima Centauri", "Galassia Vortice", "Sirio"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0062 }
            Reponses := array{"Eris", "Nebulosa Testa di Cavallo", "Betelgeuse", "Pilastri della Creazione"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0063 }
            Reponses := array{"Sagittarius A*", "Cratere Tycho", "Sirio", "Galassia Sombrero"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0064 }
            Reponses := array{"Stella Polare", "Sagittarius A*", "Vesta", "Cassini"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0065 }
            Reponses := array{"Galassia Sombrero", "Sirio", "Pulsar", "Oggetto di Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0066 }
            Reponses := array{"Vesta", "Quasar", "Nebulosa del Granchio", "Sirio"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0067 }
            Reponses := array{"Valles Marineris", "Oggetto di Hoag", "Wormhole", "Caronte"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0068 }
            Reponses := array{"Nebulosa Aquila", "Haumea", "Caronte", "Fascia degli asteroidi"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0069 }
            Reponses := array{"Grande Macchia Rossa", "Fascia di Kuiper", "Sagittarius A*", "Nebulosa Testa di Cavallo"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0070 }
            Reponses := array{"Nube di Oort", "Hale-Bopp", "Cratere Tycho", "New Horizons"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0071 }
            Reponses := array{"Nebulosa del Granchio", "Fascia di Kuiper", "Valles Marineris", "Haumea"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0072 }
            Reponses := array{"New Horizons", "Nube di Oort", "Cratere Tycho", "Pilastri della Creazione"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0073 }
            Reponses := array{"Sagittarius A*", "Nebulosa Testa di Cavallo", "Bennu", "Olympus Mons"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0074 }
            Reponses := array{"Sagittarius A*", "Proxima Centauri", "Makemake", "Rosetta"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0075 }
            Reponses := array{"Eris", "Fascia degli asteroidi", "Bennu", "Cassini"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0076 }
            Reponses := array{"Cassini", "Ryugu", "New Horizons", "Nebulosa Testa di Cavallo"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0077 }
            Reponses := array{"Rosetta", "Voyager Golden Record", "Grande Macchia Rossa", "Caronte"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0078 }
            Reponses := array{"Oggetto di Hoag", "Eris", "Rosetta", "Stella Polare"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0079 }
            Reponses := array{"Eris", "NEOWISE", "Cratere Tycho", "Quasar"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0080 }
            Reponses := array{"Hale-Bopp", "Fascia di Kuiper", "Vesta", "Oggetto di Hoag"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0081 }
            Reponses := array{"Grande Macchia Rossa", "Haumea", "Proxima Centauri", "Bennu"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0082 }
            Reponses := array{"Sagittarius A*", "Cassini", "Wormhole", "Ryugu"}
            BonneReponse := 3
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0083 }
            Reponses := array{"Cassini", "Pulsar", "Hale-Bopp", "Fascia di Kuiper"}
            BonneReponse := 2
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0084 }
            Reponses := array{"NEOWISE", "Bennu", "Caronte", "Sedna"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0085 }
            Reponses := array{"Betelgeuse", "Galassia Vortice", "Voyager Golden Record", "Nebulosa del Granchio"}
            BonneReponse := 1
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0086 }
            Reponses := array{"Galassia Sombrero", "Stella Polare", "Cratere Tycho", "Nebulosa Testa di Cavallo"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0087 }
            Reponses := array{"Nebulosa Aquila", "Stella Polare", "Hale-Bopp", "Caronte"}
            BonneReponse := 0
        question:
            Enonce := "Che cos'e questo?"
            Image := option{ espace.spc_0088 }
            Reponses := array{"Olympus Mons", "New Horizons", "Cratere Tycho", "Nebulosa Testa di Cavallo"}
            BonneReponse := 3

MakeEspaceQuestions() : []question =
    MakeEspaceQuestionsFR()
