using { /Verse.org/Assets }

# jeuxvideo_bank.verse — Quizz JEUX VIDEO (jaquettes/logos Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

JeuxVideoDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1}

MakeJeuxVideoQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0001 }
            Reponses := array{"Cyberpunk 2077", "Tetris", "Skyrim", "GTA V"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0002 }
            Reponses := array{"Space Invaders", "Mortal Kombat", "World of Warcraft", "Zelda"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0003 }
            Reponses := array{"Super Mario", "Clash of Clans", "Clash Royale", "Assassin's Creed"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0004 }
            Reponses := array{"The Witcher 3", "League of Legends", "Candy Crush", "Tetris"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0005 }
            Reponses := array{"World of Warcraft", "Pac-Man", "Tomb Raider", "Candy Crush"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0006 }
            Reponses := array{"Temple Run", "Super Mario", "Space Invaders", "Sonic"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0007 }
            Reponses := array{"Skyrim", "The Witcher 3", "Red Dead Redemption 2", "FIFA"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0008 }
            Reponses := array{"Space Invaders", "League of Legends", "Flappy Bird", "Pac-Man"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0009 }
            Reponses := array{"League of Legends", "Overwatch", "Among Us", "Sonic"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0010 }
            Reponses := array{"League of Legends", "Brawl Stars", "Temple Run", "The Witcher 3"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0011 }
            Reponses := array{"Pokemon Go", "Red Dead Redemption 2", "League of Legends", "Pokemon"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0012 }
            Reponses := array{"Zelda", "Skyrim", "Flappy Bird", "Super Mario"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0013 }
            Reponses := array{"Five Nights at Freddy's", "Pokemon", "Zelda", "Assassin's Creed"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0014 }
            Reponses := array{"GTA V", "Overwatch", "Sonic", "Among Us"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0015 }
            Reponses := array{"Skyrim", "Hearthstone", "Pokemon", "Brawl Stars"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0016 }
            Reponses := array{"Tomb Raider", "Subway Surfers", "Temple Run", "GTA V"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0017 }
            Reponses := array{"World of Warcraft", "Flappy Bird", "Mortal Kombat", "Overwatch"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0018 }
            Reponses := array{"The Witcher 3", "Flappy Bird", "Street Fighter", "Candy Crush"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0019 }
            Reponses := array{"FIFA", "Sonic", "World of Warcraft", "Street Fighter"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0020 }
            Reponses := array{"Tomb Raider", "Street Fighter", "Clash Royale", "Overwatch"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0021 }
            Reponses := array{"Mortal Kombat", "The Witcher 3", "Sonic", "Cyberpunk 2077"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0022 }
            Reponses := array{"Elden Ring", "Castlevania", "Animal Crossing", "Quake"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0023 }
            Reponses := array{"Spyro", "Bloodborne", "Gran Turismo", "Diablo"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0024 }
            Reponses := array{"Quake", "Elden Ring", "Crash Bandicoot", "Sekiro"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0025 }
            Reponses := array{"Les Sims", "PUBG", "Crash Bandicoot", "Diablo"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0026 }
            Reponses := array{"Doom", "Genshin Impact", "Apex Legends", "Forza Horizon"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0027 }
            Reponses := array{"Quake", "Crash Bandicoot", "Borderlands", "PUBG"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0028 }
            Reponses := array{"Hades", "Half-Life", "Sea of Thieves", "Stardew Valley"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0029 }
            Reponses := array{"Hollow Knight", "Crash Bandicoot", "Animal Crossing", "Portal"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0030 }
            Reponses := array{"Gran Turismo", "BioShock", "Castlevania", "Stardew Valley"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0031 }
            Reponses := array{"PUBG", "Hollow Knight", "Borderlands", "Spyro"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0032 }
            Reponses := array{"BioShock", "Rocket League", "Les Sims", "Stardew Valley"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0033 }
            Reponses := array{"Hollow Knight", "Doom", "Castlevania", "Animal Crossing"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0034 }
            Reponses := array{"Kirby", "Terraria", "PUBG", "Elden Ring"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0035 }
            Reponses := array{"Castlevania", "Les Sims", "PUBG", "Crossy Road"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0036 }
            Reponses := array{"Crash Bandicoot", "Rocket League", "Sekiro", "Elden Ring"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0037 }
            Reponses := array{"Forza Horizon", "Spyro", "Portal", "PES"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0038 }
            Reponses := array{"Hades", "Hollow Knight", "Elden Ring", "Sea of Thieves"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0039 }
            Reponses := array{"Hades", "Diablo", "Bloodborne", "Doom"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0040 }
            Reponses := array{"Hades", "Portal", "Mario Party", "Stardew Valley"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0041 }
            Reponses := array{"Elden Ring", "Gran Turismo", "Terraria", "Forza Horizon"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0042 }
            Reponses := array{"Sea of Thieves", "Stardew Valley", "Rocket League", "Genshin Impact"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0043 }
            Reponses := array{"Hades", "Fruit Ninja", "Valorant", "Castlevania"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0044 }
            Reponses := array{"Hollow Knight", "Animal Crossing", "Mario Party", "Apex Legends"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0045 }
            Reponses := array{"PUBG", "Terraria", "PES", "Apex Legends"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0046 }
            Reponses := array{"Genshin Impact", "Spyro", "Bloodborne", "Diablo"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0047 }
            Reponses := array{"Braid", "Pong", "Centipede", "Nier Automata"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0048 }
            Reponses := array{"Amnesia", "Donkey Kong 1981", "Asteroids", "Galaga"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0049 }
            Reponses := array{"Galaga", "Baldur's Gate", "Wolfenstein 3D", "Amnesia"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0050 }
            Reponses := array{"Nier Automata", "Disco Elysium", "Dig Dug", "Centipede"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0051 }
            Reponses := array{"Chrono Trigger", "System Shock", "Frogger", "Deus Ex"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0052 }
            Reponses := array{"Dig Dug", "Frogger", "Asteroids", "Centipede"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0053 }
            Reponses := array{"Cuphead", "Disco Elysium", "Asteroids", "Deus Ex"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0054 }
            Reponses := array{"Disco Elysium", "Q*bert", "Amnesia", "Asteroids"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0055 }
            Reponses := array{"System Shock", "Myst", "Asteroids", "Baldur's Gate"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0056 }
            Reponses := array{"Chrono Trigger", "Celeste", "Asteroids", "Wolfenstein 3D"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0057 }
            Reponses := array{"Secret of Mana", "Deus Ex", "Journey", "System Shock"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0058 }
            Reponses := array{"Donkey Kong 1981", "System Shock", "Wolfenstein 3D", "Asteroids"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0059 }
            Reponses := array{"Ico", "Wolfenstein 3D", "Baldur's Gate", "Limbo"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0060 }
            Reponses := array{"Monster Hunter", "Planescape Torment", "Pong", "Amnesia"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0061 }
            Reponses := array{"Katamari Damacy", "Disco Elysium", "Secret of Mana", "Pong"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0062 }
            Reponses := array{"Ico", "Baldur's Gate", "Myst", "Pong"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0063 }
            Reponses := array{"Shadow of the Colossus", "Frogger", "Galaga", "Katamari Damacy"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0064 }
            Reponses := array{"Outlast", "Katamari Damacy", "Okami", "Centipede"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0065 }
            Reponses := array{"Baldur's Gate", "Okami", "Q*bert", "Pong"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0066 }
            Reponses := array{"Chrono Trigger", "Q*bert", "Katamari Damacy", "Centipede"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0067 }
            Reponses := array{"Dead by Daylight", "Q*bert", "Cuphead", "Secret of Mana"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0068 }
            Reponses := array{"Wolfenstein 3D", "Nier Automata", "Frogger", "Planescape Torment"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0069 }
            Reponses := array{"Centipede", "Monster Hunter", "Q*bert", "Wolfenstein 3D"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0070 }
            Reponses := array{"Dead by Daylight", "Journey", "System Shock", "Limbo"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0071 }
            Reponses := array{"Ico", "Katamari Damacy", "Cuphead", "Dead by Daylight"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0072 }
            Reponses := array{"Wolfenstein 3D", "Pong", "Celeste", "Journey"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0073 }
            Reponses := array{"Braid", "Limbo", "Frogger", "Outlast"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0074 }
            Reponses := array{"Frogger", "Limbo", "Celeste", "Disco Elysium"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0075 }
            Reponses := array{"Centipede", "Journey", "Donkey Kong 1981", "Monster Hunter"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0076 }
            Reponses := array{"Cuphead", "Q*bert", "Secret of Mana", "Outlast"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0077 }
            Reponses := array{"Braid", "Amnesia", "Journey", "Nier Automata"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0078 }
            Reponses := array{"Candy Crush", "Pokemon", "Clash of Clans", "Plants vs Zombies"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0079 }
            Reponses := array{"Clash of Clans", "GTA V", "Clash Royale", "Mortal Kombat"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0080 }
            Reponses := array{"Tomb Raider", "Candy Crush", "Clash Royale", "Street Fighter"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0081 }
            Reponses := array{"Street Fighter", "Pokemon Go", "Red Dead Redemption 2", "Subway Surfers"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0082 }
            Reponses := array{"Temple Run", "Tomb Raider", "Hearthstone", "Street Fighter"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0083 }
            Reponses := array{"Flappy Bird", "Red Dead Redemption 2", "Assassin's Creed", "The Witcher 3"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0084 }
            Reponses := array{"The Witcher 3", "Sonic", "League of Legends", "Brawl Stars"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0085 }
            Reponses := array{"Super Mario", "The Witcher 3", "FIFA", "Pokemon Go"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0086 }
            Reponses := array{"GTA V", "Dota 2", "Assassin's Creed", "FIFA"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0087 }
            Reponses := array{"Assassin's Creed", "League of Legends", "Hearthstone", "Candy Crush"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0088 }
            Reponses := array{"League of Legends", "Five Nights at Freddy's", "Brawl Stars", "Dota 2"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0089 }
            Reponses := array{"Space Invaders", "Plants vs Zombies", "Subway Surfers", "FIFA"}
            BonneReponse := 1
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0090 }
            Reponses := array{"Cut the Rope", "Sea of Thieves", "PES", "Fruit Ninja"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0091 }
            Reponses := array{"Crash Bandicoot", "Forza Horizon", "Stardew Valley", "Fruit Ninja"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0092 }
            Reponses := array{"Quake", "Fruit Ninja", "Gran Turismo", "Crossy Road"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0093 }
            Reponses := array{"Bloodborne", "Diablo", "Sea of Thieves", "Rocket League"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0094 }
            Reponses := array{"Gran Turismo", "Diablo", "It Takes Two", "PES"}
            BonneReponse := 2
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0095 }
            Reponses := array{"Portal", "Hades", "Rocket League", "Mario Party"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0096 }
            Reponses := array{"Just Dance", "Apex Legends", "Animal Crossing", "Stardew Valley"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0097 }
            Reponses := array{"Gran Turismo", "Castlevania", "Fruit Ninja", "PES"}
            BonneReponse := 0
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0098 }
            Reponses := array{"It Takes Two", "Fruit Ninja", "Quake", "Forza Horizon"}
            BonneReponse := 3
        question:
            Enonce := "Quel est ce jeu video ?"
            Image := option{ jeuxvideo.jv_0099 }
            Reponses := array{"Half-Life", "Sekiro", "PES", "Valorant"}
            BonneReponse := 2

MakeJeuxVideoQuestions() : []question =
    MakeJeuxVideoQuestionsFR()

MakeJeuxVideoQuestionsEN() : []question =
    Base := MakeJeuxVideoQuestionsFR()
    for (Q : Base):
        question{ Enonce := "What video game is this?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeJeuxVideoQuestionsES() : []question =
    Base := MakeJeuxVideoQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Que videojuego es este?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeJeuxVideoQuestionsDE() : []question =
    Base := MakeJeuxVideoQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Welches Videospiel ist das?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeJeuxVideoQuestionsIT() : []question =
    Base := MakeJeuxVideoQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Quale videogioco e questo?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }
