using { /Verse.org/Assets }

# logos_bank.verse — Quizz LOGOS & MARQUES (vignettes Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

LogosDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeLogosQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0001 }
            Reponses := array{"Porsche", "Ferrari", "Nike", "Pepsi"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0002 }
            Reponses := array{"Burger King", "Google", "Adidas", "YouTube"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0003 }
            Reponses := array{"Burger King", "Amazon", "Apple", "Lego"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0004 }
            Reponses := array{"Domino's Pizza", "Microsoft", "McDonald's", "Apple"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0005 }
            Reponses := array{"Coca-Cola", "YouTube", "Tesla", "Netflix"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0006 }
            Reponses := array{"McDonald's", "Audi", "Pepsi", "Amazon"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0007 }
            Reponses := array{"Google", "Nintendo", "Coca-Cola", "Red Bull"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0008 }
            Reponses := array{"Audi", "Toyota", "Adidas", "Microsoft"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0009 }
            Reponses := array{"Apple", "Netflix", "Porsche", "Amazon"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0010 }
            Reponses := array{"Rolex", "Instagram", "Burger King", "Xbox"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0011 }
            Reponses := array{"KFC", "Mercedes-Benz", "YouTube", "McDonald's"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0012 }
            Reponses := array{"Ikea", "Netflix", "Lego", "WhatsApp"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0013 }
            Reponses := array{"Starbucks", "Lamborghini", "Netflix", "Xbox"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0014 }
            Reponses := array{"YouTube", "McDonald's", "Red Bull", "Nintendo"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0015 }
            Reponses := array{"Lego", "Adidas", "Toyota", "Nintendo"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0016 }
            Reponses := array{"Coca-Cola", "Domino's Pizza", "Lamborghini", "Ferrari"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0017 }
            Reponses := array{"Adidas", "Apple", "Porsche", "Lamborghini"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0018 }
            Reponses := array{"Nintendo", "Volkswagen", "Porsche", "Google"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0019 }
            Reponses := array{"Netflix", "Adidas", "BMW", "Instagram"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0020 }
            Reponses := array{"Volkswagen", "Louis Vuitton", "Burger King", "Mercedes-Benz"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0021 }
            Reponses := array{"Ferrari", "Burger King", "Audi", "TikTok"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0022 }
            Reponses := array{"McDonald's", "Volkswagen", "Audi", "Coca-Cola"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0023 }
            Reponses := array{"Lego", "Adidas", "Microsoft", "Toyota"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0024 }
            Reponses := array{"Instagram", "Nintendo", "Microsoft", "Tesla"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0025 }
            Reponses := array{"Xbox", "Red Bull", "McDonald's", "Pepsi"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0026 }
            Reponses := array{"Xbox", "Microsoft", "Domino's Pizza", "Starbucks"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0027 }
            Reponses := array{"Porsche", "Nintendo", "KFC", "Domino's Pizza"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0028 }
            Reponses := array{"Burger King", "YouTube", "Tesla", "Ferrari"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0029 }
            Reponses := array{"Tesla", "Domino's Pizza", "KFC", "Toyota"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0030 }
            Reponses := array{"Starbucks", "Ikea", "Louis Vuitton", "Toyota"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0031 }
            Reponses := array{"Volkswagen", "Red Bull", "Lamborghini", "Louis Vuitton"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0032 }
            Reponses := array{"Pepsi", "Volkswagen", "Chanel", "Lego"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0033 }
            Reponses := array{"Rolex", "Toyota", "Domino's Pizza", "YouTube"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0034 }
            Reponses := array{"Rolex", "Porsche", "WhatsApp", "McDonald's"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0035 }
            Reponses := array{"Coca-Cola", "Porsche", "Louis Vuitton", "TikTok"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0036 }
            Reponses := array{"Under Armour", "Ubisoft", "Prada", "Lufthansa"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0037 }
            Reponses := array{"Lacoste", "Rockstar Games", "Under Armour", "Uber"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0038 }
            Reponses := array{"Levi's", "Nutella", "Telegram", "Electronic Arts"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0039 }
            Reponses := array{"Fiat", "Intel", "Gucci", "Pringles"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0040 }
            Reponses := array{"Prada", "Nutella", "Visa", "Gucci"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0041 }
            Reponses := array{"Levi's", "Asus", "Uber", "Versace"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0042 }
            Reponses := array{"Oreo", "Honda", "Renault", "Ray-Ban"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0043 }
            Reponses := array{"Nestle", "Electronic Arts", "FedEx", "Under Armour"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0044 }
            Reponses := array{"Danone", "Epic Games", "Uber", "Peugeot"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0045 }
            Reponses := array{"Ryanair", "Nutella", "Honda", "Pringles"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0046 }
            Reponses := array{"Oreo", "Xiaomi", "Visa", "Airbnb"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0047 }
            Reponses := array{"Sony", "Pringles", "FedEx", "Lacoste"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0048 }
            Reponses := array{"Danone", "Dell", "Intel", "PayPal"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0049 }
            Reponses := array{"Nvidia", "Nutella", "Michelin", "Telegram"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0050 }
            Reponses := array{"PayPal", "Logitech", "Ubisoft", "Sony"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0051 }
            Reponses := array{"Huawei", "Ford", "Visa", "Dell"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0052 }
            Reponses := array{"Asus", "Xiaomi", "Electronic Arts", "FedEx"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0053 }
            Reponses := array{"Dell", "FedEx", "Uber", "Honda"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0054 }
            Reponses := array{"Renault", "Air France", "Lenovo", "Xiaomi"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0055 }
            Reponses := array{"Mastercard", "Gucci", "Asus", "FedEx"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0056 }
            Reponses := array{"Airbnb", "Michelin", "Gucci", "Logitech"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0057 }
            Reponses := array{"Lenovo", "Visa", "Prada", "Levi's"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0058 }
            Reponses := array{"Asus", "Ray-Ban", "Renault", "Mastercard"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0059 }
            Reponses := array{"Nutella", "PayPal", "Lacoste", "Electronic Arts"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0060 }
            Reponses := array{"Lenovo", "FedEx", "Fiat", "Intel"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0061 }
            Reponses := array{"Electronic Arts", "Intel", "Honda", "DHL"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0062 }
            Reponses := array{"Sony", "DHL", "Michelin", "Oreo"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0063 }
            Reponses := array{"Levi's", "Gucci", "Telegram", "Renault"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0064 }
            Reponses := array{"Nestle", "Lacoste", "Peugeot", "Airbnb"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0065 }
            Reponses := array{"Prada", "Fiat", "Logitech", "Ford"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0066 }
            Reponses := array{"Airbnb", "Uber", "PayPal", "Honda"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0067 }
            Reponses := array{"Michelin", "Lufthansa", "Sony", "Suzuki"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0068 }
            Reponses := array{"Ford", "Steam", "Airbnb", "Suzuki"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0069 }
            Reponses := array{"Xiaomi", "Pringles", "Nvidia", "Air France"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0070 }
            Reponses := array{"Renault", "Fiat", "Ford", "Lufthansa"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0071 }
            Reponses := array{"Nvidia", "Ryanair", "Prada", "Sony"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0072 }
            Reponses := array{"Nvidia", "Nestle", "Airbnb", "FedEx"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0073 }
            Reponses := array{"Rockstar Games", "Uber", "FedEx", "Renault"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0074 }
            Reponses := array{"Huawei", "Ryanair", "Versace", "Twitch"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0075 }
            Reponses := array{"Telegram", "Oreo", "Danone", "Honda"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0076 }
            Reponses := array{"PayPal", "Airbnb", "Discord", "Twitch"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0077 }
            Reponses := array{"Levi's", "Lufthansa", "Steam", "Prada"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0078 }
            Reponses := array{"Huawei", "Ryanair", "Dell", "Epic Games"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0079 }
            Reponses := array{"Ubisoft", "Logitech", "Discord", "Dell"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0080 }
            Reponses := array{"Nestle", "Lufthansa", "Electronic Arts", "Epic Games"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0081 }
            Reponses := array{"Air France", "Ford", "Rockstar Games", "Danone"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0082 }
            Reponses := array{"Casio", "Philips", "Carrefour", "Subaru"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0083 }
            Reponses := array{"Philips", "Perrier", "Lidl", "Omega"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0084 }
            Reponses := array{"SpaceX", "Aldi", "TAG Heuer", "Skoda"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0085 }
            Reponses := array{"Decathlon", "TAG Heuer", "General Electric", "Swatch"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0086 }
            Reponses := array{"Boeing", "TAG Heuer", "Orange", "Omega"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0087 }
            Reponses := array{"Vodafone", "Swatch", "Mazda", "Hyundai"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0088 }
            Reponses := array{"Boeing", "Vodafone", "Bic", "TAG Heuer"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0089 }
            Reponses := array{"Omega", "Airbus", "Perrier", "GitHub"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0090 }
            Reponses := array{"Aldi", "SpaceX", "Boeing", "Decathlon"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0091 }
            Reponses := array{"Vodafone", "Bosch", "General Electric", "Omega"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0092 }
            Reponses := array{"Decathlon", "Orange", "Dyson", "TAG Heuer"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0093 }
            Reponses := array{"General Electric", "Swatch", "Evian", "Perrier"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0094 }
            Reponses := array{"Casio", "Skoda", "Swatch", "Evian"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0095 }
            Reponses := array{"Milka", "GitHub", "Evian", "Philips"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0096 }
            Reponses := array{"Evian", "Perrier", "Subaru", "Siemens"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0097 }
            Reponses := array{"Bic", "Swatch", "Bosch", "Siemens"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0098 }
            Reponses := array{"Dyson", "Boeing", "Subaru", "Omega"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0099 }
            Reponses := array{"Airbus", "Bic", "GitHub", "Dyson"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0100 }
            Reponses := array{"Subaru", "Carrefour", "3M", "Casio"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0101 }
            Reponses := array{"Lidl", "General Electric", "Bic", "Aldi"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0102 }
            Reponses := array{"Bosch", "Siemens", "GitHub", "Evian"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0103 }
            Reponses := array{"Aldi", "Citroen", "SpaceX", "Skoda"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0104 }
            Reponses := array{"Skoda", "Philips", "Carrefour", "Decathlon"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0105 }
            Reponses := array{"Subaru", "Milka", "Casio", "Dyson"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0106 }
            Reponses := array{"Lidl", "Swatch", "Aldi", "Mazda"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0107 }
            Reponses := array{"Citroen", "Hyundai", "TAG Heuer", "Casio"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0108 }
            Reponses := array{"Boeing", "Perrier", "Evian", "Swatch"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0109 }
            Reponses := array{"Bosch", "Decathlon", "SpaceX", "Perrier"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette marque ?"
            Image := option{ logos.logo_0110 }
            Reponses := array{"Bosch", "Milka", "SpaceX", "Hyundai"}
            BonneReponse := 1

MakeLogosQuestions() : []question =
    MakeLogosQuestionsFR()

MakeLogosQuestionsEN() : []question =
    Base := MakeLogosQuestionsFR()
    for (Q : Base):
        question{ Enonce := "What brand is this?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeLogosQuestionsES() : []question =
    Base := MakeLogosQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Que marca es esta?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeLogosQuestionsDE() : []question =
    Base := MakeLogosQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Welche Marke ist das?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeLogosQuestionsIT() : []question =
    Base := MakeLogosQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Quale marca e questa?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }
