using { /Verse.org/Assets }

# mytho_bank.verse — Quizz MYTHOLOGIE (images Wikipedia, domaine public)
# GENERE — NE PAS EDITER A LA MAIN.

MythoDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeMythoQuestionsFR() : []question =
    array:
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0001 }
            Reponses := array{"Zeus", "Apollon", "Hephaistos", "Hades"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0002 }
            Reponses := array{"Poseidon", "Aphrodite", "Hera", "Meduse"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0003 }
            Reponses := array{"Meduse", "Hades", "Athena", "Ra"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0004 }
            Reponses := array{"Dionysos", "Hera", "Heracles", "Anubis"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0005 }
            Reponses := array{"Athena", "Zeus", "Pegase", "Meduse"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0006 }
            Reponses := array{"Hermes", "Heracles", "Apollon", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0007 }
            Reponses := array{"Osiris", "Artemis", "Poseidon", "Minotaure"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0008 }
            Reponses := array{"Hades", "Minotaure", "Loki", "Ares"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0009 }
            Reponses := array{"Ares", "Ulysse", "Aphrodite", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0010 }
            Reponses := array{"Anubis", "Pegase", "Hermes", "Achille"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0011 }
            Reponses := array{"Osiris", "Anubis", "Pegase", "Hephaistos"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0012 }
            Reponses := array{"Demeter", "Minotaure", "Meduse", "Poseidon"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0013 }
            Reponses := array{"Ra", "Achille", "Poseidon", "Dionysos"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0014 }
            Reponses := array{"Heracles", "Ares", "Cronos", "Minotaure"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0015 }
            Reponses := array{"Thor", "Demeter", "Achille", "Ra"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0016 }
            Reponses := array{"Ra", "Osiris", "Ulysse", "Hephaistos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0017 }
            Reponses := array{"Dionysos", "Hades", "Athena", "Meduse"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0018 }
            Reponses := array{"Minotaure", "Pegase", "Athena", "Meduse"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0019 }
            Reponses := array{"Dionysos", "Pegase", "Ra", "Achille"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0020 }
            Reponses := array{"Thor", "Hephaistos", "Loki", "Dionysos"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0021 }
            Reponses := array{"Pegase", "Odin", "Artemis", "Hades"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0022 }
            Reponses := array{"Pegase", "Poseidon", "Loki", "Ares"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0023 }
            Reponses := array{"Pegase", "Osiris", "Apollon", "Ra"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0024 }
            Reponses := array{"Anubis", "Meduse", "Pegase", "Hermes"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0025 }
            Reponses := array{"Hephaistos", "Osiris", "Apollon", "Aphrodite"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0026 }
            Reponses := array{"Poseidon", "Cronos", "Athena", "Ares"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0027 }
            Reponses := array{"Persephone", "Horus", "Thesee", "Cyclope"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0028 }
            Reponses := array{"Hestia", "Thesee", "Baldr", "Freyja"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0029 }
            Reponses := array{"Persee", "Orphee", "Promethee", "Thesee"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0030 }
            Reponses := array{"Seth", "Thesee", "Centaure", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0031 }
            Reponses := array{"Jason", "Freyja", "Valkyrie", "Cerbere"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0032 }
            Reponses := array{"Centaure", "Icare", "Dedale", "Eros"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0033 }
            Reponses := array{"Valkyrie", "Fenrir", "Pandore", "Dedale"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0034 }
            Reponses := array{"Orphee", "Bastet", "Valkyrie", "Cyclope"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0035 }
            Reponses := array{"Sirene", "Promethee", "Orphee", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0036 }
            Reponses := array{"Atlas", "Fenrir", "Pandore", "Icare"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0037 }
            Reponses := array{"Atlas", "Pandore", "Persee", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0038 }
            Reponses := array{"Narcisse", "Seth", "Isis", "Fenrir"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0039 }
            Reponses := array{"Jason", "Hestia", "Eros", "Fenrir"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0040 }
            Reponses := array{"Thesee", "Narcisse", "Eros", "Nike"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0041 }
            Reponses := array{"Cerbere", "Hestia", "Freyja", "Atlas"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0042 }
            Reponses := array{"Horus", "Narcisse", "Nike", "Cyclope"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0043 }
            Reponses := array{"Centaure", "Freyja", "Eros", "Bastet"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0044 }
            Reponses := array{"Thesee", "Sirene", "Freyja", "Isis"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0045 }
            Reponses := array{"Freyja", "Fenrir", "Thesee", "Persee"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0046 }
            Reponses := array{"Dedale", "Baldr", "Cerbere", "Hestia"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0047 }
            Reponses := array{"Cerbere", "Baldr", "Horus", "Fenrir"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0048 }
            Reponses := array{"Baldr", "Valkyrie", "Thesee", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0049 }
            Reponses := array{"Hestia", "Baldr", "Fenrir", "Horus"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0050 }
            Reponses := array{"Nike", "Jason", "Isis", "Cerbere"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0051 }
            Reponses := array{"Promethee", "Cerbere", "Seth", "Narcisse"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0052 }
            Reponses := array{"Fenrir", "Eros", "Bastet", "Hestia"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0053 }
            Reponses := array{"Hel", "Thanatos", "Charon", "Helios"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0054 }
            Reponses := array{"Heimdall", "Anput", "Raijin", "Thot"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0055 }
            Reponses := array{"Jormungandr", "Tyr", "Kali", "Vishnou"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0056 }
            Reponses := array{"Eos", "Brahma", "Mjolnir", "Amaterasu"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0057 }
            Reponses := array{"Jormungandr", "Quetzalcoatl", "Kraken", "Chimere"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0058 }
            Reponses := array{"Kraken", "Tyr", "Hel", "Vishnou"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0059 }
            Reponses := array{"Tiamat", "Sphinx", "Inanna", "Sobek"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0060 }
            Reponses := array{"Styx", "Shiva", "Chimere", "Thot"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0061 }
            Reponses := array{"Hydre de Lerne", "Sphinx", "Anput", "Ouranos"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0062 }
            Reponses := array{"Charon", "Ouranos", "Helios", "Hypnos"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0063 }
            Reponses := array{"Tiamat", "Chimere", "Styx", "Hypnos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0064 }
            Reponses := array{"Helios", "Hydre de Lerne", "Inanna", "Tartare"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0065 }
            Reponses := array{"Sphinx", "Gaia", "Heimdall", "Ouranos"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0066 }
            Reponses := array{"Ouranos", "Kali", "Hypnos", "Tyr"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0067 }
            Reponses := array{"Nemesis", "Eos", "Thot", "Helios"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0068 }
            Reponses := array{"Amaterasu", "Selene", "Hel", "Heimdall"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0069 }
            Reponses := array{"Selene", "Eos", "Quetzalcoatl", "Kraken"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0070 }
            Reponses := array{"Brahma", "Marduk", "Sobek", "Nemesis"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0071 }
            Reponses := array{"Hypnos", "Izanagi", "Selene", "Styx"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0072 }
            Reponses := array{"Anput", "Morphee", "Ouranos", "Thanatos"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0073 }
            Reponses := array{"Jormungandr", "Thanatos", "Charon", "Raijin"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0074 }
            Reponses := array{"Chimere", "Charon", "Quetzalcoatl", "Sphinx"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0075 }
            Reponses := array{"Nemesis", "Selene", "Helios", "Amaterasu"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0076 }
            Reponses := array{"Raijin", "Kali", "Gaia", "Brahma"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0077 }
            Reponses := array{"Izanagi", "Sphinx", "Gaia", "Heimdall"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0078 }
            Reponses := array{"Ganesh", "Sobek", "Bes", "Hydre de Lerne"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0079 }
            Reponses := array{"Hypnos", "Thanatos", "Thot", "Eos"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0080 }
            Reponses := array{"Anput", "Raijin", "Helios", "Amaterasu"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0081 }
            Reponses := array{"Quetzalcoatl", "Eos", "Mjolnir", "Bes"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0082 }
            Reponses := array{"Marduk", "Nemesis", "Maat", "Anput"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0083 }
            Reponses := array{"Kali", "Sobek", "Jormungandr", "Vishnou"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0084 }
            Reponses := array{"Mjolnir", "Shiva", "Kali", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0085 }
            Reponses := array{"Gaia", "Kraken", "Heimdall", "Ganesh"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0086 }
            Reponses := array{"Kali", "Heimdall", "Morphee", "Mjolnir"}
            BonneReponse := 0
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0087 }
            Reponses := array{"Thot", "Brahma", "Helios", "Inanna"}
            BonneReponse := 1
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0088 }
            Reponses := array{"Quetzalcoatl", "Nemesis", "Charon", "Tiamat"}
            BonneReponse := 3
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0089 }
            Reponses := array{"Chimere", "Helios", "Marduk", "Vishnou"}
            BonneReponse := 2
        question:
            Enonce := "Qui est cette figure mythologique ?"
            Image := option{ mytho.myt_0090 }
            Reponses := array{"Raijin", "Heimdall", "Izanagi", "Inanna"}
            BonneReponse := 3

MakeMythoQuestionsEN() : []question =
    array:
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0001 }
            Reponses := array{"Zeus", "Apollo", "Hephaestus", "Hades"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0002 }
            Reponses := array{"Poseidon", "Aphrodite", "Hera", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0003 }
            Reponses := array{"Medusa", "Hades", "Athena", "Ra"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0004 }
            Reponses := array{"Dionysus", "Hera", "Heracles", "Anubis"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0005 }
            Reponses := array{"Athena", "Zeus", "Pegasus", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0006 }
            Reponses := array{"Hermes", "Heracles", "Apollo", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0007 }
            Reponses := array{"Osiris", "Artemis", "Poseidon", "Minotaur"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0008 }
            Reponses := array{"Hades", "Minotaur", "Loki", "Ares"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0009 }
            Reponses := array{"Ares", "Odysseus", "Aphrodite", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0010 }
            Reponses := array{"Anubis", "Pegasus", "Hermes", "Achilles"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0011 }
            Reponses := array{"Osiris", "Anubis", "Pegasus", "Hephaestus"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0012 }
            Reponses := array{"Demeter", "Minotaur", "Medusa", "Poseidon"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0013 }
            Reponses := array{"Ra", "Achilles", "Poseidon", "Dionysus"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0014 }
            Reponses := array{"Heracles", "Ares", "Cronus", "Minotaur"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0015 }
            Reponses := array{"Thor", "Demeter", "Achilles", "Ra"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0016 }
            Reponses := array{"Ra", "Osiris", "Odysseus", "Hephaestus"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0017 }
            Reponses := array{"Dionysus", "Hades", "Athena", "Medusa"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0018 }
            Reponses := array{"Minotaur", "Pegasus", "Athena", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0019 }
            Reponses := array{"Dionysus", "Pegasus", "Ra", "Achilles"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0020 }
            Reponses := array{"Thor", "Hephaestus", "Loki", "Dionysus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0021 }
            Reponses := array{"Pegasus", "Odin", "Artemis", "Hades"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0022 }
            Reponses := array{"Pegasus", "Poseidon", "Loki", "Ares"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0023 }
            Reponses := array{"Pegasus", "Osiris", "Apollo", "Ra"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0024 }
            Reponses := array{"Anubis", "Medusa", "Pegasus", "Hermes"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0025 }
            Reponses := array{"Hephaestus", "Osiris", "Apollo", "Aphrodite"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0026 }
            Reponses := array{"Poseidon", "Cronus", "Athena", "Ares"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0027 }
            Reponses := array{"Persephone", "Horus", "Theseus", "Cyclops"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0028 }
            Reponses := array{"Hestia", "Theseus", "Baldr", "Freyja"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0029 }
            Reponses := array{"Perseus", "Orpheus", "Prometheus", "Theseus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0030 }
            Reponses := array{"Set", "Theseus", "Centaur", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0031 }
            Reponses := array{"Jason", "Freyja", "Valkyrie", "Cerberus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0032 }
            Reponses := array{"Centaur", "Icarus", "Daedalus", "Eros"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0033 }
            Reponses := array{"Valkyrie", "Fenrir", "Pandora", "Daedalus"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0034 }
            Reponses := array{"Orpheus", "Bastet", "Valkyrie", "Cyclops"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0035 }
            Reponses := array{"Siren", "Prometheus", "Orpheus", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0036 }
            Reponses := array{"Atlas", "Fenrir", "Pandora", "Icarus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0037 }
            Reponses := array{"Atlas", "Pandora", "Perseus", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0038 }
            Reponses := array{"Narcissus", "Set", "Isis", "Fenrir"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0039 }
            Reponses := array{"Jason", "Hestia", "Eros", "Fenrir"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0040 }
            Reponses := array{"Theseus", "Narcissus", "Eros", "Nike"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0041 }
            Reponses := array{"Cerberus", "Hestia", "Freyja", "Atlas"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0042 }
            Reponses := array{"Horus", "Narcissus", "Nike", "Cyclops"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0043 }
            Reponses := array{"Centaur", "Freyja", "Eros", "Bastet"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0044 }
            Reponses := array{"Theseus", "Siren", "Freyja", "Isis"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0045 }
            Reponses := array{"Freyja", "Fenrir", "Theseus", "Perseus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0046 }
            Reponses := array{"Daedalus", "Baldr", "Cerberus", "Hestia"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0047 }
            Reponses := array{"Cerberus", "Baldr", "Horus", "Fenrir"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0048 }
            Reponses := array{"Baldr", "Valkyrie", "Theseus", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0049 }
            Reponses := array{"Hestia", "Baldr", "Fenrir", "Horus"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0050 }
            Reponses := array{"Nike", "Jason", "Isis", "Cerberus"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0051 }
            Reponses := array{"Prometheus", "Cerberus", "Set", "Narcissus"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0052 }
            Reponses := array{"Fenrir", "Eros", "Bastet", "Hestia"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0053 }
            Reponses := array{"Hel", "Thanatos", "Charon", "Helios"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0054 }
            Reponses := array{"Heimdall", "Anput", "Raijin", "Thoth"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0055 }
            Reponses := array{"Jormungandr", "Tyr", "Kali", "Vishnu"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0056 }
            Reponses := array{"Eos", "Brahma", "Mjolnir", "Amaterasu"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0057 }
            Reponses := array{"Jormungandr", "Quetzalcoatl", "Kraken", "Chimera"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0058 }
            Reponses := array{"Kraken", "Tyr", "Hel", "Vishnu"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0059 }
            Reponses := array{"Tiamat", "Sphinx", "Inanna", "Sobek"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0060 }
            Reponses := array{"Styx", "Shiva", "Chimera", "Thoth"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0061 }
            Reponses := array{"Hydra", "Sphinx", "Anput", "Uranus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0062 }
            Reponses := array{"Charon", "Uranus", "Helios", "Hypnos"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0063 }
            Reponses := array{"Tiamat", "Chimera", "Styx", "Hypnos"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0064 }
            Reponses := array{"Helios", "Hydra", "Inanna", "Tartarus"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0065 }
            Reponses := array{"Sphinx", "Gaia", "Heimdall", "Uranus"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0066 }
            Reponses := array{"Uranus", "Kali", "Hypnos", "Tyr"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0067 }
            Reponses := array{"Nemesis", "Eos", "Thoth", "Helios"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0068 }
            Reponses := array{"Amaterasu", "Selene", "Hel", "Heimdall"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0069 }
            Reponses := array{"Selene", "Eos", "Quetzalcoatl", "Kraken"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0070 }
            Reponses := array{"Brahma", "Marduk", "Sobek", "Nemesis"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0071 }
            Reponses := array{"Hypnos", "Izanagi", "Selene", "Styx"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0072 }
            Reponses := array{"Anput", "Morpheus", "Uranus", "Thanatos"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0073 }
            Reponses := array{"Jormungandr", "Thanatos", "Charon", "Raijin"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0074 }
            Reponses := array{"Chimera", "Charon", "Quetzalcoatl", "Sphinx"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0075 }
            Reponses := array{"Nemesis", "Selene", "Helios", "Amaterasu"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0076 }
            Reponses := array{"Raijin", "Kali", "Gaia", "Brahma"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0077 }
            Reponses := array{"Izanagi", "Sphinx", "Gaia", "Heimdall"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0078 }
            Reponses := array{"Ganesha", "Sobek", "Bes", "Hydra"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0079 }
            Reponses := array{"Hypnos", "Thanatos", "Thoth", "Eos"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0080 }
            Reponses := array{"Anput", "Raijin", "Helios", "Amaterasu"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0081 }
            Reponses := array{"Quetzalcoatl", "Eos", "Mjolnir", "Bes"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0082 }
            Reponses := array{"Marduk", "Nemesis", "Maat", "Anput"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0083 }
            Reponses := array{"Kali", "Sobek", "Jormungandr", "Vishnu"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0084 }
            Reponses := array{"Mjolnir", "Shiva", "Kali", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0085 }
            Reponses := array{"Gaia", "Kraken", "Heimdall", "Ganesha"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0086 }
            Reponses := array{"Kali", "Heimdall", "Morpheus", "Mjolnir"}
            BonneReponse := 0
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0087 }
            Reponses := array{"Thoth", "Brahma", "Helios", "Inanna"}
            BonneReponse := 1
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0088 }
            Reponses := array{"Quetzalcoatl", "Nemesis", "Charon", "Tiamat"}
            BonneReponse := 3
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0089 }
            Reponses := array{"Chimera", "Helios", "Marduk", "Vishnu"}
            BonneReponse := 2
        question:
            Enonce := "Who is this mythological figure?"
            Image := option{ mytho.myt_0090 }
            Reponses := array{"Raijin", "Heimdall", "Izanagi", "Inanna"}
            BonneReponse := 3

MakeMythoQuestionsES() : []question =
    array:
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0001 }
            Reponses := array{"Zeus", "Apolo", "Hefesto", "Hades"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0002 }
            Reponses := array{"Poseidon", "Afrodita", "Hera", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0003 }
            Reponses := array{"Medusa", "Hades", "Atenea", "Ra"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0004 }
            Reponses := array{"Dioniso", "Hera", "Heracles", "Anubis"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0005 }
            Reponses := array{"Atenea", "Zeus", "Pegaso", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0006 }
            Reponses := array{"Hermes", "Heracles", "Apolo", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0007 }
            Reponses := array{"Osiris", "Artemisa", "Poseidon", "Minotauro"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0008 }
            Reponses := array{"Hades", "Minotauro", "Loki", "Ares"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0009 }
            Reponses := array{"Ares", "Ulises", "Afrodita", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0010 }
            Reponses := array{"Anubis", "Pegaso", "Hermes", "Aquiles"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0011 }
            Reponses := array{"Osiris", "Anubis", "Pegaso", "Hefesto"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0012 }
            Reponses := array{"Demeter", "Minotauro", "Medusa", "Poseidon"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0013 }
            Reponses := array{"Ra", "Aquiles", "Poseidon", "Dioniso"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0014 }
            Reponses := array{"Heracles", "Ares", "Cronos", "Minotauro"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0015 }
            Reponses := array{"Thor", "Demeter", "Aquiles", "Ra"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0016 }
            Reponses := array{"Ra", "Osiris", "Ulises", "Hefesto"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0017 }
            Reponses := array{"Dioniso", "Hades", "Atenea", "Medusa"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0018 }
            Reponses := array{"Minotauro", "Pegaso", "Atenea", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0019 }
            Reponses := array{"Dioniso", "Pegaso", "Ra", "Aquiles"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0020 }
            Reponses := array{"Thor", "Hefesto", "Loki", "Dioniso"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0021 }
            Reponses := array{"Pegaso", "Odin", "Artemisa", "Hades"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0022 }
            Reponses := array{"Pegaso", "Poseidon", "Loki", "Ares"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0023 }
            Reponses := array{"Pegaso", "Osiris", "Apolo", "Ra"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0024 }
            Reponses := array{"Anubis", "Medusa", "Pegaso", "Hermes"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0025 }
            Reponses := array{"Hefesto", "Osiris", "Apolo", "Afrodita"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0026 }
            Reponses := array{"Poseidon", "Cronos", "Atenea", "Ares"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0027 }
            Reponses := array{"Persefone", "Horus", "Teseo", "Ciclope"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0028 }
            Reponses := array{"Hestia", "Teseo", "Baldr", "Freyja"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0029 }
            Reponses := array{"Perseo", "Orfeo", "Prometeo", "Teseo"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0030 }
            Reponses := array{"Set", "Teseo", "Centauro", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0031 }
            Reponses := array{"Jason", "Freyja", "Valquiria", "Cerbero"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0032 }
            Reponses := array{"Centauro", "Icaro", "Dedalo", "Eros"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0033 }
            Reponses := array{"Valquiria", "Fenrir", "Pandora", "Dedalo"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0034 }
            Reponses := array{"Orfeo", "Bastet", "Valquiria", "Ciclope"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0035 }
            Reponses := array{"Sirena", "Prometeo", "Orfeo", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0036 }
            Reponses := array{"Atlas", "Fenrir", "Pandora", "Icaro"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0037 }
            Reponses := array{"Atlas", "Pandora", "Perseo", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0038 }
            Reponses := array{"Narciso", "Set", "Isis", "Fenrir"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0039 }
            Reponses := array{"Jason", "Hestia", "Eros", "Fenrir"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0040 }
            Reponses := array{"Teseo", "Narciso", "Eros", "Nike"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0041 }
            Reponses := array{"Cerbero", "Hestia", "Freyja", "Atlas"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0042 }
            Reponses := array{"Horus", "Narciso", "Nike", "Ciclope"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0043 }
            Reponses := array{"Centauro", "Freyja", "Eros", "Bastet"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0044 }
            Reponses := array{"Teseo", "Sirena", "Freyja", "Isis"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0045 }
            Reponses := array{"Freyja", "Fenrir", "Teseo", "Perseo"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0046 }
            Reponses := array{"Dedalo", "Baldr", "Cerbero", "Hestia"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0047 }
            Reponses := array{"Cerbero", "Baldr", "Horus", "Fenrir"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0048 }
            Reponses := array{"Baldr", "Valquiria", "Teseo", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0049 }
            Reponses := array{"Hestia", "Baldr", "Fenrir", "Horus"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0050 }
            Reponses := array{"Nike", "Jason", "Isis", "Cerbero"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0051 }
            Reponses := array{"Prometeo", "Cerbero", "Set", "Narciso"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0052 }
            Reponses := array{"Fenrir", "Eros", "Bastet", "Hestia"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0053 }
            Reponses := array{"Hel", "Thanatos", "Caronte", "Helios"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0054 }
            Reponses := array{"Heimdall", "Anput", "Raijin", "Tot"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0055 }
            Reponses := array{"Jormungandr", "Tyr", "Kali", "Visnu"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0056 }
            Reponses := array{"Eos", "Brahma", "Mjolnir", "Amaterasu"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0057 }
            Reponses := array{"Jormungandr", "Quetzalcoatl", "Kraken", "Quimera"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0058 }
            Reponses := array{"Kraken", "Tyr", "Hel", "Visnu"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0059 }
            Reponses := array{"Tiamat", "Esfinge", "Inanna", "Sobek"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0060 }
            Reponses := array{"Estigia", "Shiva", "Quimera", "Tot"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0061 }
            Reponses := array{"Hidra", "Esfinge", "Anput", "Urano"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0062 }
            Reponses := array{"Caronte", "Urano", "Helios", "Hypnos"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0063 }
            Reponses := array{"Tiamat", "Quimera", "Estigia", "Hypnos"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0064 }
            Reponses := array{"Helios", "Hidra", "Inanna", "Tartaro"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0065 }
            Reponses := array{"Esfinge", "Gaia", "Heimdall", "Urano"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0066 }
            Reponses := array{"Urano", "Kali", "Hypnos", "Tyr"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0067 }
            Reponses := array{"Nemesis", "Eos", "Tot", "Helios"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0068 }
            Reponses := array{"Amaterasu", "Selene", "Hel", "Heimdall"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0069 }
            Reponses := array{"Selene", "Eos", "Quetzalcoatl", "Kraken"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0070 }
            Reponses := array{"Brahma", "Marduk", "Sobek", "Nemesis"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0071 }
            Reponses := array{"Hypnos", "Izanagi", "Selene", "Estigia"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0072 }
            Reponses := array{"Anput", "Morfeo", "Urano", "Thanatos"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0073 }
            Reponses := array{"Jormungandr", "Thanatos", "Caronte", "Raijin"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0074 }
            Reponses := array{"Quimera", "Caronte", "Quetzalcoatl", "Esfinge"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0075 }
            Reponses := array{"Nemesis", "Selene", "Helios", "Amaterasu"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0076 }
            Reponses := array{"Raijin", "Kali", "Gaia", "Brahma"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0077 }
            Reponses := array{"Izanagi", "Esfinge", "Gaia", "Heimdall"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0078 }
            Reponses := array{"Ganesha", "Sobek", "Bes", "Hidra"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0079 }
            Reponses := array{"Hypnos", "Thanatos", "Tot", "Eos"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0080 }
            Reponses := array{"Anput", "Raijin", "Helios", "Amaterasu"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0081 }
            Reponses := array{"Quetzalcoatl", "Eos", "Mjolnir", "Bes"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0082 }
            Reponses := array{"Marduk", "Nemesis", "Maat", "Anput"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0083 }
            Reponses := array{"Kali", "Sobek", "Jormungandr", "Visnu"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0084 }
            Reponses := array{"Mjolnir", "Shiva", "Kali", "Caronte"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0085 }
            Reponses := array{"Gaia", "Kraken", "Heimdall", "Ganesha"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0086 }
            Reponses := array{"Kali", "Heimdall", "Morfeo", "Mjolnir"}
            BonneReponse := 0
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0087 }
            Reponses := array{"Tot", "Brahma", "Helios", "Inanna"}
            BonneReponse := 1
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0088 }
            Reponses := array{"Quetzalcoatl", "Nemesis", "Caronte", "Tiamat"}
            BonneReponse := 3
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0089 }
            Reponses := array{"Quimera", "Helios", "Marduk", "Visnu"}
            BonneReponse := 2
        question:
            Enonce := "Quien es esta figura mitologica?"
            Image := option{ mytho.myt_0090 }
            Reponses := array{"Raijin", "Heimdall", "Izanagi", "Inanna"}
            BonneReponse := 3

MakeMythoQuestionsDE() : []question =
    array:
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0001 }
            Reponses := array{"Zeus", "Apollon", "Hephaistos", "Hades"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0002 }
            Reponses := array{"Poseidon", "Aphrodite", "Hera", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0003 }
            Reponses := array{"Medusa", "Hades", "Athene", "Ra"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0004 }
            Reponses := array{"Dionysos", "Hera", "Herakles", "Anubis"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0005 }
            Reponses := array{"Athene", "Zeus", "Pegasus", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0006 }
            Reponses := array{"Hermes", "Herakles", "Apollon", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0007 }
            Reponses := array{"Osiris", "Artemis", "Poseidon", "Minotaurus"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0008 }
            Reponses := array{"Hades", "Minotaurus", "Loki", "Ares"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0009 }
            Reponses := array{"Ares", "Odysseus", "Aphrodite", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0010 }
            Reponses := array{"Anubis", "Pegasus", "Hermes", "Achilles"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0011 }
            Reponses := array{"Osiris", "Anubis", "Pegasus", "Hephaistos"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0012 }
            Reponses := array{"Demeter", "Minotaurus", "Medusa", "Poseidon"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0013 }
            Reponses := array{"Ra", "Achilles", "Poseidon", "Dionysos"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0014 }
            Reponses := array{"Herakles", "Ares", "Kronos", "Minotaurus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0015 }
            Reponses := array{"Thor", "Demeter", "Achilles", "Ra"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0016 }
            Reponses := array{"Ra", "Osiris", "Odysseus", "Hephaistos"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0017 }
            Reponses := array{"Dionysos", "Hades", "Athene", "Medusa"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0018 }
            Reponses := array{"Minotaurus", "Pegasus", "Athene", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0019 }
            Reponses := array{"Dionysos", "Pegasus", "Ra", "Achilles"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0020 }
            Reponses := array{"Thor", "Hephaistos", "Loki", "Dionysos"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0021 }
            Reponses := array{"Pegasus", "Odin", "Artemis", "Hades"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0022 }
            Reponses := array{"Pegasus", "Poseidon", "Loki", "Ares"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0023 }
            Reponses := array{"Pegasus", "Osiris", "Apollon", "Ra"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0024 }
            Reponses := array{"Anubis", "Medusa", "Pegasus", "Hermes"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0025 }
            Reponses := array{"Hephaistos", "Osiris", "Apollon", "Aphrodite"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0026 }
            Reponses := array{"Poseidon", "Kronos", "Athene", "Ares"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0027 }
            Reponses := array{"Persephone", "Horus", "Theseus", "Zyklop"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0028 }
            Reponses := array{"Hestia", "Theseus", "Baldr", "Freyja"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0029 }
            Reponses := array{"Perseus", "Orpheus", "Prometheus", "Theseus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0030 }
            Reponses := array{"Seth", "Theseus", "Zentaur", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0031 }
            Reponses := array{"Jason", "Freyja", "Walkuere", "Zerberus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0032 }
            Reponses := array{"Zentaur", "Ikarus", "Daedalus", "Eros"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0033 }
            Reponses := array{"Walkuere", "Fenrir", "Pandora", "Daedalus"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0034 }
            Reponses := array{"Orpheus", "Bastet", "Walkuere", "Zyklop"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0035 }
            Reponses := array{"Sirene", "Prometheus", "Orpheus", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0036 }
            Reponses := array{"Atlas", "Fenrir", "Pandora", "Ikarus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0037 }
            Reponses := array{"Atlas", "Pandora", "Perseus", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0038 }
            Reponses := array{"Narziss", "Seth", "Isis", "Fenrir"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0039 }
            Reponses := array{"Jason", "Hestia", "Eros", "Fenrir"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0040 }
            Reponses := array{"Theseus", "Narziss", "Eros", "Nike"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0041 }
            Reponses := array{"Zerberus", "Hestia", "Freyja", "Atlas"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0042 }
            Reponses := array{"Horus", "Narziss", "Nike", "Zyklop"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0043 }
            Reponses := array{"Zentaur", "Freyja", "Eros", "Bastet"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0044 }
            Reponses := array{"Theseus", "Sirene", "Freyja", "Isis"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0045 }
            Reponses := array{"Freyja", "Fenrir", "Theseus", "Perseus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0046 }
            Reponses := array{"Daedalus", "Baldr", "Zerberus", "Hestia"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0047 }
            Reponses := array{"Zerberus", "Baldr", "Horus", "Fenrir"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0048 }
            Reponses := array{"Baldr", "Walkuere", "Theseus", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0049 }
            Reponses := array{"Hestia", "Baldr", "Fenrir", "Horus"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0050 }
            Reponses := array{"Nike", "Jason", "Isis", "Zerberus"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0051 }
            Reponses := array{"Prometheus", "Zerberus", "Seth", "Narziss"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0052 }
            Reponses := array{"Fenrir", "Eros", "Bastet", "Hestia"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0053 }
            Reponses := array{"Hel", "Thanatos", "Charon", "Helios"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0054 }
            Reponses := array{"Heimdall", "Anput", "Raijin", "Thot"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0055 }
            Reponses := array{"Jormungandr", "Tyr", "Kali", "Vishnu"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0056 }
            Reponses := array{"Eos", "Brahma", "Mjolnir", "Amaterasu"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0057 }
            Reponses := array{"Jormungandr", "Quetzalcoatl", "Kraken", "Chimaera"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0058 }
            Reponses := array{"Kraken", "Tyr", "Hel", "Vishnu"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0059 }
            Reponses := array{"Tiamat", "Sphinx", "Inanna", "Sobek"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0060 }
            Reponses := array{"Styx", "Shiva", "Chimaera", "Thot"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0061 }
            Reponses := array{"Hydra", "Sphinx", "Anput", "Uranos"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0062 }
            Reponses := array{"Charon", "Uranos", "Helios", "Hypnos"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0063 }
            Reponses := array{"Tiamat", "Chimaera", "Styx", "Hypnos"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0064 }
            Reponses := array{"Helios", "Hydra", "Inanna", "Tartaros"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0065 }
            Reponses := array{"Sphinx", "Gaia", "Heimdall", "Uranos"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0066 }
            Reponses := array{"Uranos", "Kali", "Hypnos", "Tyr"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0067 }
            Reponses := array{"Nemesis", "Eos", "Thot", "Helios"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0068 }
            Reponses := array{"Amaterasu", "Selene", "Hel", "Heimdall"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0069 }
            Reponses := array{"Selene", "Eos", "Quetzalcoatl", "Kraken"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0070 }
            Reponses := array{"Brahma", "Marduk", "Sobek", "Nemesis"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0071 }
            Reponses := array{"Hypnos", "Izanagi", "Selene", "Styx"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0072 }
            Reponses := array{"Anput", "Morpheus", "Uranos", "Thanatos"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0073 }
            Reponses := array{"Jormungandr", "Thanatos", "Charon", "Raijin"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0074 }
            Reponses := array{"Chimaera", "Charon", "Quetzalcoatl", "Sphinx"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0075 }
            Reponses := array{"Nemesis", "Selene", "Helios", "Amaterasu"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0076 }
            Reponses := array{"Raijin", "Kali", "Gaia", "Brahma"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0077 }
            Reponses := array{"Izanagi", "Sphinx", "Gaia", "Heimdall"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0078 }
            Reponses := array{"Ganesha", "Sobek", "Bes", "Hydra"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0079 }
            Reponses := array{"Hypnos", "Thanatos", "Thot", "Eos"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0080 }
            Reponses := array{"Anput", "Raijin", "Helios", "Amaterasu"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0081 }
            Reponses := array{"Quetzalcoatl", "Eos", "Mjolnir", "Bes"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0082 }
            Reponses := array{"Marduk", "Nemesis", "Maat", "Anput"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0083 }
            Reponses := array{"Kali", "Sobek", "Jormungandr", "Vishnu"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0084 }
            Reponses := array{"Mjolnir", "Shiva", "Kali", "Charon"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0085 }
            Reponses := array{"Gaia", "Kraken", "Heimdall", "Ganesha"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0086 }
            Reponses := array{"Kali", "Heimdall", "Morpheus", "Mjolnir"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0087 }
            Reponses := array{"Thot", "Brahma", "Helios", "Inanna"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0088 }
            Reponses := array{"Quetzalcoatl", "Nemesis", "Charon", "Tiamat"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0089 }
            Reponses := array{"Chimaera", "Helios", "Marduk", "Vishnu"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese mythologische Figur?"
            Image := option{ mytho.myt_0090 }
            Reponses := array{"Raijin", "Heimdall", "Izanagi", "Inanna"}
            BonneReponse := 3

MakeMythoQuestionsIT() : []question =
    array:
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0001 }
            Reponses := array{"Zeus", "Apollo", "Efesto", "Ade"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0002 }
            Reponses := array{"Poseidone", "Afrodite", "Era", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0003 }
            Reponses := array{"Medusa", "Ade", "Atena", "Ra"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0004 }
            Reponses := array{"Dioniso", "Era", "Eracle", "Anubis"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0005 }
            Reponses := array{"Atena", "Zeus", "Pegaso", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0006 }
            Reponses := array{"Hermes", "Eracle", "Apollo", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0007 }
            Reponses := array{"Osiris", "Artemide", "Poseidone", "Minotauro"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0008 }
            Reponses := array{"Ade", "Minotauro", "Loki", "Ares"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0009 }
            Reponses := array{"Ares", "Ulisse", "Afrodite", "Osiris"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0010 }
            Reponses := array{"Anubis", "Pegaso", "Hermes", "Achille"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0011 }
            Reponses := array{"Osiris", "Anubis", "Pegaso", "Efesto"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0012 }
            Reponses := array{"Demetra", "Minotauro", "Medusa", "Poseidone"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0013 }
            Reponses := array{"Ra", "Achille", "Poseidone", "Dioniso"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0014 }
            Reponses := array{"Eracle", "Ares", "Crono", "Minotauro"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0015 }
            Reponses := array{"Thor", "Demetra", "Achille", "Ra"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0016 }
            Reponses := array{"Ra", "Osiris", "Ulisse", "Efesto"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0017 }
            Reponses := array{"Dioniso", "Ade", "Atena", "Medusa"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0018 }
            Reponses := array{"Minotauro", "Pegaso", "Atena", "Medusa"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0019 }
            Reponses := array{"Dioniso", "Pegaso", "Ra", "Achille"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0020 }
            Reponses := array{"Thor", "Efesto", "Loki", "Dioniso"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0021 }
            Reponses := array{"Pegaso", "Odin", "Artemide", "Ade"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0022 }
            Reponses := array{"Pegaso", "Poseidone", "Loki", "Ares"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0023 }
            Reponses := array{"Pegaso", "Osiris", "Apollo", "Ra"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0024 }
            Reponses := array{"Anubis", "Medusa", "Pegaso", "Hermes"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0025 }
            Reponses := array{"Efesto", "Osiris", "Apollo", "Afrodite"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0026 }
            Reponses := array{"Poseidone", "Crono", "Atena", "Ares"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0027 }
            Reponses := array{"Persefone", "Horus", "Teseo", "Ciclope"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0028 }
            Reponses := array{"Hestia", "Teseo", "Baldr", "Freyja"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0029 }
            Reponses := array{"Perseo", "Orfeo", "Prometeo", "Teseo"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0030 }
            Reponses := array{"Seth", "Teseo", "Centauro", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0031 }
            Reponses := array{"Giasone", "Freyja", "Valchiria", "Cerbero"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0032 }
            Reponses := array{"Centauro", "Icaro", "Dedalo", "Eros"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0033 }
            Reponses := array{"Valchiria", "Fenrir", "Pandora", "Dedalo"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0034 }
            Reponses := array{"Orfeo", "Bastet", "Valchiria", "Ciclope"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0035 }
            Reponses := array{"Sirena", "Prometeo", "Orfeo", "Freyja"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0036 }
            Reponses := array{"Atlante", "Fenrir", "Pandora", "Icaro"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0037 }
            Reponses := array{"Atlante", "Pandora", "Perseo", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0038 }
            Reponses := array{"Narciso", "Seth", "Isis", "Fenrir"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0039 }
            Reponses := array{"Giasone", "Hestia", "Eros", "Fenrir"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0040 }
            Reponses := array{"Teseo", "Narciso", "Eros", "Nike"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0041 }
            Reponses := array{"Cerbero", "Hestia", "Freyja", "Atlante"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0042 }
            Reponses := array{"Horus", "Narciso", "Nike", "Ciclope"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0043 }
            Reponses := array{"Centauro", "Freyja", "Eros", "Bastet"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0044 }
            Reponses := array{"Teseo", "Sirena", "Freyja", "Isis"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0045 }
            Reponses := array{"Freyja", "Fenrir", "Teseo", "Perseo"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0046 }
            Reponses := array{"Dedalo", "Baldr", "Cerbero", "Hestia"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0047 }
            Reponses := array{"Cerbero", "Baldr", "Horus", "Fenrir"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0048 }
            Reponses := array{"Baldr", "Valchiria", "Teseo", "Bastet"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0049 }
            Reponses := array{"Hestia", "Baldr", "Fenrir", "Horus"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0050 }
            Reponses := array{"Nike", "Giasone", "Isis", "Cerbero"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0051 }
            Reponses := array{"Prometeo", "Cerbero", "Seth", "Narciso"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0052 }
            Reponses := array{"Fenrir", "Eros", "Bastet", "Hestia"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0053 }
            Reponses := array{"Hel", "Thanatos", "Caronte", "Elio"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0054 }
            Reponses := array{"Heimdall", "Anput", "Raijin", "Thot"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0055 }
            Reponses := array{"Jormungandr", "Tyr", "Kali", "Visnu"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0056 }
            Reponses := array{"Eos", "Brahma", "Mjolnir", "Amaterasu"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0057 }
            Reponses := array{"Jormungandr", "Quetzalcoatl", "Kraken", "Chimera"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0058 }
            Reponses := array{"Kraken", "Tyr", "Hel", "Visnu"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0059 }
            Reponses := array{"Tiamat", "Sfinge", "Inanna", "Sobek"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0060 }
            Reponses := array{"Stige", "Shiva", "Chimera", "Thot"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0061 }
            Reponses := array{"Idra", "Sfinge", "Anput", "Urano"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0062 }
            Reponses := array{"Caronte", "Urano", "Elio", "Hypnos"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0063 }
            Reponses := array{"Tiamat", "Chimera", "Stige", "Hypnos"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0064 }
            Reponses := array{"Elio", "Idra", "Inanna", "Tartaro"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0065 }
            Reponses := array{"Sfinge", "Gaia", "Heimdall", "Urano"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0066 }
            Reponses := array{"Urano", "Kali", "Hypnos", "Tyr"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0067 }
            Reponses := array{"Nemesi", "Eos", "Thot", "Elio"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0068 }
            Reponses := array{"Amaterasu", "Selene", "Hel", "Heimdall"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0069 }
            Reponses := array{"Selene", "Eos", "Quetzalcoatl", "Kraken"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0070 }
            Reponses := array{"Brahma", "Marduk", "Sobek", "Nemesi"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0071 }
            Reponses := array{"Hypnos", "Izanagi", "Selene", "Stige"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0072 }
            Reponses := array{"Anput", "Morfeo", "Urano", "Thanatos"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0073 }
            Reponses := array{"Jormungandr", "Thanatos", "Caronte", "Raijin"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0074 }
            Reponses := array{"Chimera", "Caronte", "Quetzalcoatl", "Sfinge"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0075 }
            Reponses := array{"Nemesi", "Selene", "Elio", "Amaterasu"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0076 }
            Reponses := array{"Raijin", "Kali", "Gaia", "Brahma"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0077 }
            Reponses := array{"Izanagi", "Sfinge", "Gaia", "Heimdall"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0078 }
            Reponses := array{"Ganesha", "Sobek", "Bes", "Idra"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0079 }
            Reponses := array{"Hypnos", "Thanatos", "Thot", "Eos"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0080 }
            Reponses := array{"Anput", "Raijin", "Elio", "Amaterasu"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0081 }
            Reponses := array{"Quetzalcoatl", "Eos", "Mjolnir", "Bes"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0082 }
            Reponses := array{"Marduk", "Nemesi", "Maat", "Anput"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0083 }
            Reponses := array{"Kali", "Sobek", "Jormungandr", "Visnu"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0084 }
            Reponses := array{"Mjolnir", "Shiva", "Kali", "Caronte"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0085 }
            Reponses := array{"Gaia", "Kraken", "Heimdall", "Ganesha"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0086 }
            Reponses := array{"Kali", "Heimdall", "Morfeo", "Mjolnir"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0087 }
            Reponses := array{"Thot", "Brahma", "Elio", "Inanna"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0088 }
            Reponses := array{"Quetzalcoatl", "Nemesi", "Caronte", "Tiamat"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0089 }
            Reponses := array{"Chimera", "Elio", "Marduk", "Visnu"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questa figura mitologica?"
            Image := option{ mytho.myt_0090 }
            Reponses := array{"Raijin", "Heimdall", "Izanagi", "Inanna"}
            BonneReponse := 3

MakeMythoQuestions() : []question =
    MakeMythoQuestionsFR()
