using { /Verse.org/Assets }

# persos_bank.verse — Quizz PERSONNAGES HISTORIQUES (portraits Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

PersosDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakePersosQuestionsFR() : []question =
    array:
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0001 }
            Reponses := array{"Napoleon Bonaparte", "Mere Teresa", "Isaac Newton", "Reine Victoria"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0002 }
            Reponses := array{"Thomas Edison", "Ramses II", "Albert Einstein", "Jules Cesar"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0003 }
            Reponses := array{"Abraham Lincoln", "Jules Cesar", "Leonard de Vinci", "Marie-Antoinette"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0004 }
            Reponses := array{"Jules Cesar", "Vincent van Gogh", "Cleopatre", "Galilee"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0005 }
            Reponses := array{"Martin Luther King", "Alexandre le Grand", "Vincent van Gogh", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0006 }
            Reponses := array{"Gandhi", "Leonard de Vinci", "Beethoven", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0007 }
            Reponses := array{"Beethoven", "Nikola Tesla", "Christophe Colomb", "Aristote"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0008 }
            Reponses := array{"Karl Marx", "Toutankhamon", "George Washington", "Charles Darwin"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0009 }
            Reponses := array{"Nelson Mandela", "Abraham Lincoln", "Mozart", "Che Guevara"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0010 }
            Reponses := array{"Nelson Mandela", "Adolf Hitler", "Che Guevara", "Toutankhamon"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0011 }
            Reponses := array{"William Shakespeare", "Abraham Lincoln", "Winston Churchill", "Albert Einstein"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0012 }
            Reponses := array{"Cleopatre", "Charles de Gaulle", "Marie Curie", "Adolf Hitler"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0013 }
            Reponses := array{"John F. Kennedy", "Gandhi", "Beethoven", "Christophe Colomb"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0014 }
            Reponses := array{"Beethoven", "Ramses II", "Mozart", "Nelson Mandela"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0015 }
            Reponses := array{"Socrate", "Martin Luther King", "Charles Darwin", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0016 }
            Reponses := array{"Nikola Tesla", "Nelson Mandela", "Ramses II", "Mere Teresa"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0017 }
            Reponses := array{"Pablo Picasso", "Jeanne d'Arc", "Karl Marx", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0018 }
            Reponses := array{"Louis XIV", "Isaac Newton", "William Shakespeare", "Galilee"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0019 }
            Reponses := array{"Martin Luther King", "Mozart", "Marie-Antoinette", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0020 }
            Reponses := array{"Albert Einstein", "Vincent van Gogh", "Elisabeth II", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0021 }
            Reponses := array{"Marie-Antoinette", "Reine Victoria", "Louis XIV", "Beethoven"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0022 }
            Reponses := array{"William Shakespeare", "Elisabeth II", "Abraham Lincoln", "Aristote"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0023 }
            Reponses := array{"Mozart", "Abraham Lincoln", "Pablo Picasso", "Toutankhamon"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0024 }
            Reponses := array{"Jules Cesar", "Beethoven", "Thomas Edison", "Napoleon Bonaparte"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0025 }
            Reponses := array{"Pablo Picasso", "Reine Victoria", "John F. Kennedy", "Mozart"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0026 }
            Reponses := array{"Vincent van Gogh", "Jules Cesar", "Marie Curie", "Platon"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0027 }
            Reponses := array{"Charles de Gaulle", "Isaac Newton", "Socrate", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0028 }
            Reponses := array{"Napoleon Bonaparte", "Albert Einstein", "Leonard de Vinci", "Galilee"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0029 }
            Reponses := array{"William Shakespeare", "Gengis Khan", "Christophe Colomb", "Charles Darwin"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0030 }
            Reponses := array{"Marie Curie", "Adolf Hitler", "Mere Teresa", "Christophe Colomb"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0031 }
            Reponses := array{"Marie-Antoinette", "Thomas Edison", "Karl Marx", "Aristote"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0032 }
            Reponses := array{"Marie Curie", "Nikola Tesla", "Charles de Gaulle", "Winston Churchill"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0033 }
            Reponses := array{"Socrate", "Napoleon Bonaparte", "Beethoven", "Jules Cesar"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0034 }
            Reponses := array{"Platon", "Jules Cesar", "Charles de Gaulle", "Albert Einstein"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0035 }
            Reponses := array{"Jules Cesar", "Isaac Newton", "Marie Curie", "Aristote"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0036 }
            Reponses := array{"John F. Kennedy", "William Shakespeare", "Aristote", "Gengis Khan"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0037 }
            Reponses := array{"Abraham Lincoln", "Ramses II", "Socrate", "John F. Kennedy"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0038 }
            Reponses := array{"Che Guevara", "Beethoven", "Alexandre le Grand", "Gandhi"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0039 }
            Reponses := array{"Aristote", "Charles de Gaulle", "Jules Cesar", "Karl Marx"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0040 }
            Reponses := array{"Louis XIV", "Elisabeth II", "Toutankhamon", "Beethoven"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0041 }
            Reponses := array{"Gandhi", "Aristote", "Ramses II", "Che Guevara"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0042 }
            Reponses := array{"Attila", "Voltaire", "Copernic", "Magellan"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0043 }
            Reponses := array{"Victor Hugo", "Frida Kahlo", "Charlie Chaplin", "James Cook"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0044 }
            Reponses := array{"Charlie Chaplin", "Moliere", "James Cook", "Staline"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0045 }
            Reponses := array{"Gutenberg", "Claude Monet", "Michel-Ange", "Soliman le Magnifique"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0046 }
            Reponses := array{"Magellan", "Claude Monet", "Frida Kahlo", "Anne Frank"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0047 }
            Reponses := array{"Charlie Chaplin", "Marco Polo", "Charlemagne", "Guillaume le Conquerant"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0048 }
            Reponses := array{"Bismarck", "Voltaire", "Rembrandt", "Vasco de Gama"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0049 }
            Reponses := array{"Amelia Earhart", "Mao Zedong", "Mussolini", "James Cook"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0050 }
            Reponses := array{"Garibaldi", "Hannibal", "Victor Hugo", "Ivan le Terrible"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0051 }
            Reponses := array{"Elisabeth Ire", "Spartacus", "James Cook", "Moliere"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0052 }
            Reponses := array{"Catherine II", "Attila", "Charlemagne", "Franklin D. Roosevelt"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0053 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Simon Bolivar", "Charlemagne"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0054 }
            Reponses := array{"Guillaume le Conquerant", "Vasco de Gama", "Alexander Fleming", "Marco Polo"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0055 }
            Reponses := array{"Guillaume le Conquerant", "Victor Hugo", "Henri VIII", "Rosa Parks"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0056 }
            Reponses := array{"Henry Ford", "Rosa Parks", "Moliere", "Elisabeth Ire"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0057 }
            Reponses := array{"Staline", "Moliere", "Neil Armstrong", "Pierre le Grand"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0058 }
            Reponses := array{"Catherine II", "Simon Bolivar", "Magellan", "Amelia Earhart"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0059 }
            Reponses := array{"Franklin D. Roosevelt", "Ivan le Terrible", "Rosa Parks", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0060 }
            Reponses := array{"Attila", "James Cook", "Copernic", "Bismarck"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0061 }
            Reponses := array{"Hannibal", "Confucius", "Staline", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0062 }
            Reponses := array{"Anne Frank", "Walt Disney", "Lenine", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0063 }
            Reponses := array{"Alexander Fleming", "Mao Zedong", "Moliere", "Neil Armstrong"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0064 }
            Reponses := array{"Moliere", "Franklin D. Roosevelt", "Copernic", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0065 }
            Reponses := array{"Benjamin Franklin", "James Cook", "Alexander Fleming", "Saladin"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0066 }
            Reponses := array{"Lenine", "Neil Armstrong", "Mussolini", "Simon Bolivar"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0067 }
            Reponses := array{"Catherine II", "Rosa Parks", "Bismarck", "Garibaldi"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0068 }
            Reponses := array{"Michel-Ange", "Mussolini", "Sigmund Freud", "Benjamin Franklin"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0069 }
            Reponses := array{"James Cook", "Walt Disney", "Frida Kahlo", "Soliman le Magnifique"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0070 }
            Reponses := array{"Saladin", "Youri Gagarine", "Salvador Dali", "Walt Disney"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0071 }
            Reponses := array{"Claude Monet", "Ivan le Terrible", "Mao Zedong", "Lenine"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0072 }
            Reponses := array{"Rembrandt", "Mao Zedong", "Saladin", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0073 }
            Reponses := array{"Michel-Ange", "Rosa Parks", "Spartacus", "Confucius"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0074 }
            Reponses := array{"Rosa Parks", "Copernic", "Anne Frank", "Henry Ford"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0075 }
            Reponses := array{"Louis Pasteur", "Magellan", "Copernic", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0076 }
            Reponses := array{"Benjamin Franklin", "Henry Ford", "Alexander Fleming", "Michel-Ange"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0077 }
            Reponses := array{"James Cook", "Sigmund Freud", "Hannibal", "Claude Monet"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0078 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Charlie Chaplin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0079 }
            Reponses := array{"James Cook", "Neil Armstrong", "Spartacus", "Amelia Earhart"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0080 }
            Reponses := array{"Ivan le Terrible", "Amelia Earhart", "Bismarck", "Neil Armstrong"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0081 }
            Reponses := array{"Youri Gagarine", "Victor Hugo", "Henri VIII", "Hannibal"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0082 }
            Reponses := array{"Claude Monet", "Elisabeth Ire", "Confucius", "Voltaire"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0083 }
            Reponses := array{"Saladin", "Benjamin Franklin", "Franklin D. Roosevelt", "Gutenberg"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0084 }
            Reponses := array{"James Cook", "Henri VIII", "Soliman le Magnifique", "Attila"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0085 }
            Reponses := array{"Ivan le Terrible", "Anne Frank", "Moliere", "Marco Polo"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0086 }
            Reponses := array{"Rosa Parks", "Voltaire", "Moliere", "Staline"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0087 }
            Reponses := array{"Confucius", "Vasco de Gama", "Walt Disney", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0088 }
            Reponses := array{"Hannibal", "Saladin", "Henry Ford", "Claude Monet"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0089 }
            Reponses := array{"Francisco Pizarro", "Toussaint Louverture", "Vercingetorix", "Danton"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0090 }
            Reponses := array{"Hatchepsout", "Clovis", "Francisco Pizarro", "Emiliano Zapata"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0091 }
            Reponses := array{"Clovis", "Francois-Ferdinand", "Richelieu", "Oda Nobunaga"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0092 }
            Reponses := array{"La Fayette", "Akbar", "Ataturk", "Robespierre"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0093 }
            Reponses := array{"Danton", "La Fayette", "Akbar", "Francois-Ferdinand"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0094 }
            Reponses := array{"Akbar", "La Fayette", "Miyamoto Musashi", "Erik le Rouge"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0095 }
            Reponses := array{"Toussaint Louverture", "Constantin", "Francois-Ferdinand", "Richelieu"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0096 }
            Reponses := array{"Miyamoto Musashi", "Jose de San Martin", "Marc Aurele", "La Fayette"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0097 }
            Reponses := array{"Barbe Noire", "Erik le Rouge", "Patrice Lumumba", "Pancho Villa"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0098 }
            Reponses := array{"Clovis", "Sun Yat-sen", "Emiliano Zapata", "Ashoka"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0099 }
            Reponses := array{"Akbar", "La Fayette", "Ashoka", "Geronimo"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0100 }
            Reponses := array{"Justinien", "Caligula", "Sitting Bull", "Amerigo Vespucci"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0101 }
            Reponses := array{"La Fayette", "Ataturk", "Nicolas II", "Hernan Cortes"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0102 }
            Reponses := array{"Francisco Pizarro", "Barbe Noire", "Haile Selassie", "Gustave Eiffel"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0103 }
            Reponses := array{"Francisco Pizarro", "Geronimo", "Nefertiti", "Amerigo Vespucci"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0104 }
            Reponses := array{"Francis Drake", "Marc Aurele", "Patrice Lumumba", "Caligula"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0105 }
            Reponses := array{"Hernan Cortes", "Trotski", "Hatchepsout", "Barbe Noire"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0106 }
            Reponses := array{"Hatchepsout", "Ferdinand de Lesseps", "Ashoka", "Pancho Villa"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0107 }
            Reponses := array{"Nicolas II", "Miyamoto Musashi", "Erik le Rouge", "Gustave Eiffel"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0108 }
            Reponses := array{"Trotski", "Nefertiti", "Ho Chi Minh", "Hernan Cortes"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0109 }
            Reponses := array{"Nicolas II", "Pancho Villa", "Raspoutine", "Sitting Bull"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0110 }
            Reponses := array{"Hammurabi", "Nicolas II", "Ho Chi Minh", "Patrice Lumumba"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0111 }
            Reponses := array{"Nicolas II", "Francois-Ferdinand", "Haile Selassie", "Hernan Cortes"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0112 }
            Reponses := array{"Danton", "Francis Drake", "Ataturk", "La Fayette"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0113 }
            Reponses := array{"Francisco Pizarro", "Haile Selassie", "Hammurabi", "Miyamoto Musashi"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0114 }
            Reponses := array{"Robespierre", "Cyrus le Grand", "Jose de San Martin", "Patrice Lumumba"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0115 }
            Reponses := array{"Tokugawa Ieyasu", "Clovis", "Ho Chi Minh", "Barbe Noire"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0116 }
            Reponses := array{"Barbe Noire", "Sun Yat-sen", "Francois-Ferdinand", "Richelieu"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0117 }
            Reponses := array{"Francis Drake", "Tokugawa Ieyasu", "Danton", "Constantin"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0118 }
            Reponses := array{"Oda Nobunaga", "Tokugawa Ieyasu", "Toussaint Louverture", "Constantin"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0119 }
            Reponses := array{"Trotski", "Miyamoto Musashi", "Barbe Noire", "Caligula"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0120 }
            Reponses := array{"Akbar", "Danton", "Geronimo", "Hammurabi"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0121 }
            Reponses := array{"Clovis", "Ashoka", "Miyamoto Musashi", "Constantin"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0122 }
            Reponses := array{"Cyrus le Grand", "Leif Erikson", "Nicolas II", "Oda Nobunaga"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0123 }
            Reponses := array{"Geronimo", "Akbar", "Hammurabi", "Emiliano Zapata"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0124 }
            Reponses := array{"Francis Drake", "Erik le Rouge", "Nefertiti", "Francisco Pizarro"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0125 }
            Reponses := array{"Tokugawa Ieyasu", "Gustave Eiffel", "Hammurabi", "Hatchepsout"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0126 }
            Reponses := array{"Ho Chi Minh", "Danton", "Neron", "Haile Selassie"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0127 }
            Reponses := array{"Caligula", "Patrice Lumumba", "Sun Yat-sen", "Jose de San Martin"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0128 }
            Reponses := array{"Hammurabi", "Marc Aurele", "Sitting Bull", "Danton"}
            BonneReponse := 1
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0129 }
            Reponses := array{"Constantin", "Jose de San Martin", "Geronimo", "Clovis"}
            BonneReponse := 0
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0130 }
            Reponses := array{"Akbar", "Sitting Bull", "Justinien", "Hernan Cortes"}
            BonneReponse := 2
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0131 }
            Reponses := array{"Nefertiti", "Oda Nobunaga", "Nicolas II", "Leif Erikson"}
            BonneReponse := 3
        question:
            Enonce := "Qui est ce personnage historique ?"
            Image := option{ persos.his_0132 }
            Reponses := array{"Erik le Rouge", "Clovis", "Vercingetorix", "Pancho Villa"}
            BonneReponse := 0

MakePersosQuestionsEN() : []question =
    array:
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0001 }
            Reponses := array{"Napoleon Bonaparte", "Mother Teresa", "Isaac Newton", "Queen Victoria"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0002 }
            Reponses := array{"Thomas Edison", "Ramesses II", "Albert Einstein", "Julius Caesar"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0003 }
            Reponses := array{"Abraham Lincoln", "Julius Caesar", "Leonardo da Vinci", "Marie Antoinette"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0004 }
            Reponses := array{"Julius Caesar", "Vincent van Gogh", "Cleopatra", "Galileo Galilei"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0005 }
            Reponses := array{"Martin Luther King", "Alexander the Great", "Vincent van Gogh", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0006 }
            Reponses := array{"Gandhi", "Leonardo da Vinci", "Beethoven", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0007 }
            Reponses := array{"Beethoven", "Nikola Tesla", "Christopher Columbus", "Aristotle"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0008 }
            Reponses := array{"Karl Marx", "Tutankhamun", "George Washington", "Charles Darwin"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0009 }
            Reponses := array{"Nelson Mandela", "Abraham Lincoln", "Mozart", "Che Guevara"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0010 }
            Reponses := array{"Nelson Mandela", "Adolf Hitler", "Che Guevara", "Tutankhamun"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0011 }
            Reponses := array{"William Shakespeare", "Abraham Lincoln", "Winston Churchill", "Albert Einstein"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0012 }
            Reponses := array{"Cleopatra", "Charles de Gaulle", "Marie Curie", "Adolf Hitler"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0013 }
            Reponses := array{"John F. Kennedy", "Gandhi", "Beethoven", "Christopher Columbus"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0014 }
            Reponses := array{"Beethoven", "Ramesses II", "Mozart", "Nelson Mandela"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0015 }
            Reponses := array{"Socrates", "Martin Luther King", "Charles Darwin", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0016 }
            Reponses := array{"Nikola Tesla", "Nelson Mandela", "Ramesses II", "Mother Teresa"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0017 }
            Reponses := array{"Pablo Picasso", "Joan of Arc", "Karl Marx", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0018 }
            Reponses := array{"Louis XIV", "Isaac Newton", "William Shakespeare", "Galileo Galilei"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0019 }
            Reponses := array{"Martin Luther King", "Mozart", "Marie Antoinette", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0020 }
            Reponses := array{"Albert Einstein", "Vincent van Gogh", "Elizabeth II", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0021 }
            Reponses := array{"Marie Antoinette", "Queen Victoria", "Louis XIV", "Beethoven"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0022 }
            Reponses := array{"William Shakespeare", "Elizabeth II", "Abraham Lincoln", "Aristotle"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0023 }
            Reponses := array{"Mozart", "Abraham Lincoln", "Pablo Picasso", "Tutankhamun"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0024 }
            Reponses := array{"Julius Caesar", "Beethoven", "Thomas Edison", "Napoleon Bonaparte"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0025 }
            Reponses := array{"Pablo Picasso", "Queen Victoria", "John F. Kennedy", "Mozart"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0026 }
            Reponses := array{"Vincent van Gogh", "Julius Caesar", "Marie Curie", "Plato"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0027 }
            Reponses := array{"Charles de Gaulle", "Isaac Newton", "Socrates", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0028 }
            Reponses := array{"Napoleon Bonaparte", "Albert Einstein", "Leonardo da Vinci", "Galileo Galilei"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0029 }
            Reponses := array{"William Shakespeare", "Genghis Khan", "Christopher Columbus", "Charles Darwin"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0030 }
            Reponses := array{"Marie Curie", "Adolf Hitler", "Mother Teresa", "Christopher Columbus"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0031 }
            Reponses := array{"Marie Antoinette", "Thomas Edison", "Karl Marx", "Aristotle"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0032 }
            Reponses := array{"Marie Curie", "Nikola Tesla", "Charles de Gaulle", "Winston Churchill"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0033 }
            Reponses := array{"Socrates", "Napoleon Bonaparte", "Beethoven", "Julius Caesar"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0034 }
            Reponses := array{"Plato", "Julius Caesar", "Charles de Gaulle", "Albert Einstein"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0035 }
            Reponses := array{"Julius Caesar", "Isaac Newton", "Marie Curie", "Aristotle"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0036 }
            Reponses := array{"John F. Kennedy", "William Shakespeare", "Aristotle", "Genghis Khan"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0037 }
            Reponses := array{"Abraham Lincoln", "Ramesses II", "Socrates", "John F. Kennedy"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0038 }
            Reponses := array{"Che Guevara", "Beethoven", "Alexander the Great", "Gandhi"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0039 }
            Reponses := array{"Aristotle", "Charles de Gaulle", "Julius Caesar", "Karl Marx"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0040 }
            Reponses := array{"Louis XIV", "Elizabeth II", "Tutankhamun", "Beethoven"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0041 }
            Reponses := array{"Gandhi", "Aristotle", "Ramesses II", "Che Guevara"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0042 }
            Reponses := array{"Attila", "Voltaire", "Copernicus", "Ferdinand Magellan"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0043 }
            Reponses := array{"Victor Hugo", "Frida Kahlo", "Charlie Chaplin", "James Cook"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0044 }
            Reponses := array{"Charlie Chaplin", "Moliere", "James Cook", "Joseph Stalin"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0045 }
            Reponses := array{"Gutenberg", "Claude Monet", "Michelangelo", "Suleiman the Magnificent"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0046 }
            Reponses := array{"Ferdinand Magellan", "Claude Monet", "Frida Kahlo", "Anne Frank"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0047 }
            Reponses := array{"Charlie Chaplin", "Marco Polo", "Charlemagne", "William the Conqueror"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0048 }
            Reponses := array{"Bismarck", "Voltaire", "Rembrandt", "Vasco da Gama"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0049 }
            Reponses := array{"Amelia Earhart", "Mao Zedong", "Mussolini", "James Cook"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0050 }
            Reponses := array{"Garibaldi", "Hannibal", "Victor Hugo", "Ivan the Terrible"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0051 }
            Reponses := array{"Elizabeth I", "Spartacus", "James Cook", "Moliere"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0052 }
            Reponses := array{"Catherine the Great", "Attila", "Charlemagne", "Franklin D. Roosevelt"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0053 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Simon Bolivar", "Charlemagne"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0054 }
            Reponses := array{"William the Conqueror", "Vasco da Gama", "Alexander Fleming", "Marco Polo"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0055 }
            Reponses := array{"William the Conqueror", "Victor Hugo", "Henry VIII", "Rosa Parks"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0056 }
            Reponses := array{"Henry Ford", "Rosa Parks", "Moliere", "Elizabeth I"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0057 }
            Reponses := array{"Joseph Stalin", "Moliere", "Neil Armstrong", "Peter the Great"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0058 }
            Reponses := array{"Catherine the Great", "Simon Bolivar", "Ferdinand Magellan", "Amelia Earhart"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0059 }
            Reponses := array{"Franklin D. Roosevelt", "Ivan the Terrible", "Rosa Parks", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0060 }
            Reponses := array{"Attila", "James Cook", "Copernicus", "Bismarck"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0061 }
            Reponses := array{"Hannibal", "Confucius", "Joseph Stalin", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0062 }
            Reponses := array{"Anne Frank", "Walt Disney", "Lenin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0063 }
            Reponses := array{"Alexander Fleming", "Mao Zedong", "Moliere", "Neil Armstrong"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0064 }
            Reponses := array{"Moliere", "Franklin D. Roosevelt", "Copernicus", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0065 }
            Reponses := array{"Benjamin Franklin", "James Cook", "Alexander Fleming", "Saladin"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0066 }
            Reponses := array{"Lenin", "Neil Armstrong", "Mussolini", "Simon Bolivar"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0067 }
            Reponses := array{"Catherine the Great", "Rosa Parks", "Bismarck", "Garibaldi"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0068 }
            Reponses := array{"Michelangelo", "Mussolini", "Sigmund Freud", "Benjamin Franklin"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0069 }
            Reponses := array{"James Cook", "Walt Disney", "Frida Kahlo", "Suleiman the Magnificent"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0070 }
            Reponses := array{"Saladin", "Yuri Gagarin", "Salvador Dali", "Walt Disney"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0071 }
            Reponses := array{"Claude Monet", "Ivan the Terrible", "Mao Zedong", "Lenin"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0072 }
            Reponses := array{"Rembrandt", "Mao Zedong", "Saladin", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0073 }
            Reponses := array{"Michelangelo", "Rosa Parks", "Spartacus", "Confucius"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0074 }
            Reponses := array{"Rosa Parks", "Copernicus", "Anne Frank", "Henry Ford"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0075 }
            Reponses := array{"Louis Pasteur", "Ferdinand Magellan", "Copernicus", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0076 }
            Reponses := array{"Benjamin Franklin", "Henry Ford", "Alexander Fleming", "Michelangelo"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0077 }
            Reponses := array{"James Cook", "Sigmund Freud", "Hannibal", "Claude Monet"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0078 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Charlie Chaplin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0079 }
            Reponses := array{"James Cook", "Neil Armstrong", "Spartacus", "Amelia Earhart"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0080 }
            Reponses := array{"Ivan the Terrible", "Amelia Earhart", "Bismarck", "Neil Armstrong"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0081 }
            Reponses := array{"Yuri Gagarin", "Victor Hugo", "Henry VIII", "Hannibal"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0082 }
            Reponses := array{"Claude Monet", "Elizabeth I", "Confucius", "Voltaire"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0083 }
            Reponses := array{"Saladin", "Benjamin Franklin", "Franklin D. Roosevelt", "Gutenberg"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0084 }
            Reponses := array{"James Cook", "Henry VIII", "Suleiman the Magnificent", "Attila"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0085 }
            Reponses := array{"Ivan the Terrible", "Anne Frank", "Moliere", "Marco Polo"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0086 }
            Reponses := array{"Rosa Parks", "Voltaire", "Moliere", "Joseph Stalin"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0087 }
            Reponses := array{"Confucius", "Vasco da Gama", "Walt Disney", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0088 }
            Reponses := array{"Hannibal", "Saladin", "Henry Ford", "Claude Monet"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0089 }
            Reponses := array{"Francisco Pizarro", "Toussaint Louverture", "Vercingetorix", "Danton"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0090 }
            Reponses := array{"Hatshepsut", "Clovis", "Francisco Pizarro", "Emiliano Zapata"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0091 }
            Reponses := array{"Clovis", "Franz Ferdinand", "Richelieu", "Oda Nobunaga"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0092 }
            Reponses := array{"Lafayette", "Akbar", "Ataturk", "Robespierre"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0093 }
            Reponses := array{"Danton", "Lafayette", "Akbar", "Franz Ferdinand"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0094 }
            Reponses := array{"Akbar", "Lafayette", "Miyamoto Musashi", "Erik the Red"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0095 }
            Reponses := array{"Toussaint Louverture", "Constantine", "Franz Ferdinand", "Richelieu"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0096 }
            Reponses := array{"Miyamoto Musashi", "Jose de San Martin", "Marcus Aurelius", "Lafayette"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0097 }
            Reponses := array{"Blackbeard", "Erik the Red", "Patrice Lumumba", "Pancho Villa"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0098 }
            Reponses := array{"Clovis", "Sun Yat-sen", "Emiliano Zapata", "Ashoka"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0099 }
            Reponses := array{"Akbar", "Lafayette", "Ashoka", "Geronimo"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0100 }
            Reponses := array{"Justinian", "Caligula", "Sitting Bull", "Amerigo Vespucci"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0101 }
            Reponses := array{"Lafayette", "Ataturk", "Nicholas II", "Hernan Cortes"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0102 }
            Reponses := array{"Francisco Pizarro", "Blackbeard", "Haile Selassie", "Gustave Eiffel"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0103 }
            Reponses := array{"Francisco Pizarro", "Geronimo", "Nefertiti", "Amerigo Vespucci"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0104 }
            Reponses := array{"Francis Drake", "Marcus Aurelius", "Patrice Lumumba", "Caligula"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0105 }
            Reponses := array{"Hernan Cortes", "Trotsky", "Hatshepsut", "Blackbeard"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0106 }
            Reponses := array{"Hatshepsut", "Ferdinand de Lesseps", "Ashoka", "Pancho Villa"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0107 }
            Reponses := array{"Nicholas II", "Miyamoto Musashi", "Erik the Red", "Gustave Eiffel"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0108 }
            Reponses := array{"Trotsky", "Nefertiti", "Ho Chi Minh", "Hernan Cortes"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0109 }
            Reponses := array{"Nicholas II", "Pancho Villa", "Rasputin", "Sitting Bull"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0110 }
            Reponses := array{"Hammurabi", "Nicholas II", "Ho Chi Minh", "Patrice Lumumba"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0111 }
            Reponses := array{"Nicholas II", "Franz Ferdinand", "Haile Selassie", "Hernan Cortes"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0112 }
            Reponses := array{"Danton", "Francis Drake", "Ataturk", "Lafayette"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0113 }
            Reponses := array{"Francisco Pizarro", "Haile Selassie", "Hammurabi", "Miyamoto Musashi"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0114 }
            Reponses := array{"Robespierre", "Cyrus the Great", "Jose de San Martin", "Patrice Lumumba"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0115 }
            Reponses := array{"Tokugawa Ieyasu", "Clovis", "Ho Chi Minh", "Blackbeard"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0116 }
            Reponses := array{"Blackbeard", "Sun Yat-sen", "Franz Ferdinand", "Richelieu"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0117 }
            Reponses := array{"Francis Drake", "Tokugawa Ieyasu", "Danton", "Constantine"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0118 }
            Reponses := array{"Oda Nobunaga", "Tokugawa Ieyasu", "Toussaint Louverture", "Constantine"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0119 }
            Reponses := array{"Trotsky", "Miyamoto Musashi", "Blackbeard", "Caligula"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0120 }
            Reponses := array{"Akbar", "Danton", "Geronimo", "Hammurabi"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0121 }
            Reponses := array{"Clovis", "Ashoka", "Miyamoto Musashi", "Constantine"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0122 }
            Reponses := array{"Cyrus the Great", "Leif Erikson", "Nicholas II", "Oda Nobunaga"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0123 }
            Reponses := array{"Geronimo", "Akbar", "Hammurabi", "Emiliano Zapata"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0124 }
            Reponses := array{"Francis Drake", "Erik the Red", "Nefertiti", "Francisco Pizarro"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0125 }
            Reponses := array{"Tokugawa Ieyasu", "Gustave Eiffel", "Hammurabi", "Hatshepsut"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0126 }
            Reponses := array{"Ho Chi Minh", "Danton", "Nero", "Haile Selassie"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0127 }
            Reponses := array{"Caligula", "Patrice Lumumba", "Sun Yat-sen", "Jose de San Martin"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0128 }
            Reponses := array{"Hammurabi", "Marcus Aurelius", "Sitting Bull", "Danton"}
            BonneReponse := 1
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0129 }
            Reponses := array{"Constantine", "Jose de San Martin", "Geronimo", "Clovis"}
            BonneReponse := 0
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0130 }
            Reponses := array{"Akbar", "Sitting Bull", "Justinian", "Hernan Cortes"}
            BonneReponse := 2
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0131 }
            Reponses := array{"Nefertiti", "Oda Nobunaga", "Nicholas II", "Leif Erikson"}
            BonneReponse := 3
        question:
            Enonce := "Who is this historical figure?"
            Image := option{ persos.his_0132 }
            Reponses := array{"Erik the Red", "Clovis", "Vercingetorix", "Pancho Villa"}
            BonneReponse := 0

MakePersosQuestionsES() : []question =
    array:
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0001 }
            Reponses := array{"Napoleon Bonaparte", "Madre Teresa", "Isaac Newton", "Reina Victoria"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0002 }
            Reponses := array{"Thomas Edison", "Ramses II", "Albert Einstein", "Julio Cesar"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0003 }
            Reponses := array{"Abraham Lincoln", "Julio Cesar", "Leonardo da Vinci", "Maria Antonieta"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0004 }
            Reponses := array{"Julio Cesar", "Vincent van Gogh", "Cleopatra", "Galileo Galilei"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0005 }
            Reponses := array{"Martin Luther King", "Alejandro Magno", "Vincent van Gogh", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0006 }
            Reponses := array{"Gandhi", "Leonardo da Vinci", "Beethoven", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0007 }
            Reponses := array{"Beethoven", "Nikola Tesla", "Cristobal Colon", "Aristoteles"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0008 }
            Reponses := array{"Karl Marx", "Tutankamon", "George Washington", "Charles Darwin"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0009 }
            Reponses := array{"Nelson Mandela", "Abraham Lincoln", "Mozart", "Che Guevara"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0010 }
            Reponses := array{"Nelson Mandela", "Adolf Hitler", "Che Guevara", "Tutankamon"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0011 }
            Reponses := array{"William Shakespeare", "Abraham Lincoln", "Winston Churchill", "Albert Einstein"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0012 }
            Reponses := array{"Cleopatra", "Charles de Gaulle", "Marie Curie", "Adolf Hitler"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0013 }
            Reponses := array{"John F. Kennedy", "Gandhi", "Beethoven", "Cristobal Colon"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0014 }
            Reponses := array{"Beethoven", "Ramses II", "Mozart", "Nelson Mandela"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0015 }
            Reponses := array{"Socrates", "Martin Luther King", "Charles Darwin", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0016 }
            Reponses := array{"Nikola Tesla", "Nelson Mandela", "Ramses II", "Madre Teresa"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0017 }
            Reponses := array{"Pablo Picasso", "Juana de Arco", "Karl Marx", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0018 }
            Reponses := array{"Luis XIV", "Isaac Newton", "William Shakespeare", "Galileo Galilei"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0019 }
            Reponses := array{"Martin Luther King", "Mozart", "Maria Antonieta", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0020 }
            Reponses := array{"Albert Einstein", "Vincent van Gogh", "Isabel II", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0021 }
            Reponses := array{"Maria Antonieta", "Reina Victoria", "Luis XIV", "Beethoven"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0022 }
            Reponses := array{"William Shakespeare", "Isabel II", "Abraham Lincoln", "Aristoteles"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0023 }
            Reponses := array{"Mozart", "Abraham Lincoln", "Pablo Picasso", "Tutankamon"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0024 }
            Reponses := array{"Julio Cesar", "Beethoven", "Thomas Edison", "Napoleon Bonaparte"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0025 }
            Reponses := array{"Pablo Picasso", "Reina Victoria", "John F. Kennedy", "Mozart"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0026 }
            Reponses := array{"Vincent van Gogh", "Julio Cesar", "Marie Curie", "Platon"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0027 }
            Reponses := array{"Charles de Gaulle", "Isaac Newton", "Socrates", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0028 }
            Reponses := array{"Napoleon Bonaparte", "Albert Einstein", "Leonardo da Vinci", "Galileo Galilei"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0029 }
            Reponses := array{"William Shakespeare", "Gengis Kan", "Cristobal Colon", "Charles Darwin"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0030 }
            Reponses := array{"Marie Curie", "Adolf Hitler", "Madre Teresa", "Cristobal Colon"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0031 }
            Reponses := array{"Maria Antonieta", "Thomas Edison", "Karl Marx", "Aristoteles"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0032 }
            Reponses := array{"Marie Curie", "Nikola Tesla", "Charles de Gaulle", "Winston Churchill"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0033 }
            Reponses := array{"Socrates", "Napoleon Bonaparte", "Beethoven", "Julio Cesar"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0034 }
            Reponses := array{"Platon", "Julio Cesar", "Charles de Gaulle", "Albert Einstein"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0035 }
            Reponses := array{"Julio Cesar", "Isaac Newton", "Marie Curie", "Aristoteles"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0036 }
            Reponses := array{"John F. Kennedy", "William Shakespeare", "Aristoteles", "Gengis Kan"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0037 }
            Reponses := array{"Abraham Lincoln", "Ramses II", "Socrates", "John F. Kennedy"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0038 }
            Reponses := array{"Che Guevara", "Beethoven", "Alejandro Magno", "Gandhi"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0039 }
            Reponses := array{"Aristoteles", "Charles de Gaulle", "Julio Cesar", "Karl Marx"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0040 }
            Reponses := array{"Luis XIV", "Isabel II", "Tutankamon", "Beethoven"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0041 }
            Reponses := array{"Gandhi", "Aristoteles", "Ramses II", "Che Guevara"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0042 }
            Reponses := array{"Atila", "Voltaire", "Copernico", "Fernando de Magallanes"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0043 }
            Reponses := array{"Victor Hugo", "Frida Kahlo", "Charlie Chaplin", "James Cook"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0044 }
            Reponses := array{"Charlie Chaplin", "Moliere", "James Cook", "Stalin"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0045 }
            Reponses := array{"Gutenberg", "Claude Monet", "Miguel Angel", "Suleiman el Magnifico"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0046 }
            Reponses := array{"Fernando de Magallanes", "Claude Monet", "Frida Kahlo", "Anne Frank"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0047 }
            Reponses := array{"Charlie Chaplin", "Marco Polo", "Carlomagno", "Guillermo el Conquistador"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0048 }
            Reponses := array{"Bismarck", "Voltaire", "Rembrandt", "Vasco da Gama"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0049 }
            Reponses := array{"Amelia Earhart", "Mao Zedong", "Mussolini", "James Cook"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0050 }
            Reponses := array{"Garibaldi", "Anibal", "Victor Hugo", "Ivan el Terrible"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0051 }
            Reponses := array{"Isabel I", "Espartaco", "James Cook", "Moliere"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0052 }
            Reponses := array{"Catalina la Grande", "Atila", "Carlomagno", "Franklin D. Roosevelt"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0053 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Simon Bolivar", "Carlomagno"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0054 }
            Reponses := array{"Guillermo el Conquistador", "Vasco da Gama", "Alexander Fleming", "Marco Polo"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0055 }
            Reponses := array{"Guillermo el Conquistador", "Victor Hugo", "Enrique VIII", "Rosa Parks"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0056 }
            Reponses := array{"Henry Ford", "Rosa Parks", "Moliere", "Isabel I"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0057 }
            Reponses := array{"Stalin", "Moliere", "Neil Armstrong", "Pedro el Grande"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0058 }
            Reponses := array{"Catalina la Grande", "Simon Bolivar", "Fernando de Magallanes", "Amelia Earhart"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0059 }
            Reponses := array{"Franklin D. Roosevelt", "Ivan el Terrible", "Rosa Parks", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0060 }
            Reponses := array{"Atila", "James Cook", "Copernico", "Bismarck"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0061 }
            Reponses := array{"Anibal", "Confucio", "Stalin", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0062 }
            Reponses := array{"Anne Frank", "Walt Disney", "Lenin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0063 }
            Reponses := array{"Alexander Fleming", "Mao Zedong", "Moliere", "Neil Armstrong"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0064 }
            Reponses := array{"Moliere", "Franklin D. Roosevelt", "Copernico", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0065 }
            Reponses := array{"Benjamin Franklin", "James Cook", "Alexander Fleming", "Saladino"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0066 }
            Reponses := array{"Lenin", "Neil Armstrong", "Mussolini", "Simon Bolivar"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0067 }
            Reponses := array{"Catalina la Grande", "Rosa Parks", "Bismarck", "Garibaldi"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0068 }
            Reponses := array{"Miguel Angel", "Mussolini", "Sigmund Freud", "Benjamin Franklin"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0069 }
            Reponses := array{"James Cook", "Walt Disney", "Frida Kahlo", "Suleiman el Magnifico"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0070 }
            Reponses := array{"Saladino", "Yuri Gagarin", "Salvador Dali", "Walt Disney"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0071 }
            Reponses := array{"Claude Monet", "Ivan el Terrible", "Mao Zedong", "Lenin"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0072 }
            Reponses := array{"Rembrandt", "Mao Zedong", "Saladino", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0073 }
            Reponses := array{"Miguel Angel", "Rosa Parks", "Espartaco", "Confucio"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0074 }
            Reponses := array{"Rosa Parks", "Copernico", "Anne Frank", "Henry Ford"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0075 }
            Reponses := array{"Louis Pasteur", "Fernando de Magallanes", "Copernico", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0076 }
            Reponses := array{"Benjamin Franklin", "Henry Ford", "Alexander Fleming", "Miguel Angel"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0077 }
            Reponses := array{"James Cook", "Sigmund Freud", "Anibal", "Claude Monet"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0078 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Charlie Chaplin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0079 }
            Reponses := array{"James Cook", "Neil Armstrong", "Espartaco", "Amelia Earhart"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0080 }
            Reponses := array{"Ivan el Terrible", "Amelia Earhart", "Bismarck", "Neil Armstrong"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0081 }
            Reponses := array{"Yuri Gagarin", "Victor Hugo", "Enrique VIII", "Anibal"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0082 }
            Reponses := array{"Claude Monet", "Isabel I", "Confucio", "Voltaire"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0083 }
            Reponses := array{"Saladino", "Benjamin Franklin", "Franklin D. Roosevelt", "Gutenberg"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0084 }
            Reponses := array{"James Cook", "Enrique VIII", "Suleiman el Magnifico", "Atila"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0085 }
            Reponses := array{"Ivan el Terrible", "Anne Frank", "Moliere", "Marco Polo"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0086 }
            Reponses := array{"Rosa Parks", "Voltaire", "Moliere", "Stalin"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0087 }
            Reponses := array{"Confucio", "Vasco da Gama", "Walt Disney", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0088 }
            Reponses := array{"Anibal", "Saladino", "Henry Ford", "Claude Monet"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0089 }
            Reponses := array{"Francisco Pizarro", "Toussaint Louverture", "Vercingetorix", "Danton"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0090 }
            Reponses := array{"Hatshepsut", "Clodoveo", "Francisco Pizarro", "Emiliano Zapata"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0091 }
            Reponses := array{"Clodoveo", "Francisco Fernando", "Richelieu", "Oda Nobunaga"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0092 }
            Reponses := array{"Lafayette", "Akbar", "Ataturk", "Robespierre"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0093 }
            Reponses := array{"Danton", "Lafayette", "Akbar", "Francisco Fernando"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0094 }
            Reponses := array{"Akbar", "Lafayette", "Miyamoto Musashi", "Erik el Rojo"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0095 }
            Reponses := array{"Toussaint Louverture", "Constantino", "Francisco Fernando", "Richelieu"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0096 }
            Reponses := array{"Miyamoto Musashi", "Jose de San Martin", "Marco Aurelio", "Lafayette"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0097 }
            Reponses := array{"Barbanegra", "Erik el Rojo", "Patrice Lumumba", "Pancho Villa"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0098 }
            Reponses := array{"Clodoveo", "Sun Yat-sen", "Emiliano Zapata", "Asoka"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0099 }
            Reponses := array{"Akbar", "Lafayette", "Asoka", "Geronimo"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0100 }
            Reponses := array{"Justiniano", "Caligula", "Sitting Bull", "Amerigo Vespucci"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0101 }
            Reponses := array{"Lafayette", "Ataturk", "Nicolas II", "Hernan Cortes"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0102 }
            Reponses := array{"Francisco Pizarro", "Barbanegra", "Haile Selassie", "Gustave Eiffel"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0103 }
            Reponses := array{"Francisco Pizarro", "Geronimo", "Nefertiti", "Amerigo Vespucci"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0104 }
            Reponses := array{"Francis Drake", "Marco Aurelio", "Patrice Lumumba", "Caligula"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0105 }
            Reponses := array{"Hernan Cortes", "Trotski", "Hatshepsut", "Barbanegra"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0106 }
            Reponses := array{"Hatshepsut", "Ferdinand de Lesseps", "Asoka", "Pancho Villa"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0107 }
            Reponses := array{"Nicolas II", "Miyamoto Musashi", "Erik el Rojo", "Gustave Eiffel"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0108 }
            Reponses := array{"Trotski", "Nefertiti", "Ho Chi Minh", "Hernan Cortes"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0109 }
            Reponses := array{"Nicolas II", "Pancho Villa", "Rasputin", "Sitting Bull"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0110 }
            Reponses := array{"Hammurabi", "Nicolas II", "Ho Chi Minh", "Patrice Lumumba"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0111 }
            Reponses := array{"Nicolas II", "Francisco Fernando", "Haile Selassie", "Hernan Cortes"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0112 }
            Reponses := array{"Danton", "Francis Drake", "Ataturk", "Lafayette"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0113 }
            Reponses := array{"Francisco Pizarro", "Haile Selassie", "Hammurabi", "Miyamoto Musashi"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0114 }
            Reponses := array{"Robespierre", "Ciro el Grande", "Jose de San Martin", "Patrice Lumumba"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0115 }
            Reponses := array{"Tokugawa Ieyasu", "Clodoveo", "Ho Chi Minh", "Barbanegra"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0116 }
            Reponses := array{"Barbanegra", "Sun Yat-sen", "Francisco Fernando", "Richelieu"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0117 }
            Reponses := array{"Francis Drake", "Tokugawa Ieyasu", "Danton", "Constantino"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0118 }
            Reponses := array{"Oda Nobunaga", "Tokugawa Ieyasu", "Toussaint Louverture", "Constantino"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0119 }
            Reponses := array{"Trotski", "Miyamoto Musashi", "Barbanegra", "Caligula"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0120 }
            Reponses := array{"Akbar", "Danton", "Geronimo", "Hammurabi"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0121 }
            Reponses := array{"Clodoveo", "Asoka", "Miyamoto Musashi", "Constantino"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0122 }
            Reponses := array{"Ciro el Grande", "Leif Erikson", "Nicolas II", "Oda Nobunaga"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0123 }
            Reponses := array{"Geronimo", "Akbar", "Hammurabi", "Emiliano Zapata"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0124 }
            Reponses := array{"Francis Drake", "Erik el Rojo", "Nefertiti", "Francisco Pizarro"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0125 }
            Reponses := array{"Tokugawa Ieyasu", "Gustave Eiffel", "Hammurabi", "Hatshepsut"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0126 }
            Reponses := array{"Ho Chi Minh", "Danton", "Neron", "Haile Selassie"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0127 }
            Reponses := array{"Caligula", "Patrice Lumumba", "Sun Yat-sen", "Jose de San Martin"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0128 }
            Reponses := array{"Hammurabi", "Marco Aurelio", "Sitting Bull", "Danton"}
            BonneReponse := 1
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0129 }
            Reponses := array{"Constantino", "Jose de San Martin", "Geronimo", "Clodoveo"}
            BonneReponse := 0
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0130 }
            Reponses := array{"Akbar", "Sitting Bull", "Justiniano", "Hernan Cortes"}
            BonneReponse := 2
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0131 }
            Reponses := array{"Nefertiti", "Oda Nobunaga", "Nicolas II", "Leif Erikson"}
            BonneReponse := 3
        question:
            Enonce := "Quien es este personaje historico?"
            Image := option{ persos.his_0132 }
            Reponses := array{"Erik el Rojo", "Clodoveo", "Vercingetorix", "Pancho Villa"}
            BonneReponse := 0

MakePersosQuestionsDE() : []question =
    array:
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0001 }
            Reponses := array{"Napoleon Bonaparte", "Mutter Teresa", "Isaac Newton", "Koenigin Victoria"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0002 }
            Reponses := array{"Thomas Edison", "Ramses II", "Albert Einstein", "Julius Caesar"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0003 }
            Reponses := array{"Abraham Lincoln", "Julius Caesar", "Leonardo da Vinci", "Marie Antoinette"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0004 }
            Reponses := array{"Julius Caesar", "Vincent van Gogh", "Kleopatra", "Galileo Galilei"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0005 }
            Reponses := array{"Martin Luther King", "Alexander der Grosse", "Vincent van Gogh", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0006 }
            Reponses := array{"Gandhi", "Leonardo da Vinci", "Beethoven", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0007 }
            Reponses := array{"Beethoven", "Nikola Tesla", "Christoph Kolumbus", "Aristoteles"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0008 }
            Reponses := array{"Karl Marx", "Tutanchamun", "George Washington", "Charles Darwin"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0009 }
            Reponses := array{"Nelson Mandela", "Abraham Lincoln", "Mozart", "Che Guevara"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0010 }
            Reponses := array{"Nelson Mandela", "Adolf Hitler", "Che Guevara", "Tutanchamun"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0011 }
            Reponses := array{"William Shakespeare", "Abraham Lincoln", "Winston Churchill", "Albert Einstein"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0012 }
            Reponses := array{"Kleopatra", "Charles de Gaulle", "Marie Curie", "Adolf Hitler"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0013 }
            Reponses := array{"John F. Kennedy", "Gandhi", "Beethoven", "Christoph Kolumbus"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0014 }
            Reponses := array{"Beethoven", "Ramses II", "Mozart", "Nelson Mandela"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0015 }
            Reponses := array{"Sokrates", "Martin Luther King", "Charles Darwin", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0016 }
            Reponses := array{"Nikola Tesla", "Nelson Mandela", "Ramses II", "Mutter Teresa"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0017 }
            Reponses := array{"Pablo Picasso", "Johanna von Orleans", "Karl Marx", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0018 }
            Reponses := array{"Ludwig XIV", "Isaac Newton", "William Shakespeare", "Galileo Galilei"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0019 }
            Reponses := array{"Martin Luther King", "Mozart", "Marie Antoinette", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0020 }
            Reponses := array{"Albert Einstein", "Vincent van Gogh", "Elisabeth II", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0021 }
            Reponses := array{"Marie Antoinette", "Koenigin Victoria", "Ludwig XIV", "Beethoven"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0022 }
            Reponses := array{"William Shakespeare", "Elisabeth II", "Abraham Lincoln", "Aristoteles"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0023 }
            Reponses := array{"Mozart", "Abraham Lincoln", "Pablo Picasso", "Tutanchamun"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0024 }
            Reponses := array{"Julius Caesar", "Beethoven", "Thomas Edison", "Napoleon Bonaparte"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0025 }
            Reponses := array{"Pablo Picasso", "Koenigin Victoria", "John F. Kennedy", "Mozart"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0026 }
            Reponses := array{"Vincent van Gogh", "Julius Caesar", "Marie Curie", "Platon"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0027 }
            Reponses := array{"Charles de Gaulle", "Isaac Newton", "Sokrates", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0028 }
            Reponses := array{"Napoleon Bonaparte", "Albert Einstein", "Leonardo da Vinci", "Galileo Galilei"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0029 }
            Reponses := array{"William Shakespeare", "Dschingis Khan", "Christoph Kolumbus", "Charles Darwin"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0030 }
            Reponses := array{"Marie Curie", "Adolf Hitler", "Mutter Teresa", "Christoph Kolumbus"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0031 }
            Reponses := array{"Marie Antoinette", "Thomas Edison", "Karl Marx", "Aristoteles"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0032 }
            Reponses := array{"Marie Curie", "Nikola Tesla", "Charles de Gaulle", "Winston Churchill"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0033 }
            Reponses := array{"Sokrates", "Napoleon Bonaparte", "Beethoven", "Julius Caesar"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0034 }
            Reponses := array{"Platon", "Julius Caesar", "Charles de Gaulle", "Albert Einstein"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0035 }
            Reponses := array{"Julius Caesar", "Isaac Newton", "Marie Curie", "Aristoteles"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0036 }
            Reponses := array{"John F. Kennedy", "William Shakespeare", "Aristoteles", "Dschingis Khan"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0037 }
            Reponses := array{"Abraham Lincoln", "Ramses II", "Sokrates", "John F. Kennedy"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0038 }
            Reponses := array{"Che Guevara", "Beethoven", "Alexander der Grosse", "Gandhi"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0039 }
            Reponses := array{"Aristoteles", "Charles de Gaulle", "Julius Caesar", "Karl Marx"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0040 }
            Reponses := array{"Ludwig XIV", "Elisabeth II", "Tutanchamun", "Beethoven"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0041 }
            Reponses := array{"Gandhi", "Aristoteles", "Ramses II", "Che Guevara"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0042 }
            Reponses := array{"Attila", "Voltaire", "Kopernikus", "Ferdinand Magellan"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0043 }
            Reponses := array{"Victor Hugo", "Frida Kahlo", "Charlie Chaplin", "James Cook"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0044 }
            Reponses := array{"Charlie Chaplin", "Moliere", "James Cook", "Stalin"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0045 }
            Reponses := array{"Gutenberg", "Claude Monet", "Michelangelo", "Sueleyman der Praechtige"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0046 }
            Reponses := array{"Ferdinand Magellan", "Claude Monet", "Frida Kahlo", "Anne Frank"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0047 }
            Reponses := array{"Charlie Chaplin", "Marco Polo", "Karl der Grosse", "Wilhelm der Eroberer"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0048 }
            Reponses := array{"Bismarck", "Voltaire", "Rembrandt", "Vasco da Gama"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0049 }
            Reponses := array{"Amelia Earhart", "Mao Zedong", "Mussolini", "James Cook"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0050 }
            Reponses := array{"Garibaldi", "Hannibal", "Victor Hugo", "Iwan der Schreckliche"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0051 }
            Reponses := array{"Elisabeth I", "Spartacus", "James Cook", "Moliere"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0052 }
            Reponses := array{"Katharina die Grosse", "Attila", "Karl der Grosse", "Franklin D. Roosevelt"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0053 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Simon Bolivar", "Karl der Grosse"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0054 }
            Reponses := array{"Wilhelm der Eroberer", "Vasco da Gama", "Alexander Fleming", "Marco Polo"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0055 }
            Reponses := array{"Wilhelm der Eroberer", "Victor Hugo", "Heinrich VIII", "Rosa Parks"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0056 }
            Reponses := array{"Henry Ford", "Rosa Parks", "Moliere", "Elisabeth I"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0057 }
            Reponses := array{"Stalin", "Moliere", "Neil Armstrong", "Peter der Grosse"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0058 }
            Reponses := array{"Katharina die Grosse", "Simon Bolivar", "Ferdinand Magellan", "Amelia Earhart"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0059 }
            Reponses := array{"Franklin D. Roosevelt", "Iwan der Schreckliche", "Rosa Parks", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0060 }
            Reponses := array{"Attila", "James Cook", "Kopernikus", "Bismarck"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0061 }
            Reponses := array{"Hannibal", "Konfuzius", "Stalin", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0062 }
            Reponses := array{"Anne Frank", "Walt Disney", "Lenin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0063 }
            Reponses := array{"Alexander Fleming", "Mao Zedong", "Moliere", "Neil Armstrong"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0064 }
            Reponses := array{"Moliere", "Franklin D. Roosevelt", "Kopernikus", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0065 }
            Reponses := array{"Benjamin Franklin", "James Cook", "Alexander Fleming", "Saladin"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0066 }
            Reponses := array{"Lenin", "Neil Armstrong", "Mussolini", "Simon Bolivar"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0067 }
            Reponses := array{"Katharina die Grosse", "Rosa Parks", "Bismarck", "Garibaldi"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0068 }
            Reponses := array{"Michelangelo", "Mussolini", "Sigmund Freud", "Benjamin Franklin"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0069 }
            Reponses := array{"James Cook", "Walt Disney", "Frida Kahlo", "Sueleyman der Praechtige"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0070 }
            Reponses := array{"Saladin", "Juri Gagarin", "Salvador Dali", "Walt Disney"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0071 }
            Reponses := array{"Claude Monet", "Iwan der Schreckliche", "Mao Zedong", "Lenin"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0072 }
            Reponses := array{"Rembrandt", "Mao Zedong", "Saladin", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0073 }
            Reponses := array{"Michelangelo", "Rosa Parks", "Spartacus", "Konfuzius"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0074 }
            Reponses := array{"Rosa Parks", "Kopernikus", "Anne Frank", "Henry Ford"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0075 }
            Reponses := array{"Louis Pasteur", "Ferdinand Magellan", "Kopernikus", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0076 }
            Reponses := array{"Benjamin Franklin", "Henry Ford", "Alexander Fleming", "Michelangelo"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0077 }
            Reponses := array{"James Cook", "Sigmund Freud", "Hannibal", "Claude Monet"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0078 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Charlie Chaplin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0079 }
            Reponses := array{"James Cook", "Neil Armstrong", "Spartacus", "Amelia Earhart"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0080 }
            Reponses := array{"Iwan der Schreckliche", "Amelia Earhart", "Bismarck", "Neil Armstrong"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0081 }
            Reponses := array{"Juri Gagarin", "Victor Hugo", "Heinrich VIII", "Hannibal"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0082 }
            Reponses := array{"Claude Monet", "Elisabeth I", "Konfuzius", "Voltaire"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0083 }
            Reponses := array{"Saladin", "Benjamin Franklin", "Franklin D. Roosevelt", "Gutenberg"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0084 }
            Reponses := array{"James Cook", "Heinrich VIII", "Sueleyman der Praechtige", "Attila"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0085 }
            Reponses := array{"Iwan der Schreckliche", "Anne Frank", "Moliere", "Marco Polo"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0086 }
            Reponses := array{"Rosa Parks", "Voltaire", "Moliere", "Stalin"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0087 }
            Reponses := array{"Konfuzius", "Vasco da Gama", "Walt Disney", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0088 }
            Reponses := array{"Hannibal", "Saladin", "Henry Ford", "Claude Monet"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0089 }
            Reponses := array{"Francisco Pizarro", "Toussaint Louverture", "Vercingetorix", "Danton"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0090 }
            Reponses := array{"Hatschepsut", "Chlodwig", "Francisco Pizarro", "Emiliano Zapata"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0091 }
            Reponses := array{"Chlodwig", "Franz Ferdinand", "Richelieu", "Oda Nobunaga"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0092 }
            Reponses := array{"Lafayette", "Akbar", "Atatuerk", "Robespierre"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0093 }
            Reponses := array{"Danton", "Lafayette", "Akbar", "Franz Ferdinand"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0094 }
            Reponses := array{"Akbar", "Lafayette", "Miyamoto Musashi", "Erik der Rote"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0095 }
            Reponses := array{"Toussaint Louverture", "Konstantin", "Franz Ferdinand", "Richelieu"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0096 }
            Reponses := array{"Miyamoto Musashi", "Jose de San Martin", "Mark Aurel", "Lafayette"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0097 }
            Reponses := array{"Blackbeard", "Erik der Rote", "Patrice Lumumba", "Pancho Villa"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0098 }
            Reponses := array{"Chlodwig", "Sun Yat-sen", "Emiliano Zapata", "Ashoka"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0099 }
            Reponses := array{"Akbar", "Lafayette", "Ashoka", "Geronimo"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0100 }
            Reponses := array{"Justinian", "Caligula", "Sitting Bull", "Amerigo Vespucci"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0101 }
            Reponses := array{"Lafayette", "Atatuerk", "Nikolaus II", "Hernan Cortes"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0102 }
            Reponses := array{"Francisco Pizarro", "Blackbeard", "Haile Selassie", "Gustave Eiffel"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0103 }
            Reponses := array{"Francisco Pizarro", "Geronimo", "Nofretete", "Amerigo Vespucci"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0104 }
            Reponses := array{"Francis Drake", "Mark Aurel", "Patrice Lumumba", "Caligula"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0105 }
            Reponses := array{"Hernan Cortes", "Trotzki", "Hatschepsut", "Blackbeard"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0106 }
            Reponses := array{"Hatschepsut", "Ferdinand de Lesseps", "Ashoka", "Pancho Villa"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0107 }
            Reponses := array{"Nikolaus II", "Miyamoto Musashi", "Erik der Rote", "Gustave Eiffel"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0108 }
            Reponses := array{"Trotzki", "Nofretete", "Ho Chi Minh", "Hernan Cortes"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0109 }
            Reponses := array{"Nikolaus II", "Pancho Villa", "Rasputin", "Sitting Bull"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0110 }
            Reponses := array{"Hammurabi", "Nikolaus II", "Ho Chi Minh", "Patrice Lumumba"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0111 }
            Reponses := array{"Nikolaus II", "Franz Ferdinand", "Haile Selassie", "Hernan Cortes"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0112 }
            Reponses := array{"Danton", "Francis Drake", "Atatuerk", "Lafayette"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0113 }
            Reponses := array{"Francisco Pizarro", "Haile Selassie", "Hammurabi", "Miyamoto Musashi"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0114 }
            Reponses := array{"Robespierre", "Kyros der Grosse", "Jose de San Martin", "Patrice Lumumba"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0115 }
            Reponses := array{"Tokugawa Ieyasu", "Chlodwig", "Ho Chi Minh", "Blackbeard"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0116 }
            Reponses := array{"Blackbeard", "Sun Yat-sen", "Franz Ferdinand", "Richelieu"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0117 }
            Reponses := array{"Francis Drake", "Tokugawa Ieyasu", "Danton", "Konstantin"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0118 }
            Reponses := array{"Oda Nobunaga", "Tokugawa Ieyasu", "Toussaint Louverture", "Konstantin"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0119 }
            Reponses := array{"Trotzki", "Miyamoto Musashi", "Blackbeard", "Caligula"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0120 }
            Reponses := array{"Akbar", "Danton", "Geronimo", "Hammurabi"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0121 }
            Reponses := array{"Chlodwig", "Ashoka", "Miyamoto Musashi", "Konstantin"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0122 }
            Reponses := array{"Kyros der Grosse", "Leif Erikson", "Nikolaus II", "Oda Nobunaga"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0123 }
            Reponses := array{"Geronimo", "Akbar", "Hammurabi", "Emiliano Zapata"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0124 }
            Reponses := array{"Francis Drake", "Erik der Rote", "Nofretete", "Francisco Pizarro"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0125 }
            Reponses := array{"Tokugawa Ieyasu", "Gustave Eiffel", "Hammurabi", "Hatschepsut"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0126 }
            Reponses := array{"Ho Chi Minh", "Danton", "Nero", "Haile Selassie"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0127 }
            Reponses := array{"Caligula", "Patrice Lumumba", "Sun Yat-sen", "Jose de San Martin"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0128 }
            Reponses := array{"Hammurabi", "Mark Aurel", "Sitting Bull", "Danton"}
            BonneReponse := 1
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0129 }
            Reponses := array{"Konstantin", "Jose de San Martin", "Geronimo", "Chlodwig"}
            BonneReponse := 0
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0130 }
            Reponses := array{"Akbar", "Sitting Bull", "Justinian", "Hernan Cortes"}
            BonneReponse := 2
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0131 }
            Reponses := array{"Nofretete", "Oda Nobunaga", "Nikolaus II", "Leif Erikson"}
            BonneReponse := 3
        question:
            Enonce := "Wer ist diese historische Person?"
            Image := option{ persos.his_0132 }
            Reponses := array{"Erik der Rote", "Chlodwig", "Vercingetorix", "Pancho Villa"}
            BonneReponse := 0

MakePersosQuestionsIT() : []question =
    array:
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0001 }
            Reponses := array{"Napoleone Bonaparte", "Madre Teresa", "Isaac Newton", "Regina Vittoria"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0002 }
            Reponses := array{"Thomas Edison", "Ramses II", "Albert Einstein", "Giulio Cesare"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0003 }
            Reponses := array{"Abraham Lincoln", "Giulio Cesare", "Leonardo da Vinci", "Maria Antonietta"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0004 }
            Reponses := array{"Giulio Cesare", "Vincent van Gogh", "Cleopatra", "Galileo Galilei"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0005 }
            Reponses := array{"Martin Luther King", "Alessandro Magno", "Vincent van Gogh", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0006 }
            Reponses := array{"Gandhi", "Leonardo da Vinci", "Beethoven", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0007 }
            Reponses := array{"Beethoven", "Nikola Tesla", "Cristoforo Colombo", "Aristotele"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0008 }
            Reponses := array{"Karl Marx", "Tutankhamon", "George Washington", "Charles Darwin"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0009 }
            Reponses := array{"Nelson Mandela", "Abraham Lincoln", "Mozart", "Che Guevara"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0010 }
            Reponses := array{"Nelson Mandela", "Adolf Hitler", "Che Guevara", "Tutankhamon"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0011 }
            Reponses := array{"William Shakespeare", "Abraham Lincoln", "Winston Churchill", "Albert Einstein"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0012 }
            Reponses := array{"Cleopatra", "Charles de Gaulle", "Marie Curie", "Adolf Hitler"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0013 }
            Reponses := array{"John F. Kennedy", "Gandhi", "Beethoven", "Cristoforo Colombo"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0014 }
            Reponses := array{"Beethoven", "Ramses II", "Mozart", "Nelson Mandela"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0015 }
            Reponses := array{"Socrate", "Martin Luther King", "Charles Darwin", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0016 }
            Reponses := array{"Nikola Tesla", "Nelson Mandela", "Ramses II", "Madre Teresa"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0017 }
            Reponses := array{"Pablo Picasso", "Giovanna d'Arco", "Karl Marx", "Isaac Newton"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0018 }
            Reponses := array{"Luigi XIV", "Isaac Newton", "William Shakespeare", "Galileo Galilei"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0019 }
            Reponses := array{"Martin Luther King", "Mozart", "Maria Antonietta", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0020 }
            Reponses := array{"Albert Einstein", "Vincent van Gogh", "Elisabetta II", "Adolf Hitler"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0021 }
            Reponses := array{"Maria Antonietta", "Regina Vittoria", "Luigi XIV", "Beethoven"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0022 }
            Reponses := array{"William Shakespeare", "Elisabetta II", "Abraham Lincoln", "Aristotele"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0023 }
            Reponses := array{"Mozart", "Abraham Lincoln", "Pablo Picasso", "Tutankhamon"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0024 }
            Reponses := array{"Giulio Cesare", "Beethoven", "Thomas Edison", "Napoleone Bonaparte"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0025 }
            Reponses := array{"Pablo Picasso", "Regina Vittoria", "John F. Kennedy", "Mozart"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0026 }
            Reponses := array{"Vincent van Gogh", "Giulio Cesare", "Marie Curie", "Platone"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0027 }
            Reponses := array{"Charles de Gaulle", "Isaac Newton", "Socrate", "Mozart"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0028 }
            Reponses := array{"Napoleone Bonaparte", "Albert Einstein", "Leonardo da Vinci", "Galileo Galilei"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0029 }
            Reponses := array{"William Shakespeare", "Gengis Khan", "Cristoforo Colombo", "Charles Darwin"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0030 }
            Reponses := array{"Marie Curie", "Adolf Hitler", "Madre Teresa", "Cristoforo Colombo"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0031 }
            Reponses := array{"Maria Antonietta", "Thomas Edison", "Karl Marx", "Aristotele"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0032 }
            Reponses := array{"Marie Curie", "Nikola Tesla", "Charles de Gaulle", "Winston Churchill"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0033 }
            Reponses := array{"Socrate", "Napoleone Bonaparte", "Beethoven", "Giulio Cesare"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0034 }
            Reponses := array{"Platone", "Giulio Cesare", "Charles de Gaulle", "Albert Einstein"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0035 }
            Reponses := array{"Giulio Cesare", "Isaac Newton", "Marie Curie", "Aristotele"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0036 }
            Reponses := array{"John F. Kennedy", "William Shakespeare", "Aristotele", "Gengis Khan"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0037 }
            Reponses := array{"Abraham Lincoln", "Ramses II", "Socrate", "John F. Kennedy"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0038 }
            Reponses := array{"Che Guevara", "Beethoven", "Alessandro Magno", "Gandhi"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0039 }
            Reponses := array{"Aristotele", "Charles de Gaulle", "Giulio Cesare", "Karl Marx"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0040 }
            Reponses := array{"Luigi XIV", "Elisabetta II", "Tutankhamon", "Beethoven"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0041 }
            Reponses := array{"Gandhi", "Aristotele", "Ramses II", "Che Guevara"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0042 }
            Reponses := array{"Attila", "Voltaire", "Copernico", "Ferdinando Magellano"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0043 }
            Reponses := array{"Victor Hugo", "Frida Kahlo", "Charlie Chaplin", "James Cook"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0044 }
            Reponses := array{"Charlie Chaplin", "Moliere", "James Cook", "Stalin"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0045 }
            Reponses := array{"Gutenberg", "Claude Monet", "Michelangelo", "Solimano il Magnifico"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0046 }
            Reponses := array{"Ferdinando Magellano", "Claude Monet", "Frida Kahlo", "Anne Frank"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0047 }
            Reponses := array{"Charlie Chaplin", "Marco Polo", "Carlo Magno", "Guglielmo il Conquistatore"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0048 }
            Reponses := array{"Bismarck", "Voltaire", "Rembrandt", "Vasco da Gama"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0049 }
            Reponses := array{"Amelia Earhart", "Mao Zedong", "Mussolini", "James Cook"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0050 }
            Reponses := array{"Garibaldi", "Annibale", "Victor Hugo", "Ivan il Terribile"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0051 }
            Reponses := array{"Elisabetta I", "Spartaco", "James Cook", "Moliere"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0052 }
            Reponses := array{"Caterina la Grande", "Attila", "Carlo Magno", "Franklin D. Roosevelt"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0053 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Simon Bolivar", "Carlo Magno"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0054 }
            Reponses := array{"Guglielmo il Conquistatore", "Vasco da Gama", "Alexander Fleming", "Marco Polo"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0055 }
            Reponses := array{"Guglielmo il Conquistatore", "Victor Hugo", "Enrico VIII", "Rosa Parks"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0056 }
            Reponses := array{"Henry Ford", "Rosa Parks", "Moliere", "Elisabetta I"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0057 }
            Reponses := array{"Stalin", "Moliere", "Neil Armstrong", "Pietro il Grande"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0058 }
            Reponses := array{"Caterina la Grande", "Simon Bolivar", "Ferdinando Magellano", "Amelia Earhart"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0059 }
            Reponses := array{"Franklin D. Roosevelt", "Ivan il Terribile", "Rosa Parks", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0060 }
            Reponses := array{"Attila", "James Cook", "Copernico", "Bismarck"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0061 }
            Reponses := array{"Annibale", "Confucio", "Stalin", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0062 }
            Reponses := array{"Anne Frank", "Walt Disney", "Lenin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0063 }
            Reponses := array{"Alexander Fleming", "Mao Zedong", "Moliere", "Neil Armstrong"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0064 }
            Reponses := array{"Moliere", "Franklin D. Roosevelt", "Copernico", "Mao Zedong"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0065 }
            Reponses := array{"Benjamin Franklin", "James Cook", "Alexander Fleming", "Saladino"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0066 }
            Reponses := array{"Lenin", "Neil Armstrong", "Mussolini", "Simon Bolivar"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0067 }
            Reponses := array{"Caterina la Grande", "Rosa Parks", "Bismarck", "Garibaldi"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0068 }
            Reponses := array{"Michelangelo", "Mussolini", "Sigmund Freud", "Benjamin Franklin"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0069 }
            Reponses := array{"James Cook", "Walt Disney", "Frida Kahlo", "Solimano il Magnifico"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0070 }
            Reponses := array{"Saladino", "Jurij Gagarin", "Salvador Dali", "Walt Disney"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0071 }
            Reponses := array{"Claude Monet", "Ivan il Terribile", "Mao Zedong", "Lenin"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0072 }
            Reponses := array{"Rembrandt", "Mao Zedong", "Saladino", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0073 }
            Reponses := array{"Michelangelo", "Rosa Parks", "Spartaco", "Confucio"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0074 }
            Reponses := array{"Rosa Parks", "Copernico", "Anne Frank", "Henry Ford"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0075 }
            Reponses := array{"Louis Pasteur", "Ferdinando Magellano", "Copernico", "Voltaire"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0076 }
            Reponses := array{"Benjamin Franklin", "Henry Ford", "Alexander Fleming", "Michelangelo"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0077 }
            Reponses := array{"James Cook", "Sigmund Freud", "Annibale", "Claude Monet"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0078 }
            Reponses := array{"Neil Armstrong", "Marco Polo", "Charlie Chaplin", "Simon Bolivar"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0079 }
            Reponses := array{"James Cook", "Neil Armstrong", "Spartaco", "Amelia Earhart"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0080 }
            Reponses := array{"Ivan il Terribile", "Amelia Earhart", "Bismarck", "Neil Armstrong"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0081 }
            Reponses := array{"Jurij Gagarin", "Victor Hugo", "Enrico VIII", "Annibale"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0082 }
            Reponses := array{"Claude Monet", "Elisabetta I", "Confucio", "Voltaire"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0083 }
            Reponses := array{"Saladino", "Benjamin Franklin", "Franklin D. Roosevelt", "Gutenberg"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0084 }
            Reponses := array{"James Cook", "Enrico VIII", "Solimano il Magnifico", "Attila"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0085 }
            Reponses := array{"Ivan il Terribile", "Anne Frank", "Moliere", "Marco Polo"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0086 }
            Reponses := array{"Rosa Parks", "Voltaire", "Moliere", "Stalin"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0087 }
            Reponses := array{"Confucio", "Vasco da Gama", "Walt Disney", "Victor Hugo"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0088 }
            Reponses := array{"Annibale", "Saladino", "Henry Ford", "Claude Monet"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0089 }
            Reponses := array{"Francisco Pizarro", "Toussaint Louverture", "Vercingetorige", "Danton"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0090 }
            Reponses := array{"Hatshepsut", "Clodoveo", "Francisco Pizarro", "Emiliano Zapata"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0091 }
            Reponses := array{"Clodoveo", "Francesco Ferdinando", "Richelieu", "Oda Nobunaga"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0092 }
            Reponses := array{"La Fayette", "Akbar", "Ataturk", "Robespierre"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0093 }
            Reponses := array{"Danton", "La Fayette", "Akbar", "Francesco Ferdinando"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0094 }
            Reponses := array{"Akbar", "La Fayette", "Miyamoto Musashi", "Erik il Rosso"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0095 }
            Reponses := array{"Toussaint Louverture", "Costantino", "Francesco Ferdinando", "Richelieu"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0096 }
            Reponses := array{"Miyamoto Musashi", "Jose de San Martin", "Marco Aurelio", "La Fayette"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0097 }
            Reponses := array{"Barbanera", "Erik il Rosso", "Patrice Lumumba", "Pancho Villa"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0098 }
            Reponses := array{"Clodoveo", "Sun Yat-sen", "Emiliano Zapata", "Ashoka"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0099 }
            Reponses := array{"Akbar", "La Fayette", "Ashoka", "Geronimo"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0100 }
            Reponses := array{"Giustiniano", "Caligola", "Sitting Bull", "Amerigo Vespucci"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0101 }
            Reponses := array{"La Fayette", "Ataturk", "Nicola II", "Hernan Cortes"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0102 }
            Reponses := array{"Francisco Pizarro", "Barbanera", "Haile Selassie", "Gustave Eiffel"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0103 }
            Reponses := array{"Francisco Pizarro", "Geronimo", "Nefertiti", "Amerigo Vespucci"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0104 }
            Reponses := array{"Francis Drake", "Marco Aurelio", "Patrice Lumumba", "Caligola"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0105 }
            Reponses := array{"Hernan Cortes", "Trotsky", "Hatshepsut", "Barbanera"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0106 }
            Reponses := array{"Hatshepsut", "Ferdinand de Lesseps", "Ashoka", "Pancho Villa"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0107 }
            Reponses := array{"Nicola II", "Miyamoto Musashi", "Erik il Rosso", "Gustave Eiffel"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0108 }
            Reponses := array{"Trotsky", "Nefertiti", "Ho Chi Minh", "Hernan Cortes"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0109 }
            Reponses := array{"Nicola II", "Pancho Villa", "Rasputin", "Sitting Bull"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0110 }
            Reponses := array{"Hammurabi", "Nicola II", "Ho Chi Minh", "Patrice Lumumba"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0111 }
            Reponses := array{"Nicola II", "Francesco Ferdinando", "Haile Selassie", "Hernan Cortes"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0112 }
            Reponses := array{"Danton", "Francis Drake", "Ataturk", "La Fayette"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0113 }
            Reponses := array{"Francisco Pizarro", "Haile Selassie", "Hammurabi", "Miyamoto Musashi"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0114 }
            Reponses := array{"Robespierre", "Ciro il Grande", "Jose de San Martin", "Patrice Lumumba"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0115 }
            Reponses := array{"Tokugawa Ieyasu", "Clodoveo", "Ho Chi Minh", "Barbanera"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0116 }
            Reponses := array{"Barbanera", "Sun Yat-sen", "Francesco Ferdinando", "Richelieu"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0117 }
            Reponses := array{"Francis Drake", "Tokugawa Ieyasu", "Danton", "Costantino"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0118 }
            Reponses := array{"Oda Nobunaga", "Tokugawa Ieyasu", "Toussaint Louverture", "Costantino"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0119 }
            Reponses := array{"Trotsky", "Miyamoto Musashi", "Barbanera", "Caligola"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0120 }
            Reponses := array{"Akbar", "Danton", "Geronimo", "Hammurabi"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0121 }
            Reponses := array{"Clodoveo", "Ashoka", "Miyamoto Musashi", "Costantino"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0122 }
            Reponses := array{"Ciro il Grande", "Leif Erikson", "Nicola II", "Oda Nobunaga"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0123 }
            Reponses := array{"Geronimo", "Akbar", "Hammurabi", "Emiliano Zapata"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0124 }
            Reponses := array{"Francis Drake", "Erik il Rosso", "Nefertiti", "Francisco Pizarro"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0125 }
            Reponses := array{"Tokugawa Ieyasu", "Gustave Eiffel", "Hammurabi", "Hatshepsut"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0126 }
            Reponses := array{"Ho Chi Minh", "Danton", "Nerone", "Haile Selassie"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0127 }
            Reponses := array{"Caligola", "Patrice Lumumba", "Sun Yat-sen", "Jose de San Martin"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0128 }
            Reponses := array{"Hammurabi", "Marco Aurelio", "Sitting Bull", "Danton"}
            BonneReponse := 1
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0129 }
            Reponses := array{"Costantino", "Jose de San Martin", "Geronimo", "Clodoveo"}
            BonneReponse := 0
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0130 }
            Reponses := array{"Akbar", "Sitting Bull", "Giustiniano", "Hernan Cortes"}
            BonneReponse := 2
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0131 }
            Reponses := array{"Nefertiti", "Oda Nobunaga", "Nicola II", "Leif Erikson"}
            BonneReponse := 3
        question:
            Enonce := "Chi e questo personaggio storico?"
            Image := option{ persos.his_0132 }
            Reponses := array{"Erik il Rosso", "Clodoveo", "Vercingetorige", "Pancho Villa"}
            BonneReponse := 0

MakePersosQuestions() : []question =
    MakePersosQuestionsFR()
