using { /Verse.org/Assets }

# regions_bank.verse — Quizz DRAPEAUX REGIONAUX (pages Flag of X)
# GENERE — NE PAS EDITER A LA MAIN.

RegionsDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}

MakeRegionsQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0001 }
            Reponses := array{"Hawai", "Ecosse", "Angleterre", "Nevada"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0002 }
            Reponses := array{"Corse", "Pays de Galles", "Hawai", "Normandie"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0003 }
            Reponses := array{"Nevada", "Pays de Galles", "Bretagne", "Angleterre"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0004 }
            Reponses := array{"Californie", "Normandie", "Texas", "Corse"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0005 }
            Reponses := array{"Andalousie", "Texas", "Groenland", "Pays basque"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0006 }
            Reponses := array{"Floride", "Baviere", "Californie", "Texas"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0007 }
            Reponses := array{"Pays basque", "Nouveau-Mexique", "Colorado", "Hawai"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0008 }
            Reponses := array{"Maryland", "Baviere", "Alaska", "Groenland"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0009 }
            Reponses := array{"Arizona", "Groenland", "Catalogne", "Angleterre"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0010 }
            Reponses := array{"Baviere", "Arizona", "Nevada", "Andalousie"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0011 }
            Reponses := array{"Angleterre", "Etat de New York", "Groenland", "Catalogne"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0012 }
            Reponses := array{"Porto Rico", "Corse", "Pays basque", "Ecosse"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0013 }
            Reponses := array{"Andalousie", "Bretagne", "Colorado", "Maryland"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0014 }
            Reponses := array{"Colorado", "Catalogne", "Arizona", "Bretagne"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0015 }
            Reponses := array{"Nevada", "Quebec", "Californie", "Corse"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0016 }
            Reponses := array{"Angleterre", "Normandie", "Alaska", "Maryland"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0017 }
            Reponses := array{"Texas", "Quebec", "Pays de Galles", "Floride"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0018 }
            Reponses := array{"Californie", "Ecosse", "Sicile", "Andalousie"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0019 }
            Reponses := array{"Bretagne", "Texas", "Californie", "Colorado"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0020 }
            Reponses := array{"Alaska", "Floride", "Pays de Galles", "Nouveau-Mexique"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0021 }
            Reponses := array{"Maryland", "Floride", "Pays basque", "Arizona"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0022 }
            Reponses := array{"Nouveau-Mexique", "Catalogne", "Maryland", "Porto Rico"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0023 }
            Reponses := array{"Nevada", "Groenland", "Catalogne", "Normandie"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0024 }
            Reponses := array{"Alaska", "Etat de New York", "Nevada", "Angleterre"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0025 }
            Reponses := array{"Bretagne", "Pays basque", "Nevada", "Etat de New York"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0026 }
            Reponses := array{"Andalousie", "Sicile", "Georgie (USA)", "Etat de New York"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0027 }
            Reponses := array{"Occitanie", "Toscane", "Sardaigne", "Venetie"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0028 }
            Reponses := array{"Iles Canaries", "Occitanie", "Galice", "Berlin"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0029 }
            Reponses := array{"Utah", "Colombie-Britannique", "Caroline du Sud", "Iles Canaries"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0030 }
            Reponses := array{"Iles Canaries", "Iles Baleares", "Toscane", "Saxe"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0031 }
            Reponses := array{"Caroline du Sud", "Iles Canaries", "Saxe", "Sardaigne"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0032 }
            Reponses := array{"Berlin", "Oregon", "Iles Baleares", "Iles Feroe"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0033 }
            Reponses := array{"Colombie-Britannique", "Berlin", "Hambourg", "Toscane"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0034 }
            Reponses := array{"Ontario", "Louisiane", "Iles Feroe", "Alsace"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0035 }
            Reponses := array{"Iles Canaries", "Venetie", "Alberta", "Colombie-Britannique"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0036 }
            Reponses := array{"Galice", "Colombie-Britannique", "Toscane", "Alberta"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0037 }
            Reponses := array{"Berlin", "Oregon", "Iles Baleares", "Iles Feroe"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0038 }
            Reponses := array{"Sardaigne", "Berlin", "Occitanie", "Etat de Washington"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0039 }
            Reponses := array{"Wyoming", "Occitanie", "Oregon", "Venetie"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0040 }
            Reponses := array{"Berlin", "Ohio", "Utah", "Hambourg"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0041 }
            Reponses := array{"Hambourg", "Tennessee", "Venetie", "Ohio"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0042 }
            Reponses := array{"Saxe", "Louisiane", "Alberta", "Ohio"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0043 }
            Reponses := array{"Berlin", "Tennessee", "Sardaigne", "Wyoming"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0044 }
            Reponses := array{"Venetie", "Iles Baleares", "Caroline du Sud", "Etat de Washington"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0045 }
            Reponses := array{"Toscane", "Galice", "Virginie", "Tennessee"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0046 }
            Reponses := array{"Wyoming", "Tennessee", "Alberta", "Ontario"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0047 }
            Reponses := array{"Wyoming", "Montana", "Etat de Washington", "Colombie-Britannique"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0048 }
            Reponses := array{"Polynesie francaise", "Virginie", "Berlin", "Iles Baleares"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0049 }
            Reponses := array{"Polynesie francaise", "Alsace", "Louisiane", "Virginie"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0050 }
            Reponses := array{"Occitanie", "Berlin", "Tennessee", "Saxe"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0051 }
            Reponses := array{"Iles Canaries", "Virginie", "Venetie", "Polynesie francaise"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0052 }
            Reponses := array{"Utah", "Iles Baleares", "Toscane", "Alsace"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0053 }
            Reponses := array{"Hesse", "Aragon", "Ligurie", "Calabre"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0054 }
            Reponses := array{"Madere", "Asturies", "Acores", "Campanie"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0055 }
            Reponses := array{"Frioul", "Cantabrie", "Vermont", "Calabre"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0056 }
            Reponses := array{"Nouvelle-Ecosse", "Lombardie", "Manitoba", "Murcie"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0057 }
            Reponses := array{"Estremadure", "Madere", "Nebraska", "Acores"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0058 }
            Reponses := array{"Estremadure", "Aragon", "Bade-Wurtemberg", "Nebraska"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0059 }
            Reponses := array{"Maine", "Frioul", "Hesse", "Kansas"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0060 }
            Reponses := array{"Emilie-Romagne", "Thuringe", "Aragon", "Kansas"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0061 }
            Reponses := array{"Vermont", "Brandebourg", "Delaware", "Michigan"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0062 }
            Reponses := array{"Manitoba", "Pouilles", "Calabre", "Idaho"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0063 }
            Reponses := array{"Lombardie", "Saskatchewan", "Madere", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0064 }
            Reponses := array{"Thuringe", "Emilie-Romagne", "Maine", "Nouvelle-Ecosse"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0065 }
            Reponses := array{"Murcie", "Nunavut", "Emilie-Romagne", "Nebraska"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0066 }
            Reponses := array{"Calabre", "Kansas", "Emilie-Romagne", "Brandebourg"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0067 }
            Reponses := array{"Kansas", "Nebraska", "Frioul", "Maine"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0068 }
            Reponses := array{"Idaho", "Michigan", "Piemont", "Frioul"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0069 }
            Reponses := array{"Michigan", "Bade-Wurtemberg", "Maine", "Dakota du Nord"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0070 }
            Reponses := array{"Thuringe", "Pouilles", "Vermont", "Nunavut"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0071 }
            Reponses := array{"Saskatchewan", "Hesse", "Piemont", "Delaware"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0072 }
            Reponses := array{"Idaho", "Arkansas", "Murcie", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0073 }
            Reponses := array{"Oklahoma", "Michigan", "Estremadure", "Hesse"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0074 }
            Reponses := array{"Nunavut", "Lombardie", "Saskatchewan", "Nouvelle-Ecosse"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0075 }
            Reponses := array{"Asturies", "Oklahoma", "Pennsylvanie", "Calabre"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0076 }
            Reponses := array{"Murcie", "Aragon", "Ligurie", "Nouvelle-Ecosse"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0077 }
            Reponses := array{"Indiana", "Nunavut", "Madere", "Idaho"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0078 }
            Reponses := array{"Manitoba", "Acores", "Madere", "Arkansas"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0079 }
            Reponses := array{"Piemont", "Manitoba", "Campanie", "Calabre"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0080 }
            Reponses := array{"Aragon", "Maine", "Nouvelle-Ecosse", "Emilie-Romagne"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0081 }
            Reponses := array{"Nebraska", "Thuringe", "Campanie", "Bade-Wurtemberg"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0082 }
            Reponses := array{"Pouilles", "Brandebourg", "Madere", "Cantabrie"}
            BonneReponse := 0
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0083 }
            Reponses := array{"Nebraska", "Bade-Wurtemberg", "Frioul", "Michigan"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0084 }
            Reponses := array{"Acores", "Frioul", "Michigan", "Pennsylvanie"}
            BonneReponse := 3
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0085 }
            Reponses := array{"Kansas", "Aragon", "Massachusetts", "Ligurie"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0086 }
            Reponses := array{"Brandebourg", "Vermont", "Michigan", "Cantabrie"}
            BonneReponse := 2
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0087 }
            Reponses := array{"Lombardie", "Indiana", "Delaware", "Vermont"}
            BonneReponse := 1
        question:
            Enonce := "Quel etat ou region a ce drapeau ?"
            Image := option{ regions.reg_0088 }
            Reponses := array{"Cantabrie", "Pouilles", "Dakota du Nord", "Ligurie"}
            BonneReponse := 2

MakeRegionsQuestionsEN() : []question =
    array:
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0001 }
            Reponses := array{"Hawaii", "Scotland", "England", "Nevada"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0002 }
            Reponses := array{"Corsica", "Wales", "Hawaii", "Normandy"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0003 }
            Reponses := array{"Nevada", "Wales", "Brittany", "England"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0004 }
            Reponses := array{"California", "Normandy", "Texas", "Corsica"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0005 }
            Reponses := array{"Andalusia", "Texas", "Greenland", "Basque Country"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0006 }
            Reponses := array{"Florida", "Bavaria", "California", "Texas"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0007 }
            Reponses := array{"Basque Country", "New Mexico", "Colorado", "Hawaii"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0008 }
            Reponses := array{"Maryland", "Bavaria", "Alaska", "Greenland"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0009 }
            Reponses := array{"Arizona", "Greenland", "Catalonia", "England"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0010 }
            Reponses := array{"Bavaria", "Arizona", "Nevada", "Andalusia"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0011 }
            Reponses := array{"England", "New York", "Greenland", "Catalonia"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0012 }
            Reponses := array{"Puerto Rico", "Corsica", "Basque Country", "Scotland"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0013 }
            Reponses := array{"Andalusia", "Brittany", "Colorado", "Maryland"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0014 }
            Reponses := array{"Colorado", "Catalonia", "Arizona", "Brittany"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0015 }
            Reponses := array{"Nevada", "Quebec", "California", "Corsica"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0016 }
            Reponses := array{"England", "Normandy", "Alaska", "Maryland"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0017 }
            Reponses := array{"Texas", "Quebec", "Wales", "Florida"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0018 }
            Reponses := array{"California", "Scotland", "Sicily", "Andalusia"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0019 }
            Reponses := array{"Brittany", "Texas", "California", "Colorado"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0020 }
            Reponses := array{"Alaska", "Florida", "Wales", "New Mexico"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0021 }
            Reponses := array{"Maryland", "Florida", "Basque Country", "Arizona"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0022 }
            Reponses := array{"New Mexico", "Catalonia", "Maryland", "Puerto Rico"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0023 }
            Reponses := array{"Nevada", "Greenland", "Catalonia", "Normandy"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0024 }
            Reponses := array{"Alaska", "New York", "Nevada", "England"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0025 }
            Reponses := array{"Brittany", "Basque Country", "Nevada", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0026 }
            Reponses := array{"Andalusia", "Sicily", "Georgia", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0027 }
            Reponses := array{"Occitania", "Tuscany", "Sardinia", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0028 }
            Reponses := array{"Canary Islands", "Occitania", "Galicia", "Berlin"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0029 }
            Reponses := array{"Utah", "British Columbia", "South Carolina", "Canary Islands"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0030 }
            Reponses := array{"Canary Islands", "Balearic Islands", "Tuscany", "Saxony"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0031 }
            Reponses := array{"South Carolina", "Canary Islands", "Saxony", "Sardinia"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0032 }
            Reponses := array{"Berlin", "Oregon", "Balearic Islands", "Faroe Islands"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0033 }
            Reponses := array{"British Columbia", "Berlin", "Hamburg", "Tuscany"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0034 }
            Reponses := array{"Ontario", "Louisiana", "Faroe Islands", "Alsace"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0035 }
            Reponses := array{"Canary Islands", "Veneto", "Alberta", "British Columbia"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0036 }
            Reponses := array{"Galicia", "British Columbia", "Tuscany", "Alberta"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0037 }
            Reponses := array{"Berlin", "Oregon", "Balearic Islands", "Faroe Islands"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0038 }
            Reponses := array{"Sardinia", "Berlin", "Occitania", "Washington"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0039 }
            Reponses := array{"Wyoming", "Occitania", "Oregon", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0040 }
            Reponses := array{"Berlin", "Ohio", "Utah", "Hamburg"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0041 }
            Reponses := array{"Hamburg", "Tennessee", "Veneto", "Ohio"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0042 }
            Reponses := array{"Saxony", "Louisiana", "Alberta", "Ohio"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0043 }
            Reponses := array{"Berlin", "Tennessee", "Sardinia", "Wyoming"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0044 }
            Reponses := array{"Veneto", "Balearic Islands", "South Carolina", "Washington"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0045 }
            Reponses := array{"Tuscany", "Galicia", "Virginia", "Tennessee"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0046 }
            Reponses := array{"Wyoming", "Tennessee", "Alberta", "Ontario"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0047 }
            Reponses := array{"Wyoming", "Montana", "Washington", "British Columbia"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0048 }
            Reponses := array{"French Polynesia", "Virginia", "Berlin", "Balearic Islands"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0049 }
            Reponses := array{"French Polynesia", "Alsace", "Louisiana", "Virginia"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0050 }
            Reponses := array{"Occitania", "Berlin", "Tennessee", "Saxony"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0051 }
            Reponses := array{"Canary Islands", "Virginia", "Veneto", "French Polynesia"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0052 }
            Reponses := array{"Utah", "Balearic Islands", "Tuscany", "Alsace"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0053 }
            Reponses := array{"Hesse", "Aragon", "Liguria", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0054 }
            Reponses := array{"Madeira", "Asturias", "Azores", "Campania"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0055 }
            Reponses := array{"Friuli", "Cantabria", "Vermont", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0056 }
            Reponses := array{"Nova Scotia", "Lombardy", "Manitoba", "Murcia"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0057 }
            Reponses := array{"Extremadura", "Madeira", "Nebraska", "Azores"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0058 }
            Reponses := array{"Extremadura", "Aragon", "Baden-Wurttemberg", "Nebraska"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0059 }
            Reponses := array{"Maine", "Friuli", "Hesse", "Kansas"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0060 }
            Reponses := array{"Emilia-Romagna", "Thuringia", "Aragon", "Kansas"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0061 }
            Reponses := array{"Vermont", "Brandenburg", "Delaware", "Michigan"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0062 }
            Reponses := array{"Manitoba", "Apulia", "Calabria", "Idaho"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0063 }
            Reponses := array{"Lombardy", "Saskatchewan", "Madeira", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0064 }
            Reponses := array{"Thuringia", "Emilia-Romagna", "Maine", "Nova Scotia"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0065 }
            Reponses := array{"Murcia", "Nunavut", "Emilia-Romagna", "Nebraska"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0066 }
            Reponses := array{"Calabria", "Kansas", "Emilia-Romagna", "Brandenburg"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0067 }
            Reponses := array{"Kansas", "Nebraska", "Friuli", "Maine"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0068 }
            Reponses := array{"Idaho", "Michigan", "Piedmont", "Friuli"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0069 }
            Reponses := array{"Michigan", "Baden-Wurttemberg", "Maine", "North Dakota"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0070 }
            Reponses := array{"Thuringia", "Apulia", "Vermont", "Nunavut"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0071 }
            Reponses := array{"Saskatchewan", "Hesse", "Piedmont", "Delaware"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0072 }
            Reponses := array{"Idaho", "Arkansas", "Murcia", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0073 }
            Reponses := array{"Oklahoma", "Michigan", "Extremadura", "Hesse"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0074 }
            Reponses := array{"Nunavut", "Lombardy", "Saskatchewan", "Nova Scotia"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0075 }
            Reponses := array{"Asturias", "Oklahoma", "Pennsylvania", "Calabria"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0076 }
            Reponses := array{"Murcia", "Aragon", "Liguria", "Nova Scotia"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0077 }
            Reponses := array{"Indiana", "Nunavut", "Madeira", "Idaho"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0078 }
            Reponses := array{"Manitoba", "Azores", "Madeira", "Arkansas"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0079 }
            Reponses := array{"Piedmont", "Manitoba", "Campania", "Calabria"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0080 }
            Reponses := array{"Aragon", "Maine", "Nova Scotia", "Emilia-Romagna"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0081 }
            Reponses := array{"Nebraska", "Thuringia", "Campania", "Baden-Wurttemberg"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0082 }
            Reponses := array{"Apulia", "Brandenburg", "Madeira", "Cantabria"}
            BonneReponse := 0
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0083 }
            Reponses := array{"Nebraska", "Baden-Wurttemberg", "Friuli", "Michigan"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0084 }
            Reponses := array{"Azores", "Friuli", "Michigan", "Pennsylvania"}
            BonneReponse := 3
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0085 }
            Reponses := array{"Kansas", "Aragon", "Massachusetts", "Liguria"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0086 }
            Reponses := array{"Brandenburg", "Vermont", "Michigan", "Cantabria"}
            BonneReponse := 2
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0087 }
            Reponses := array{"Lombardy", "Indiana", "Delaware", "Vermont"}
            BonneReponse := 1
        question:
            Enonce := "Which state or region has this flag?"
            Image := option{ regions.reg_0088 }
            Reponses := array{"Cantabria", "Apulia", "North Dakota", "Liguria"}
            BonneReponse := 2

MakeRegionsQuestionsES() : []question =
    array:
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0001 }
            Reponses := array{"Hawai", "Escocia", "Inglaterra", "Nevada"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0002 }
            Reponses := array{"Corcega", "Gales", "Hawai", "Normandia"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0003 }
            Reponses := array{"Nevada", "Gales", "Bretana", "Inglaterra"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0004 }
            Reponses := array{"California", "Normandia", "Texas", "Corcega"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0005 }
            Reponses := array{"Andalucia", "Texas", "Groenlandia", "Pais Vasco"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0006 }
            Reponses := array{"Florida", "Baviera", "California", "Texas"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0007 }
            Reponses := array{"Pais Vasco", "Nuevo Mexico", "Colorado", "Hawai"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0008 }
            Reponses := array{"Maryland", "Baviera", "Alaska", "Groenlandia"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0009 }
            Reponses := array{"Arizona", "Groenlandia", "Cataluna", "Inglaterra"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0010 }
            Reponses := array{"Baviera", "Arizona", "Nevada", "Andalucia"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0011 }
            Reponses := array{"Inglaterra", "Nueva York", "Groenlandia", "Cataluna"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0012 }
            Reponses := array{"Puerto Rico", "Corcega", "Pais Vasco", "Escocia"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0013 }
            Reponses := array{"Andalucia", "Bretana", "Colorado", "Maryland"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0014 }
            Reponses := array{"Colorado", "Cataluna", "Arizona", "Bretana"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0015 }
            Reponses := array{"Nevada", "Quebec", "California", "Corcega"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0016 }
            Reponses := array{"Inglaterra", "Normandia", "Alaska", "Maryland"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0017 }
            Reponses := array{"Texas", "Quebec", "Gales", "Florida"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0018 }
            Reponses := array{"California", "Escocia", "Sicilia", "Andalucia"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0019 }
            Reponses := array{"Bretana", "Texas", "California", "Colorado"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0020 }
            Reponses := array{"Alaska", "Florida", "Gales", "Nuevo Mexico"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0021 }
            Reponses := array{"Maryland", "Florida", "Pais Vasco", "Arizona"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0022 }
            Reponses := array{"Nuevo Mexico", "Cataluna", "Maryland", "Puerto Rico"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0023 }
            Reponses := array{"Nevada", "Groenlandia", "Cataluna", "Normandia"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0024 }
            Reponses := array{"Alaska", "Nueva York", "Nevada", "Inglaterra"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0025 }
            Reponses := array{"Bretana", "Pais Vasco", "Nevada", "Nueva York"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0026 }
            Reponses := array{"Andalucia", "Sicilia", "Georgia", "Nueva York"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0027 }
            Reponses := array{"Occitania", "Toscana", "Cerdena", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0028 }
            Reponses := array{"Islas Canarias", "Occitania", "Galicia", "Berlin"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0029 }
            Reponses := array{"Utah", "Columbia Britanica", "Carolina del Sur", "Islas Canarias"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0030 }
            Reponses := array{"Islas Canarias", "Islas Baleares", "Toscana", "Sajonia"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0031 }
            Reponses := array{"Carolina del Sur", "Islas Canarias", "Sajonia", "Cerdena"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0032 }
            Reponses := array{"Berlin", "Oregon", "Islas Baleares", "Islas Feroe"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0033 }
            Reponses := array{"Columbia Britanica", "Berlin", "Hamburgo", "Toscana"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0034 }
            Reponses := array{"Ontario", "Luisiana", "Islas Feroe", "Alsacia"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0035 }
            Reponses := array{"Islas Canarias", "Veneto", "Alberta", "Columbia Britanica"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0036 }
            Reponses := array{"Galicia", "Columbia Britanica", "Toscana", "Alberta"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0037 }
            Reponses := array{"Berlin", "Oregon", "Islas Baleares", "Islas Feroe"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0038 }
            Reponses := array{"Cerdena", "Berlin", "Occitania", "Washington"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0039 }
            Reponses := array{"Wyoming", "Occitania", "Oregon", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0040 }
            Reponses := array{"Berlin", "Ohio", "Utah", "Hamburgo"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0041 }
            Reponses := array{"Hamburgo", "Tennessee", "Veneto", "Ohio"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0042 }
            Reponses := array{"Sajonia", "Luisiana", "Alberta", "Ohio"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0043 }
            Reponses := array{"Berlin", "Tennessee", "Cerdena", "Wyoming"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0044 }
            Reponses := array{"Veneto", "Islas Baleares", "Carolina del Sur", "Washington"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0045 }
            Reponses := array{"Toscana", "Galicia", "Virginia", "Tennessee"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0046 }
            Reponses := array{"Wyoming", "Tennessee", "Alberta", "Ontario"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0047 }
            Reponses := array{"Wyoming", "Montana", "Washington", "Columbia Britanica"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0048 }
            Reponses := array{"Polinesia Francesa", "Virginia", "Berlin", "Islas Baleares"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0049 }
            Reponses := array{"Polinesia Francesa", "Alsacia", "Luisiana", "Virginia"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0050 }
            Reponses := array{"Occitania", "Berlin", "Tennessee", "Sajonia"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0051 }
            Reponses := array{"Islas Canarias", "Virginia", "Veneto", "Polinesia Francesa"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0052 }
            Reponses := array{"Utah", "Islas Baleares", "Toscana", "Alsacia"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0053 }
            Reponses := array{"Hesse", "Aragon", "Liguria", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0054 }
            Reponses := array{"Madeira", "Asturias", "Azores", "Campania"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0055 }
            Reponses := array{"Friul", "Cantabria", "Vermont", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0056 }
            Reponses := array{"Nueva Escocia", "Lombardia", "Manitoba", "Murcia"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0057 }
            Reponses := array{"Extremadura", "Madeira", "Nebraska", "Azores"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0058 }
            Reponses := array{"Extremadura", "Aragon", "Baden-Wurtemberg", "Nebraska"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0059 }
            Reponses := array{"Maine", "Friul", "Hesse", "Kansas"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0060 }
            Reponses := array{"Emilia-Romana", "Turingia", "Aragon", "Kansas"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0061 }
            Reponses := array{"Vermont", "Brandeburgo", "Delaware", "Michigan"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0062 }
            Reponses := array{"Manitoba", "Apulia", "Calabria", "Idaho"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0063 }
            Reponses := array{"Lombardia", "Saskatchewan", "Madeira", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0064 }
            Reponses := array{"Turingia", "Emilia-Romana", "Maine", "Nueva Escocia"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0065 }
            Reponses := array{"Murcia", "Nunavut", "Emilia-Romana", "Nebraska"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0066 }
            Reponses := array{"Calabria", "Kansas", "Emilia-Romana", "Brandeburgo"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0067 }
            Reponses := array{"Kansas", "Nebraska", "Friul", "Maine"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0068 }
            Reponses := array{"Idaho", "Michigan", "Piamonte", "Friul"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0069 }
            Reponses := array{"Michigan", "Baden-Wurtemberg", "Maine", "Dakota del Norte"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0070 }
            Reponses := array{"Turingia", "Apulia", "Vermont", "Nunavut"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0071 }
            Reponses := array{"Saskatchewan", "Hesse", "Piamonte", "Delaware"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0072 }
            Reponses := array{"Idaho", "Arkansas", "Murcia", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0073 }
            Reponses := array{"Oklahoma", "Michigan", "Extremadura", "Hesse"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0074 }
            Reponses := array{"Nunavut", "Lombardia", "Saskatchewan", "Nueva Escocia"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0075 }
            Reponses := array{"Asturias", "Oklahoma", "Pensilvania", "Calabria"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0076 }
            Reponses := array{"Murcia", "Aragon", "Liguria", "Nueva Escocia"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0077 }
            Reponses := array{"Indiana", "Nunavut", "Madeira", "Idaho"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0078 }
            Reponses := array{"Manitoba", "Azores", "Madeira", "Arkansas"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0079 }
            Reponses := array{"Piamonte", "Manitoba", "Campania", "Calabria"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0080 }
            Reponses := array{"Aragon", "Maine", "Nueva Escocia", "Emilia-Romana"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0081 }
            Reponses := array{"Nebraska", "Turingia", "Campania", "Baden-Wurtemberg"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0082 }
            Reponses := array{"Apulia", "Brandeburgo", "Madeira", "Cantabria"}
            BonneReponse := 0
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0083 }
            Reponses := array{"Nebraska", "Baden-Wurtemberg", "Friul", "Michigan"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0084 }
            Reponses := array{"Azores", "Friul", "Michigan", "Pensilvania"}
            BonneReponse := 3
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0085 }
            Reponses := array{"Kansas", "Aragon", "Massachusetts", "Liguria"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0086 }
            Reponses := array{"Brandeburgo", "Vermont", "Michigan", "Cantabria"}
            BonneReponse := 2
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0087 }
            Reponses := array{"Lombardia", "Indiana", "Delaware", "Vermont"}
            BonneReponse := 1
        question:
            Enonce := "Que estado o region tiene esta bandera?"
            Image := option{ regions.reg_0088 }
            Reponses := array{"Cantabria", "Apulia", "Dakota del Norte", "Liguria"}
            BonneReponse := 2

MakeRegionsQuestionsDE() : []question =
    array:
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0001 }
            Reponses := array{"Hawaii", "Schottland", "England", "Nevada"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0002 }
            Reponses := array{"Korsika", "Wales", "Hawaii", "Normandie"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0003 }
            Reponses := array{"Nevada", "Wales", "Bretagne", "England"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0004 }
            Reponses := array{"Kalifornien", "Normandie", "Texas", "Korsika"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0005 }
            Reponses := array{"Andalusien", "Texas", "Groenland", "Baskenland"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0006 }
            Reponses := array{"Florida", "Bayern", "Kalifornien", "Texas"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0007 }
            Reponses := array{"Baskenland", "New Mexico", "Colorado", "Hawaii"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0008 }
            Reponses := array{"Maryland", "Bayern", "Alaska", "Groenland"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0009 }
            Reponses := array{"Arizona", "Groenland", "Katalonien", "England"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0010 }
            Reponses := array{"Bayern", "Arizona", "Nevada", "Andalusien"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0011 }
            Reponses := array{"England", "New York", "Groenland", "Katalonien"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0012 }
            Reponses := array{"Puerto Rico", "Korsika", "Baskenland", "Schottland"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0013 }
            Reponses := array{"Andalusien", "Bretagne", "Colorado", "Maryland"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0014 }
            Reponses := array{"Colorado", "Katalonien", "Arizona", "Bretagne"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0015 }
            Reponses := array{"Nevada", "Quebec", "Kalifornien", "Korsika"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0016 }
            Reponses := array{"England", "Normandie", "Alaska", "Maryland"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0017 }
            Reponses := array{"Texas", "Quebec", "Wales", "Florida"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0018 }
            Reponses := array{"Kalifornien", "Schottland", "Sizilien", "Andalusien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0019 }
            Reponses := array{"Bretagne", "Texas", "Kalifornien", "Colorado"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0020 }
            Reponses := array{"Alaska", "Florida", "Wales", "New Mexico"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0021 }
            Reponses := array{"Maryland", "Florida", "Baskenland", "Arizona"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0022 }
            Reponses := array{"New Mexico", "Katalonien", "Maryland", "Puerto Rico"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0023 }
            Reponses := array{"Nevada", "Groenland", "Katalonien", "Normandie"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0024 }
            Reponses := array{"Alaska", "New York", "Nevada", "England"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0025 }
            Reponses := array{"Bretagne", "Baskenland", "Nevada", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0026 }
            Reponses := array{"Andalusien", "Sizilien", "Georgia", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0027 }
            Reponses := array{"Okzitanien", "Toskana", "Sardinien", "Venetien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0028 }
            Reponses := array{"Kanarische Inseln", "Okzitanien", "Galicien", "Berlin"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0029 }
            Reponses := array{"Utah", "British Columbia", "South Carolina", "Kanarische Inseln"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0030 }
            Reponses := array{"Kanarische Inseln", "Balearen", "Toskana", "Sachsen"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0031 }
            Reponses := array{"South Carolina", "Kanarische Inseln", "Sachsen", "Sardinien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0032 }
            Reponses := array{"Berlin", "Oregon", "Balearen", "Faeroeer"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0033 }
            Reponses := array{"British Columbia", "Berlin", "Hamburg", "Toskana"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0034 }
            Reponses := array{"Ontario", "Louisiana", "Faeroeer", "Elsass"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0035 }
            Reponses := array{"Kanarische Inseln", "Venetien", "Alberta", "British Columbia"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0036 }
            Reponses := array{"Galicien", "British Columbia", "Toskana", "Alberta"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0037 }
            Reponses := array{"Berlin", "Oregon", "Balearen", "Faeroeer"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0038 }
            Reponses := array{"Sardinien", "Berlin", "Okzitanien", "Washington"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0039 }
            Reponses := array{"Wyoming", "Okzitanien", "Oregon", "Venetien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0040 }
            Reponses := array{"Berlin", "Ohio", "Utah", "Hamburg"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0041 }
            Reponses := array{"Hamburg", "Tennessee", "Venetien", "Ohio"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0042 }
            Reponses := array{"Sachsen", "Louisiana", "Alberta", "Ohio"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0043 }
            Reponses := array{"Berlin", "Tennessee", "Sardinien", "Wyoming"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0044 }
            Reponses := array{"Venetien", "Balearen", "South Carolina", "Washington"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0045 }
            Reponses := array{"Toskana", "Galicien", "Virginia", "Tennessee"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0046 }
            Reponses := array{"Wyoming", "Tennessee", "Alberta", "Ontario"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0047 }
            Reponses := array{"Wyoming", "Montana", "Washington", "British Columbia"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0048 }
            Reponses := array{"Franzoesisch-Polynesien", "Virginia", "Berlin", "Balearen"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0049 }
            Reponses := array{"Franzoesisch-Polynesien", "Elsass", "Louisiana", "Virginia"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0050 }
            Reponses := array{"Okzitanien", "Berlin", "Tennessee", "Sachsen"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0051 }
            Reponses := array{"Kanarische Inseln", "Virginia", "Venetien", "Franzoesisch-Polynesien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0052 }
            Reponses := array{"Utah", "Balearen", "Toskana", "Elsass"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0053 }
            Reponses := array{"Hessen", "Aragonien", "Ligurien", "Kalabrien"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0054 }
            Reponses := array{"Madeira", "Asturien", "Azoren", "Kampanien"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0055 }
            Reponses := array{"Friaul", "Kantabrien", "Vermont", "Kalabrien"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0056 }
            Reponses := array{"Nova Scotia", "Lombardei", "Manitoba", "Murcia"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0057 }
            Reponses := array{"Extremadura", "Madeira", "Nebraska", "Azoren"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0058 }
            Reponses := array{"Extremadura", "Aragonien", "Baden-Wuerttemberg", "Nebraska"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0059 }
            Reponses := array{"Maine", "Friaul", "Hessen", "Kansas"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0060 }
            Reponses := array{"Emilia-Romagna", "Thueringen", "Aragonien", "Kansas"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0061 }
            Reponses := array{"Vermont", "Brandenburg", "Delaware", "Michigan"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0062 }
            Reponses := array{"Manitoba", "Apulien", "Kalabrien", "Idaho"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0063 }
            Reponses := array{"Lombardei", "Saskatchewan", "Madeira", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0064 }
            Reponses := array{"Thueringen", "Emilia-Romagna", "Maine", "Nova Scotia"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0065 }
            Reponses := array{"Murcia", "Nunavut", "Emilia-Romagna", "Nebraska"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0066 }
            Reponses := array{"Kalabrien", "Kansas", "Emilia-Romagna", "Brandenburg"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0067 }
            Reponses := array{"Kansas", "Nebraska", "Friaul", "Maine"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0068 }
            Reponses := array{"Idaho", "Michigan", "Piemont", "Friaul"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0069 }
            Reponses := array{"Michigan", "Baden-Wuerttemberg", "Maine", "North Dakota"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0070 }
            Reponses := array{"Thueringen", "Apulien", "Vermont", "Nunavut"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0071 }
            Reponses := array{"Saskatchewan", "Hessen", "Piemont", "Delaware"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0072 }
            Reponses := array{"Idaho", "Arkansas", "Murcia", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0073 }
            Reponses := array{"Oklahoma", "Michigan", "Extremadura", "Hessen"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0074 }
            Reponses := array{"Nunavut", "Lombardei", "Saskatchewan", "Nova Scotia"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0075 }
            Reponses := array{"Asturien", "Oklahoma", "Pennsylvania", "Kalabrien"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0076 }
            Reponses := array{"Murcia", "Aragonien", "Ligurien", "Nova Scotia"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0077 }
            Reponses := array{"Indiana", "Nunavut", "Madeira", "Idaho"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0078 }
            Reponses := array{"Manitoba", "Azoren", "Madeira", "Arkansas"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0079 }
            Reponses := array{"Piemont", "Manitoba", "Kampanien", "Kalabrien"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0080 }
            Reponses := array{"Aragonien", "Maine", "Nova Scotia", "Emilia-Romagna"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0081 }
            Reponses := array{"Nebraska", "Thueringen", "Kampanien", "Baden-Wuerttemberg"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0082 }
            Reponses := array{"Apulien", "Brandenburg", "Madeira", "Kantabrien"}
            BonneReponse := 0
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0083 }
            Reponses := array{"Nebraska", "Baden-Wuerttemberg", "Friaul", "Michigan"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0084 }
            Reponses := array{"Azoren", "Friaul", "Michigan", "Pennsylvania"}
            BonneReponse := 3
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0085 }
            Reponses := array{"Kansas", "Aragonien", "Massachusetts", "Ligurien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0086 }
            Reponses := array{"Brandenburg", "Vermont", "Michigan", "Kantabrien"}
            BonneReponse := 2
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0087 }
            Reponses := array{"Lombardei", "Indiana", "Delaware", "Vermont"}
            BonneReponse := 1
        question:
            Enonce := "Welche Region hat diese Flagge?"
            Image := option{ regions.reg_0088 }
            Reponses := array{"Kantabrien", "Apulien", "North Dakota", "Ligurien"}
            BonneReponse := 2

MakeRegionsQuestionsIT() : []question =
    array:
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0001 }
            Reponses := array{"Hawaii", "Scozia", "Inghilterra", "Nevada"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0002 }
            Reponses := array{"Corsica", "Galles", "Hawaii", "Normandia"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0003 }
            Reponses := array{"Nevada", "Galles", "Bretagna", "Inghilterra"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0004 }
            Reponses := array{"California", "Normandia", "Texas", "Corsica"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0005 }
            Reponses := array{"Andalusia", "Texas", "Groenlandia", "Paesi Baschi"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0006 }
            Reponses := array{"Florida", "Baviera", "California", "Texas"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0007 }
            Reponses := array{"Paesi Baschi", "Nuovo Messico", "Colorado", "Hawaii"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0008 }
            Reponses := array{"Maryland", "Baviera", "Alaska", "Groenlandia"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0009 }
            Reponses := array{"Arizona", "Groenlandia", "Catalogna", "Inghilterra"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0010 }
            Reponses := array{"Baviera", "Arizona", "Nevada", "Andalusia"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0011 }
            Reponses := array{"Inghilterra", "New York", "Groenlandia", "Catalogna"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0012 }
            Reponses := array{"Porto Rico", "Corsica", "Paesi Baschi", "Scozia"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0013 }
            Reponses := array{"Andalusia", "Bretagna", "Colorado", "Maryland"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0014 }
            Reponses := array{"Colorado", "Catalogna", "Arizona", "Bretagna"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0015 }
            Reponses := array{"Nevada", "Quebec", "California", "Corsica"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0016 }
            Reponses := array{"Inghilterra", "Normandia", "Alaska", "Maryland"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0017 }
            Reponses := array{"Texas", "Quebec", "Galles", "Florida"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0018 }
            Reponses := array{"California", "Scozia", "Sicilia", "Andalusia"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0019 }
            Reponses := array{"Bretagna", "Texas", "California", "Colorado"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0020 }
            Reponses := array{"Alaska", "Florida", "Galles", "Nuovo Messico"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0021 }
            Reponses := array{"Maryland", "Florida", "Paesi Baschi", "Arizona"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0022 }
            Reponses := array{"Nuovo Messico", "Catalogna", "Maryland", "Porto Rico"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0023 }
            Reponses := array{"Nevada", "Groenlandia", "Catalogna", "Normandia"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0024 }
            Reponses := array{"Alaska", "New York", "Nevada", "Inghilterra"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0025 }
            Reponses := array{"Bretagna", "Paesi Baschi", "Nevada", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0026 }
            Reponses := array{"Andalusia", "Sicilia", "Georgia", "New York"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0027 }
            Reponses := array{"Occitania", "Toscana", "Sardegna", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0028 }
            Reponses := array{"Isole Canarie", "Occitania", "Galizia", "Berlino"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0029 }
            Reponses := array{"Utah", "Columbia Britannica", "Carolina del Sud", "Isole Canarie"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0030 }
            Reponses := array{"Isole Canarie", "Isole Baleari", "Toscana", "Sassonia"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0031 }
            Reponses := array{"Carolina del Sud", "Isole Canarie", "Sassonia", "Sardegna"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0032 }
            Reponses := array{"Berlino", "Oregon", "Isole Baleari", "Isole Faroe"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0033 }
            Reponses := array{"Columbia Britannica", "Berlino", "Amburgo", "Toscana"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0034 }
            Reponses := array{"Ontario", "Louisiana", "Isole Faroe", "Alsazia"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0035 }
            Reponses := array{"Isole Canarie", "Veneto", "Alberta", "Columbia Britannica"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0036 }
            Reponses := array{"Galizia", "Columbia Britannica", "Toscana", "Alberta"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0037 }
            Reponses := array{"Berlino", "Oregon", "Isole Baleari", "Isole Faroe"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0038 }
            Reponses := array{"Sardegna", "Berlino", "Occitania", "Washington"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0039 }
            Reponses := array{"Wyoming", "Occitania", "Oregon", "Veneto"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0040 }
            Reponses := array{"Berlino", "Ohio", "Utah", "Amburgo"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0041 }
            Reponses := array{"Amburgo", "Tennessee", "Veneto", "Ohio"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0042 }
            Reponses := array{"Sassonia", "Louisiana", "Alberta", "Ohio"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0043 }
            Reponses := array{"Berlino", "Tennessee", "Sardegna", "Wyoming"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0044 }
            Reponses := array{"Veneto", "Isole Baleari", "Carolina del Sud", "Washington"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0045 }
            Reponses := array{"Toscana", "Galizia", "Virginia", "Tennessee"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0046 }
            Reponses := array{"Wyoming", "Tennessee", "Alberta", "Ontario"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0047 }
            Reponses := array{"Wyoming", "Montana", "Washington", "Columbia Britannica"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0048 }
            Reponses := array{"Polinesia Francese", "Virginia", "Berlino", "Isole Baleari"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0049 }
            Reponses := array{"Polinesia Francese", "Alsazia", "Louisiana", "Virginia"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0050 }
            Reponses := array{"Occitania", "Berlino", "Tennessee", "Sassonia"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0051 }
            Reponses := array{"Isole Canarie", "Virginia", "Veneto", "Polinesia Francese"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0052 }
            Reponses := array{"Utah", "Isole Baleari", "Toscana", "Alsazia"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0053 }
            Reponses := array{"Assia", "Aragona", "Liguria", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0054 }
            Reponses := array{"Madera", "Asturie", "Azzorre", "Campania"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0055 }
            Reponses := array{"Friuli", "Cantabria", "Vermont", "Calabria"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0056 }
            Reponses := array{"Nuova Scozia", "Lombardia", "Manitoba", "Murcia"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0057 }
            Reponses := array{"Estremadura", "Madera", "Nebraska", "Azzorre"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0058 }
            Reponses := array{"Estremadura", "Aragona", "Baden-Wuerttemberg", "Nebraska"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0059 }
            Reponses := array{"Maine", "Friuli", "Assia", "Kansas"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0060 }
            Reponses := array{"Emilia-Romagna", "Turingia", "Aragona", "Kansas"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0061 }
            Reponses := array{"Vermont", "Brandeburgo", "Delaware", "Michigan"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0062 }
            Reponses := array{"Manitoba", "Puglia", "Calabria", "Idaho"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0063 }
            Reponses := array{"Lombardia", "Saskatchewan", "Madera", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0064 }
            Reponses := array{"Turingia", "Emilia-Romagna", "Maine", "Nuova Scozia"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0065 }
            Reponses := array{"Murcia", "Nunavut", "Emilia-Romagna", "Nebraska"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0066 }
            Reponses := array{"Calabria", "Kansas", "Emilia-Romagna", "Brandeburgo"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0067 }
            Reponses := array{"Kansas", "Nebraska", "Friuli", "Maine"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0068 }
            Reponses := array{"Idaho", "Michigan", "Piemonte", "Friuli"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0069 }
            Reponses := array{"Michigan", "Baden-Wuerttemberg", "Maine", "Dakota del Nord"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0070 }
            Reponses := array{"Turingia", "Puglia", "Vermont", "Nunavut"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0071 }
            Reponses := array{"Saskatchewan", "Assia", "Piemonte", "Delaware"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0072 }
            Reponses := array{"Idaho", "Arkansas", "Murcia", "Nunavut"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0073 }
            Reponses := array{"Oklahoma", "Michigan", "Estremadura", "Assia"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0074 }
            Reponses := array{"Nunavut", "Lombardia", "Saskatchewan", "Nuova Scozia"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0075 }
            Reponses := array{"Asturie", "Oklahoma", "Pennsylvania", "Calabria"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0076 }
            Reponses := array{"Murcia", "Aragona", "Liguria", "Nuova Scozia"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0077 }
            Reponses := array{"Indiana", "Nunavut", "Madera", "Idaho"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0078 }
            Reponses := array{"Manitoba", "Azzorre", "Madera", "Arkansas"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0079 }
            Reponses := array{"Piemonte", "Manitoba", "Campania", "Calabria"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0080 }
            Reponses := array{"Aragona", "Maine", "Nuova Scozia", "Emilia-Romagna"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0081 }
            Reponses := array{"Nebraska", "Turingia", "Campania", "Baden-Wuerttemberg"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0082 }
            Reponses := array{"Puglia", "Brandeburgo", "Madera", "Cantabria"}
            BonneReponse := 0
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0083 }
            Reponses := array{"Nebraska", "Baden-Wuerttemberg", "Friuli", "Michigan"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0084 }
            Reponses := array{"Azzorre", "Friuli", "Michigan", "Pennsylvania"}
            BonneReponse := 3
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0085 }
            Reponses := array{"Kansas", "Aragona", "Massachusetts", "Liguria"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0086 }
            Reponses := array{"Brandeburgo", "Vermont", "Michigan", "Cantabria"}
            BonneReponse := 2
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0087 }
            Reponses := array{"Lombardia", "Indiana", "Delaware", "Vermont"}
            BonneReponse := 1
        question:
            Enonce := "Quale stato o regione ha questa bandiera?"
            Image := option{ regions.reg_0088 }
            Reponses := array{"Cantabria", "Puglia", "Dakota del Nord", "Liguria"}
            BonneReponse := 2

MakeRegionsQuestions() : []question =
    MakeRegionsQuestionsFR()
