using { /Verse.org/Assets }

# series_bank.verse — Quizz SERIES TV (affiches Wikipedia)
# GENERE — NE PAS EDITER A LA MAIN.

SeriesDiff : []int = array{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 0, 1, 2, 1, 1, 0}

MakeSeriesQuestionsFR() : []question =
    array:
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0001 }
            Reponses := array{"House of the Dragon", "Lost", "Game of Thrones", "The Crown"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0002 }
            Reponses := array{"Prison Break", "The Big Bang Theory", "Mr Bean", "Breaking Bad"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0003 }
            Reponses := array{"Stranger Things", "Scooby-Doo", "Avatar le dernier maitre de l'air", "Breaking Bad"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0004 }
            Reponses := array{"Attack on Titan", "The Big Bang Theory", "Prison Break", "Squid Game"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0005 }
            Reponses := array{"Scooby-Doo", "Peaky Blinders", "Squid Game", "Looney Tunes"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0006 }
            Reponses := array{"Squid Game", "Prison Break", "The Witcher", "Dexter"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0007 }
            Reponses := array{"Lost", "The Crown", "Stranger Things", "Naruto"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0008 }
            Reponses := array{"Family Guy", "Avatar le dernier maitre de l'air", "Stranger Things", "House of the Dragon"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0009 }
            Reponses := array{"Peaky Blinders", "Avatar le dernier maitre de l'air", "Prison Break", "Pokemon"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0010 }
            Reponses := array{"Attack on Titan", "Family Guy", "Game of Thrones", "Lost"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0011 }
            Reponses := array{"Breaking Bad", "Dexter", "Peaky Blinders", "Prison Break"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0012 }
            Reponses := array{"The Big Bang Theory", "Dexter", "Sherlock", "House of the Dragon"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0013 }
            Reponses := array{"Sherlock", "House of the Dragon", "Stranger Things", "Mr Bean"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0014 }
            Reponses := array{"Peaky Blinders", "The Simpsons", "Squid Game", "Breaking Bad"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0015 }
            Reponses := array{"Game of Thrones", "Naruto", "SpongeBob SquarePants", "South Park"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0016 }
            Reponses := array{"Dexter", "Family Guy", "The Simpsons", "The Crown"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0017 }
            Reponses := array{"South Park", "SpongeBob SquarePants", "The Simpsons", "Mr Bean"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0018 }
            Reponses := array{"Attack on Titan", "The Simpsons", "Pokemon", "SpongeBob SquarePants"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0019 }
            Reponses := array{"Breaking Bad", "Dexter", "Naruto", "Sherlock"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0020 }
            Reponses := array{"Avatar le dernier maitre de l'air", "The Witcher", "Attack on Titan", "Lost"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0021 }
            Reponses := array{"SpongeBob SquarePants", "One Piece", "Looney Tunes", "Family Guy"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0022 }
            Reponses := array{"How I Met Your Mother", "Death Note", "Les Pierrafeu", "Les Experts"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0023 }
            Reponses := array{"Fargo", "Better Call Saul", "Gomorra", "Westworld"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0024 }
            Reponses := array{"Narcos", "The Umbrella Academy", "Riverdale", "Buffy"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0025 }
            Reponses := array{"Le Prince de Bel-Air", "Charmed", "Sex Education", "The Boys"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0026 }
            Reponses := array{"Chernobyl", "Doraemon", "Cobra Kai", "Vikings"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0027 }
            Reponses := array{"The Queen's Gambit", "Fairy Tail", "Doraemon", "Westworld"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0028 }
            Reponses := array{"Chernobyl", "Les Experts", "The Umbrella Academy", "Sex Education"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0029 }
            Reponses := array{"Vikings", "Death Note", "Bleach", "Fargo"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0030 }
            Reponses := array{"Buffy", "Gomorra", "True Detective", "Les Pierrafeu"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0031 }
            Reponses := array{"Buffy", "Sex Education", "Les Pierrafeu", "Chernobyl"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0032 }
            Reponses := array{"True Detective", "The Handmaid's Tale", "Doctor Who", "Tortues Ninja"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0033 }
            Reponses := array{"Cobra Kai", "Buffy", "True Detective", "Ted Lasso"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0034 }
            Reponses := array{"Cobra Kai", "Tortues Ninja", "Death Note", "Fargo"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0035 }
            Reponses := array{"Westworld", "Gomorra", "The Queen's Gambit", "True Detective"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0036 }
            Reponses := array{"Sex Education", "Les Pierrafeu", "Charmed", "Gossip Girl"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0037 }
            Reponses := array{"Buffy", "Gomorra", "The Queen's Gambit", "Narcos"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0038 }
            Reponses := array{"Demon Slayer", "Better Call Saul", "Death Note", "Gossip Girl"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0039 }
            Reponses := array{"Riverdale", "The Queen's Gambit", "Gomorra", "Chernobyl"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0040 }
            Reponses := array{"The Handmaid's Tale", "My Hero Academia", "Buffy", "Les Experts"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0041 }
            Reponses := array{"Sex Education", "Demon Slayer", "Les Pierrafeu", "Charmed"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0042 }
            Reponses := array{"The Boys", "Death Note", "Cobra Kai", "Riverdale"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0043 }
            Reponses := array{"Fullmetal Alchemist", "Death Note", "Le Prince de Bel-Air", "The Handmaid's Tale"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0044 }
            Reponses := array{"The Wire", "Arrested Development", "Heroes", "Battlestar Galactica"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0045 }
            Reponses := array{"24 heures chrono", "Mad Men", "Boardwalk Empire", "Heroes"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0046 }
            Reponses := array{"Oz", "Seinfeld", "Evangelion", "Boardwalk Empire"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0047 }
            Reponses := array{"Hunter x Hunter", "Oz", "Frasier", "Mad Men"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0048 }
            Reponses := array{"Cheers", "X-Files", "Oz", "The Wire"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0049 }
            Reponses := array{"X-Files", "Cheers", "Malcolm", "Deux flics a Miami"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0050 }
            Reponses := array{"Arrested Development", "The Shield", "Urgences", "Mad Men"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0051 }
            Reponses := array{"24 heures chrono", "Homeland", "The Americans", "Brooklyn Nine-Nine"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0052 }
            Reponses := array{"Oz", "Heroes", "Deadwood", "Malcolm"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0053 }
            Reponses := array{"Malcolm", "Battlestar Galactica", "Oz", "Urgences"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0054 }
            Reponses := array{"Mariés deux enfants", "Cowboy Bebop", "Malcolm", "Deadwood"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0055 }
            Reponses := array{"Boardwalk Empire", "Oz", "Battlestar Galactica", "The Wire"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0056 }
            Reponses := array{"Battlestar Galactica", "Malcolm", "The Shield", "Arrested Development"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0057 }
            Reponses := array{"Heroes", "X-Files", "Urgences", "Oz"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0058 }
            Reponses := array{"Philadelphia", "Seinfeld", "Evangelion", "Gundam"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0059 }
            Reponses := array{"Malcolm", "Mariés deux enfants", "The Shield", "Arrested Development"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0060 }
            Reponses := array{"Boardwalk Empire", "Arrested Development", "Battlestar Galactica", "Frasier"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0061 }
            Reponses := array{"Brooklyn Nine-Nine", "Homeland", "Berserk", "The Wire"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0062 }
            Reponses := array{"The Americans", "Homeland", "Seinfeld", "Hunter x Hunter"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0063 }
            Reponses := array{"Battlestar Galactica", "Arrested Development", "The Wire", "The Americans"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0064 }
            Reponses := array{"Cowboy Bebop", "Jujutsu Kaisen", "Hunter x Hunter", "Philadelphia"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0065 }
            Reponses := array{"Battlestar Galactica", "Hunter x Hunter", "X-Files", "Evangelion"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0066 }
            Reponses := array{"Berserk", "Mariés deux enfants", "The Wire", "Malcolm"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0067 }
            Reponses := array{"The Wire", "Mad Men", "X-Files", "Hunter x Hunter"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0068 }
            Reponses := array{"Heroes", "Seinfeld", "The Americans", "Jujutsu Kaisen"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0069 }
            Reponses := array{"SpongeBob SquarePants", "Avatar le dernier maitre de l'air", "Prison Break", "Squid Game"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0070 }
            Reponses := array{"Pokemon", "One Piece", "Family Guy", "Scooby-Doo"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0071 }
            Reponses := array{"Better Call Saul", "The Boys", "Bleach", "Sex Education"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0072 }
            Reponses := array{"My Hero Academia", "Demon Slayer", "Fairy Tail", "Gossip Girl"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0073 }
            Reponses := array{"The Umbrella Academy", "Buffy", "Sailor Moon", "Westworld"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0074 }
            Reponses := array{"Doraemon", "Narcos", "Doctor Who", "Charmed"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0075 }
            Reponses := array{"Boardwalk Empire", "Gundam", "Agence tous risques", "Hunter x Hunter"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0076 }
            Reponses := array{"Deadwood", "Battlestar Galactica", "Philadelphia", "Inuyasha"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0077 }
            Reponses := array{"Doraemon", "Charmed", "Fullmetal Alchemist", "Doctor Who"}
            BonneReponse := 3
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0078 }
            Reponses := array{"The Wire", "Agence tous risques", "Jujutsu Kaisen", "Arrested Development"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0079 }
            Reponses := array{"Deux flics a Miami", "Hunter x Hunter", "Agence tous risques", "Frasier"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0080 }
            Reponses := array{"Demon Slayer", "Buffy", "Riverdale", "Sex Education"}
            BonneReponse := 1
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0081 }
            Reponses := array{"Charmed", "Fairy Tail", "Bleach", "Fullmetal Alchemist"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0082 }
            Reponses := array{"Les Experts", "Tortues Ninja", "Fairy Tail", "Sailor Moon"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0083 }
            Reponses := array{"The Simpsons", "Sherlock", "Mr Bean", "Game of Thrones"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0084 }
            Reponses := array{"Le Prince de Bel-Air", "Doraemon", "True Detective", "The Boys"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0085 }
            Reponses := array{"Mariés deux enfants", "Heroes", "Urgences", "Seinfeld"}
            BonneReponse := 0
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0086 }
            Reponses := array{"Charmed", "Chernobyl", "Tortues Ninja", "Gomorra"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0087 }
            Reponses := array{"My Hero Academia", "The Handmaid's Tale", "Les Pierrafeu", "Better Call Saul"}
            BonneReponse := 2
        question:
            Enonce := "Quelle est cette serie ?"
            Image := option{ series.ser_0088 }
            Reponses := array{"Pokemon", "Looney Tunes", "Squid Game", "SpongeBob SquarePants"}
            BonneReponse := 1

MakeSeriesQuestions() : []question =
    MakeSeriesQuestionsFR()

MakeSeriesQuestionsEN() : []question =
    Base := MakeSeriesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "What TV series is this?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeSeriesQuestionsES() : []question =
    Base := MakeSeriesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Que serie es esta?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeSeriesQuestionsDE() : []question =
    Base := MakeSeriesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Welche Serie ist das?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }

MakeSeriesQuestionsIT() : []question =
    Base := MakeSeriesQuestionsFR()
    for (Q : Base):
        question{ Enonce := "Quale serie e questa?", Image := Q.Image, Reponses := Q.Reponses, BonneReponse := Q.BonneReponse }
