#!/usr/bin/env python3
# ============================================================
#  build_animaux.py — Quizz "Animaux" (~170 especes, photos Wikipedia)
#  Table ecrite a la main : (titre_wiki_EN, FR, EN, ES, DE, IT, palier)
#  0 = tres connu, 1 = connu, 2 = obscur. Photos via REST Wikipedia.
#  Sortie : animaux/ani_0001.png... + verse/animaux_bank.verse
# ============================================================
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from quiz_common import build_images, emit_bank

BANK_ONLY = "--bank-only" in sys.argv
ROOT = "D:/QuizzFortnite"

# (wiki_EN, FR, EN, ES, DE, IT, palier)
A = [
 ("Lion","Lion","Lion","Leon","Loewe","Leone",0),
 ("Tiger","Tigre","Tiger","Tigre","Tiger","Tigre",0),
 ("African bush elephant","Elephant","Elephant","Elefante","Elefant","Elefante",0),
 ("Giraffe","Girafe","Giraffe","Jirafa","Giraffe","Giraffa",0),
 ("Plains zebra","Zebre","Zebra","Cebra","Zebra","Zebra",0),
 ("Gorilla","Gorille","Gorilla","Gorila","Gorilla","Gorilla",0),
 ("Chimpanzee","Chimpanze","Chimpanzee","Chimpance","Schimpanse","Scimpanze",0),
 ("Wolf","Loup","Wolf","Lobo","Wolf","Lupo",0),
 ("Red fox","Renard","Fox","Zorro","Fuchs","Volpe",0),
 ("Brown bear","Ours brun","Brown bear","Oso pardo","Braunbaer","Orso bruno",0),
 ("Polar bear","Ours polaire","Polar bear","Oso polar","Eisbaer","Orso polare",0),
 ("Giant panda","Panda geant","Giant panda","Panda gigante","Grosser Panda","Panda gigante",0),
 ("Koala","Koala","Koala","Koala","Koala","Koala",0),
 ("Kangaroo","Kangourou","Kangaroo","Canguro","Kaenguru","Canguro",0),
 ("Bottlenose dolphin","Dauphin","Dolphin","Delfin","Delfin","Delfino",0),
 ("Blue whale","Baleine bleue","Blue whale","Ballena azul","Blauwal","Balenottera azzurra",0),
 ("Great white shark","Requin blanc","Great white shark","Tiburon blanco","Weisser Hai","Squalo bianco",0),
 ("Golden eagle","Aigle royal","Golden eagle","Aguila real","Steinadler","Aquila reale",0),
 ("Owl","Hibou","Owl","Buho","Eule","Gufo",0),
 ("Parrot","Perroquet","Parrot","Loro","Papagei","Pappagallo",0),
 ("Emperor penguin","Manchot empereur","Emperor penguin","Pinguino emperador","Kaiserpinguin","Pinguino imperatore",0),
 ("Flamingo","Flamant rose","Flamingo","Flamenco","Flamingo","Fenicottero",0),
 ("Common ostrich","Autruche","Ostrich","Avestruz","Strauss","Struzzo",0),
 ("Nile crocodile","Crocodile","Crocodile","Cocodrilo","Krokodil","Coccodrillo",0),
 ("King cobra","Cobra royal","King cobra","Cobra real","Koenigskobra","Cobra reale",0),
 ("Sea turtle","Tortue de mer","Sea turtle","Tortuga marina","Meeresschildkroete","Tartaruga marina",0),
 ("Frog","Grenouille","Frog","Rana","Frosch","Rana",0),
 ("Butterfly","Papillon","Butterfly","Mariposa","Schmetterling","Farfalla",0),
 ("Western honey bee","Abeille","Bee","Abeja","Biene","Ape",0),
 ("Ant","Fourmi","Ant","Hormiga","Ameise","Formica",0),
 ("Spider","Araignee","Spider","Arana","Spinne","Ragno",0),
 ("Horse","Cheval","Horse","Caballo","Pferd","Cavallo",0),
 ("Cattle","Vache","Cow","Vaca","Kuh","Mucca",0),
 ("Pig","Cochon","Pig","Cerdo","Schwein","Maiale",0),
 ("Sheep","Mouton","Sheep","Oveja","Schaf","Pecora",0),
 ("Goat","Chevre","Goat","Cabra","Ziege","Capra",0),
 ("Rabbit","Lapin","Rabbit","Conejo","Kaninchen","Coniglio",0),
 ("Red squirrel","Ecureuil","Squirrel","Ardilla","Eichhoernchen","Scoiattolo",0),
 ("Hedgehog","Herisson","Hedgehog","Erizo","Igel","Riccio",0),
 ("Bat","Chauve-souris","Bat","Murcielago","Fledermaus","Pipistrello",0),
 ("Hippopotamus","Hippopotame","Hippopotamus","Hipopotamo","Flusspferd","Ippopotamo",0),
 ("Rhinoceros","Rhinoceros","Rhinoceros","Rinoceronte","Nashorn","Rinoceronte",0),
 ("Cheetah","Guepard","Cheetah","Guepardo","Gepard","Ghepardo",0),
 ("Leopard","Leopard","Leopard","Leopardo","Leopard","Leopardo",0),
 ("Dromedary","Dromadaire","Camel","Camello","Kamel","Cammello",0),
 ("Donkey","Ane","Donkey","Burro","Esel","Asino",0),
 ("Deer","Cerf","Deer","Ciervo","Hirsch","Cervo",0),
 ("Snail","Escargot","Snail","Caracol","Schnecke","Lumaca",0),
 ("Coccinellidae","Coccinelle","Ladybug","Mariquita","Marienkaefer","Coccinella",0),
 ("Octopus","Poulpe","Octopus","Pulpo","Krake","Polpo",0),
 ("Peafowl","Paon","Peacock","Pavo real","Pfau","Pavone",0),
 ("Mute swan","Cygne","Swan","Cisne","Schwan","Cigno",0),
 ("House mouse","Souris","Mouse","Raton","Maus","Topo",0),
 # ---- palier 1 : connus ----
 ("Eurasian lynx","Lynx","Lynx","Lince","Luchs","Lince",1),
 ("Cougar","Puma","Cougar","Puma","Puma","Puma",1),
 ("Jaguar","Jaguar","Jaguar","Jaguar","Jaguar","Giaguaro",1),
 ("Spotted hyena","Hyene","Hyena","Hiena","Hyaene","Iena",1),
 ("Meerkat","Suricate","Meerkat","Suricata","Erdmaennchen","Suricato",1),
 ("Sloth","Paresseux","Sloth","Perezoso","Faultier","Bradipo",1),
 ("Armadillo","Tatou","Armadillo","Armadillo","Guerteltier","Armadillo",1),
 ("Giant anteater","Fourmilier","Anteater","Oso hormiguero","Ameisenbaer","Formichiere",1),
 ("Beaver","Castor","Beaver","Castor","Biber","Castoro",1),
 ("Otter","Loutre","Otter","Nutria","Otter","Lontra",1),
 ("European badger","Blaireau","Badger","Tejon","Dachs","Tasso",1),
 ("Raccoon","Raton laveur","Raccoon","Mapache","Waschbaer","Procione",1),
 ("Skunk","Mouffette","Skunk","Mofeta","Stinktier","Moffetta",1),
 ("Llama","Lama","Llama","Llama","Lama","Lama",1),
 ("Alpaca","Alpaga","Alpaca","Alpaca","Alpaka","Alpaca",1),
 ("American bison","Bison","Bison","Bisonte","Bison","Bisonte",1),
 ("Moose","Elan","Moose","Alce","Elch","Alce",1),
 ("Reindeer","Renne","Reindeer","Reno","Rentier","Renna",1),
 ("Wild boar","Sanglier","Wild boar","Jabali","Wildschwein","Cinghiale",1),
 ("Walrus","Morse","Walrus","Morsa","Walross","Tricheco",1),
 ("Harbor seal","Phoque","Seal","Foca","Robbe","Foca",1),
 ("Orca","Orque","Orca","Orca","Schwertwal","Orca",1),
 ("Narwhal","Narval","Narwhal","Narval","Narwal","Narvalo",1),
 ("Sperm whale","Cachalot","Sperm whale","Cachalote","Pottwal","Capodoglio",1),
 ("Manta ray","Raie manta","Manta ray","Mantarraya","Mantarochen","Manta",1),
 ("Seahorse","Hippocampe","Seahorse","Caballito de mar","Seepferdchen","Cavalluccio marino",1),
 ("Jellyfish","Meduse","Jellyfish","Medusa","Qualle","Medusa",1),
 ("Squid","Calamar","Squid","Calamar","Kalmar","Calamaro",1),
 ("Lobster","Homard","Lobster","Bogavante","Hummer","Astice",1),
 ("Crab","Crabe","Crab","Cangrejo","Krabbe","Granchio",1),
 ("Starfish","Etoile de mer","Starfish","Estrella de mar","Seestern","Stella marina",1),
 ("Swordfish","Espadon","Swordfish","Pez espada","Schwertfisch","Pesce spada",1),
 ("Tuna","Thon","Tuna","Atun","Thunfisch","Tonno",1),
 ("Salmon","Saumon","Salmon","Salmon","Lachs","Salmone",1),
 ("Piranha","Piranha","Piranha","Pirana","Piranha","Piranha",1),
 ("Eel","Anguille","Eel","Anguila","Aal","Anguilla",1),
 ("Toco toucan","Toucan","Toucan","Tucan","Tukan","Tucano",1),
 ("Hummingbird","Colibri","Hummingbird","Colibri","Kolibri","Colibri",1),
 ("Pelican","Pelican","Pelican","Pelicano","Pelikan","Pellicano",1),
 ("White stork","Cigogne","Stork","Ciguena","Storch","Cicogna",1),
 ("Grey heron","Heron","Heron","Garza","Reiher","Airone",1),
 ("Common raven","Corbeau","Raven","Cuervo","Rabe","Corvo",1),
 ("Eurasian magpie","Pie","Magpie","Urraca","Elster","Gazza",1),
 ("European robin","Rouge-gorge","Robin","Petirrojo","Rotkehlchen","Pettirosso",1),
 ("Common kingfisher","Martin-pecheur","Kingfisher","Martin pescador","Eisvogel","Martin pescatore",1),
 ("Peregrine falcon","Faucon pelerin","Peregrine falcon","Halcon peregrino","Wanderfalke","Falco pellegrino",1),
 ("Vulture","Vautour","Vulture","Buitre","Geier","Avvoltoio",1),
 ("Andean condor","Condor","Condor","Condor","Kondor","Condor",1),
 ("Albatross","Albatros","Albatross","Albatros","Albatros","Albatro",1),
 ("Gull","Mouette","Seagull","Gaviota","Moewe","Gabbiano",1),
 ("Chameleon","Cameleon","Chameleon","Camaleon","Chamaeleon","Camaleonte",1),
 ("Green iguana","Iguane","Iguana","Iguana","Leguan","Iguana",1),
 ("Gecko","Gecko","Gecko","Geco","Gecko","Geco",1),
 ("Komodo dragon","Dragon de Komodo","Komodo dragon","Dragon de Komodo","Komodowaran","Drago di Komodo",1),
 ("Boa constrictor","Boa","Boa","Boa","Boa","Boa",1),
 ("Pythonidae","Python","Python","Piton","Python","Pitone",1),
 ("Viperidae","Vipere","Viper","Vibora","Viper","Vipera",1),
 ("Fire salamander","Salamandre","Salamander","Salamandra","Salamander","Salamandra",1),
 ("Axolotl","Axolotl","Axolotl","Ajolote","Axolotl","Axolotl",1),
 ("Hamster","Hamster","Hamster","Hamster","Hamster","Criceto",1),
 ("Ferret","Furet","Ferret","Huron","Frettchen","Furetto",1),
 ("Mole (animal)","Taupe","Mole","Topo europeo","Maulwurf","Talpa",1),
 ("Porcupine","Porc-epic","Porcupine","Puercoespin","Stachelschwein","Istrice",1),
 ("Gazelle","Gazelle","Gazelle","Gacela","Gazelle","Gazzella",1),
 ("Mantis","Mante religieuse","Praying mantis","Mantis religiosa","Gottesanbeterin","Mantide religiosa",1),
 ("Dragonfly","Libellule","Dragonfly","Libelula","Libelle","Libellula",1),
 ("Scorpion","Scorpion","Scorpion","Escorpion","Skorpion","Scorpione",1),
 ("Red panda","Panda roux","Red panda","Panda rojo","Kleiner Panda","Panda rosso",1),
 ("Snow leopard","Panthere des neiges","Snow leopard","Leopardo de las nieves","Schneeleopard","Leopardo delle nevi",1),
 ("Mandrill","Mandrill","Mandrill","Mandril","Mandrill","Mandrillo",1),
 ("Ring-tailed lemur","Lemurien","Lemur","Lemur","Lemur","Lemure",1),
 ("Orangutan","Orang-outan","Orangutan","Orangutan","Orang-Utan","Orango",1),
 ("Gibbon","Gibbon","Gibbon","Gibon","Gibbon","Gibbone",1),
 # ---- palier 2 : obscurs ----
 ("Okapi","Okapi","Okapi","Okapi","Okapi","Okapi",2),
 ("Tapir","Tapir","Tapir","Tapir","Tapir","Tapiro",2),
 ("Aardvark","Orycterope","Aardvark","Cerdo hormiguero","Erdferkel","Oritteropo",2),
 ("Pangolin","Pangolin","Pangolin","Pangolin","Schuppentier","Pangolino",2),
 ("Echidna","Echidne","Echidna","Equidna","Schnabeligel","Echidna",2),
 ("Platypus","Ornithorynque","Platypus","Ornitorrinco","Schnabeltier","Ornitorinco",2),
 ("Quokka","Quokka","Quokka","Quokka","Quokka","Quokka",2),
 ("Wombat","Wombat","Wombat","Wombat","Wombat","Vombato",2),
 ("Tasmanian devil","Diable de Tasmanie","Tasmanian devil","Demonio de Tasmania","Beutelteufel","Diavolo della Tasmania",2),
 ("Dingo","Dingo","Dingo","Dingo","Dingo","Dingo",2),
 ("Fennec fox","Fennec","Fennec fox","Zorro fenec","Fennek","Fennec",2),
 ("Caracal","Caracal","Caracal","Caracal","Karakal","Caracal",2),
 ("Serval","Serval","Serval","Serval","Serval","Servalo",2),
 ("Ocelot","Ocelot","Ocelot","Ocelote","Ozelot","Ocelot",2),
 ("Binturong","Binturong","Binturong","Binturong","Binturong","Binturong",2),
 ("Mongoose","Mangouste","Mongoose","Mangosta","Manguste","Mangusta",2),
 ("Tarsier","Tarsier","Tarsier","Tarsero","Koboldmaki","Tarsio",2),
 ("Capybara","Capybara","Capybara","Capibara","Wasserschwein","Capibara",2),
 ("Chinchilla","Chinchilla","Chinchilla","Chinchilla","Chinchilla","Cincilla",2),
 ("Jerboa","Gerboise","Jerboa","Jerbo","Springmaus","Gerboa",2),
 ("Lemming","Lemming","Lemming","Lemming","Lemming","Lemming",2),
 ("Saiga antelope","Saiga","Saiga","Saiga","Saigaantilope","Saiga",2),
 ("Wildebeest","Gnou","Wildebeest","Nu","Gnu","Gnu",2),
 ("Impala","Impala","Impala","Impala","Impala","Impala",2),
 ("Springbok","Springbok","Springbok","Springbok","Springbock","Springbok",2),
 ("Greater kudu","Koudou","Kudu","Kudu","Kudu","Kudu",2),
 ("Addax","Addax","Addax","Addax","Addax","Addax",2),
 ("Alpine ibex","Bouquetin","Ibex","Ibice","Steinbock","Stambecco",2),
 ("Chamois","Chamois","Chamois","Rebeco","Gaemse","Camoscio",2),
 ("Mouflon","Mouflon","Mouflon","Muflon","Mufflon","Muflone",2),
 ("Domestic yak","Yack","Yak","Yak","Yak","Yak",2),
 ("Dik-dik","Dik-dik","Dik-dik","Dik-dik","Dikdik","Dik-dik",2),
 ("Gerenuk","Gerenuk","Gerenuk","Gerenuc","Giraffengazelle","Gerenuk",2),
 ("Kakapo","Kakapo","Kakapo","Kakapo","Kakapo","Kakapo",2),
 ("Kiwi (bird)","Kiwi","Kiwi","Kiwi","Kiwi","Kiwi",2),
 ("Cassowary","Casoar","Cassowary","Casuario","Kasuar","Casuario",2),
 ("Emu","Emeu","Emu","Emu","Emu","Emu",2),
 ("Rhea (bird)","Nandou","Rhea","Nandu","Nandu","Nandu",2),
 ("Snowy owl","Harfang des neiges","Snowy owl","Buho nival","Schneeeule","Civetta delle nevi",2),
 ("Resplendent quetzal","Quetzal","Quetzal","Quetzal","Quetzal","Quetzal",2),
 ("Shoebill","Bec-en-sabot","Shoebill","Picozapato","Schuhschnabel","Becco a scarpa",2),
 ("Frigatebird","Fregate","Frigatebird","Fragata","Fregattvogel","Fregata",2),
 ("Northern gannet","Fou de Bassan","Gannet","Alcatraz","Basstoelpel","Sula",2),
 ("Atlantic puffin","Macareux","Puffin","Frailecillo","Papageitaucher","Pulcinella di mare",2),
 ("Gharial","Gavial","Gharial","Gavial","Gangesgavial","Gaviale",2),
 ("Green anaconda","Anaconda","Anaconda","Anaconda","Anakonda","Anaconda",2),
 ("Black mamba","Mamba noir","Black mamba","Mamba negra","Schwarze Mamba","Mamba nero",2),
 ("Inland taipan","Taipan","Taipan","Taipan","Taipan","Taipan",2),
 ("Leafy seadragon","Dragon de mer feuillu","Leafy seadragon","Dragon de mar foliaceo","Grosser Fetzenfisch","Drago foglia",2),
 ("Ocean sunfish","Poisson-lune","Sunfish","Pez luna","Mondfisch","Pesce luna",2),
 ("Coelacanth","Coelacanthe","Coelacanth","Celacanto","Quastenflosser","Celacanto",2),
 ("Lamprey","Lamproie","Lamprey","Lamprea","Neunauge","Lampreda",2),
 ("Mantis shrimp","Squille","Mantis shrimp","Camaron mantis","Fangschreckenkrebs","Canocchia",2),
 ("Horseshoe crab","Limule","Horseshoe crab","Cangrejo herradura","Pfeilschwanzkrebs","Limulo",2),
 ("Nautilus","Nautile","Nautilus","Nautilo","Nautilus","Nautilo",2),
 ("Dugong","Dugong","Dugong","Dugongo","Dugong","Dugongo",2),
 ("Manatee","Lamantin","Manatee","Manati","Seekuh","Lamantino",2),
 ("Sun bear","Ours malais","Sun bear","Oso malayo","Malaienbaer","Orso malese",2),
 ("Honey badger","Ratel","Honey badger","Tejon de la miel","Honigdachs","Tasso del miele",2),
 ("Proboscis monkey","Nasique","Proboscis monkey","Mono narigudo","Nasenaffe","Nasica",2),
]

items = [{"id": w, "wiki": w, "tier": t,
          "names": {"FR": fr, "EN": en, "ES": es, "DE": de, "IT": it}}
         for (w, fr, en, es, de, it, t) in A]
print("Animaux :", len(items))

if not BANK_ONLY:
    errs = build_images(items, f"{ROOT}/animaux", "ani")
    if errs:
        print("ERREURS:"); [print("  " + e) for e in errs]; sys.exit(1)
    print("OK : images animaux/")

ENONCE = {"FR": "Quel est cet animal ?", "EN": "What animal is this?",
          "ES": "Que animal es este?", "DE": "Welches Tier ist das?",
          "IT": "Quale animale e questo?"}
emit_bank(f"{ROOT}/verse/animaux_bank.verse",
          "animaux_bank.verse — Quizz ANIMAUX (photos Wikipedia, CC)",
          "AnimauxDiff", "Animaux", ENONCE, items, shared=False, seed_prefix="animaux",
          img_ref_of=lambda i: "animaux.ani_%04d" % (i + 1))
t = [it["tier"] for it in items]
print("Paliers : %d/%d/%d" % (t.count(0), t.count(1), t.count(2)))
