# Donnees allemandes partagees par build_flags.py et build_capitals.py
# DE : nom allemand du pays (ASCII : ae/oe/ue/ss pour les umlauts — convention du projet) ;
# CAP_DE : capitale allemande SI differente du francais.

DE = {
    "fr": "Frankreich", "de": "Deutschland", "it": "Italien", "es": "Spanien", "pt": "Portugal",
    "gb": "Vereinigtes Koenigreich", "ie": "Irland", "be": "Belgien", "nl": "Niederlande",
    "lu": "Luxemburg", "ch": "Schweiz", "at": "Oesterreich", "mc": "Monaco",
    "ad": "Andorra", "li": "Liechtenstein", "sm": "San Marino", "va": "Vatikanstadt",
    "mt": "Malta", "is": "Island", "no": "Norwegen", "se": "Schweden", "dk": "Daenemark",
    "fi": "Finnland", "pl": "Polen", "cz": "Tschechien", "sk": "Slowakei", "hu": "Ungarn",
    "si": "Slowenien", "hr": "Kroatien", "ba": "Bosnien und Herzegowina", "rs": "Serbien",
    "me": "Montenegro", "mk": "Nordmazedonien", "al": "Albanien", "gr": "Griechenland",
    "bg": "Bulgarien", "ro": "Rumaenien", "md": "Moldau", "ua": "Ukraine", "by": "Belarus",
    "ru": "Russland", "ee": "Estland", "lv": "Lettland", "lt": "Litauen", "cy": "Zypern",
    "tr": "Tuerkei", "il": "Israel", "ps": "Palaestina", "lb": "Libanon", "sy": "Syrien",
    "jo": "Jordanien", "iq": "Irak", "ir": "Iran", "sa": "Saudi-Arabien", "ye": "Jemen",
    "om": "Oman", "ae": "Vereinigte Arabische Emirate", "qa": "Katar", "bh": "Bahrain",
    "kw": "Kuwait", "ge": "Georgien", "am": "Armenien", "az": "Aserbaidschan",
    "kz": "Kasachstan", "uz": "Usbekistan", "tm": "Turkmenistan", "kg": "Kirgisistan",
    "tj": "Tadschikistan", "af": "Afghanistan", "mn": "Mongolei", "cn": "China",
    "jp": "Japan", "kr": "Suedkorea", "kp": "Nordkorea", "in": "Indien",
    "pk": "Pakistan", "bd": "Bangladesch", "lk": "Sri Lanka", "np": "Nepal",
    "bt": "Bhutan", "mv": "Malediven", "mm": "Myanmar", "th": "Thailand", "la": "Laos",
    "kh": "Kambodscha", "vn": "Vietnam", "my": "Malaysia", "sg": "Singapur",
    "id": "Indonesien", "bn": "Brunei", "ph": "Philippinen", "tl": "Osttimor",
    "au": "Australien", "nz": "Neuseeland", "pg": "Papua-Neuguinea", "fj": "Fidschi",
    "sb": "Salomonen", "vu": "Vanuatu", "ws": "Samoa", "to": "Tonga",
    "tv": "Tuvalu", "ki": "Kiribati", "nr": "Nauru", "pw": "Palau", "fm": "Mikronesien",
    "mh": "Marshallinseln", "ma": "Marokko", "dz": "Algerien", "tn": "Tunesien",
    "ly": "Libyen", "eg": "Aegypten", "sd": "Sudan", "ss": "Suedsudan", "et": "Aethiopien",
    "er": "Eritrea", "dj": "Dschibuti", "so": "Somalia", "ke": "Kenia", "ug": "Uganda",
    "tz": "Tansania", "rw": "Ruanda", "bi": "Burundi", "cd": "DR Kongo", "cg": "Kongo",
    "ga": "Gabun", "gq": "Aequatorialguinea", "cm": "Kamerun",
    "cf": "Zentralafrikanische Republik", "td": "Tschad", "ne": "Niger", "ng": "Nigeria",
    "bj": "Benin", "tg": "Togo", "gh": "Ghana", "ci": "Elfenbeinkueste", "lr": "Liberia",
    "sl": "Sierra Leone", "gn": "Guinea", "gw": "Guinea-Bissau", "sn": "Senegal",
    "gm": "Gambia", "ml": "Mali", "bf": "Burkina Faso", "mr": "Mauretanien",
    "cv": "Kap Verde", "st": "Sao Tome und Principe", "ao": "Angola", "zm": "Sambia",
    "zw": "Simbabwe", "mw": "Malawi", "mz": "Mosambik", "mg": "Madagaskar",
    "km": "Komoren", "mu": "Mauritius", "sc": "Seychellen", "za": "Suedafrika",
    "na": "Namibia", "bw": "Botswana", "ls": "Lesotho", "sz": "Eswatini",
    "us": "Vereinigte Staaten", "ca": "Kanada", "mx": "Mexiko", "gt": "Guatemala",
    "bz": "Belize", "hn": "Honduras", "sv": "El Salvador", "ni": "Nicaragua",
    "cr": "Costa Rica", "pa": "Panama", "bs": "Bahamas", "cu": "Kuba", "jm": "Jamaika",
    "ht": "Haiti", "do": "Dominikanische Republik", "kn": "St. Kitts und Nevis",
    "ag": "Antigua und Barbuda", "dm": "Dominica", "lc": "St. Lucia",
    "vc": "St. Vincent", "bb": "Barbados", "gd": "Grenada",
    "tt": "Trinidad und Tobago", "co": "Kolumbien", "ve": "Venezuela", "gy": "Guyana",
    "sr": "Suriname", "ec": "Ecuador", "pe": "Peru", "br": "Brasilien", "bo": "Bolivien",
    "py": "Paraguay", "uy": "Uruguay", "cl": "Chile", "ar": "Argentinien",
}

# capitales DE uniquement si differentes du francais (base FR ascii)
CAP_DE = {
    "pt": "Lissabon", "gb": "London", "be": "Bruessel", "ch": "Bern", "at": "Wien",
    "ad": "Andorra la Vella", "sm": "San Marino", "va": "Vatikanstadt",
    "mt": "Valletta", "dk": "Kopenhagen", "it": "Rom",
    "pl": "Warschau", "cz": "Prag", "rs": "Belgrad", "gr": "Athen",
    "ro": "Bukarest", "ua": "Kiew", "ru": "Moskau", "cy": "Nikosia",
    "lb": "Beirut", "sy": "Damaskus", "sa": "Riad", "om": "Maskat",
    "ae": "Abu Dhabi", "kw": "Kuwait-Stadt", "ge": "Tiflis", "am": "Eriwan",
    "az": "Baku", "uz": "Taschkent", "tm": "Aschgabat", "kg": "Bischkek",
    "tj": "Duschanbe", "af": "Kabul", "cn": "Peking", "kp": "Pjoengjang",
    "jp": "Tokio", "in": "Neu-Delhi", "bd": "Dhaka", "np": "Kathmandu",
    "bt": "Thimphu", "sg": "Singapur", "ph": "Manila", "vu": "Port Vila",
    "dz": "Algier", "ly": "Tripolis", "eg": "Kairo", "sd": "Khartum",
    "ss": "Juba", "et": "Addis Abeba", "dj": "Dschibuti", "so": "Mogadischu",
    "cm": "Jaunde", "mu": "Port Louis", "st": "Sao Tome",
    "mx": "Mexiko-Stadt", "gt": "Guatemala-Stadt", "pa": "Panama-Stadt",
    "cu": "Havanna", "do": "Santo Domingo", "gd": "Saint George's",
    "tt": "Port of Spain",
}
