# Donnees italiennes partagees par build_flags.py et build_capitals.py
# IT : nom italien du pays (ASCII, sans accents — convention du projet) ;
# CAP_IT : capitale italienne SI differente du francais.

IT = {
    "fr": "Francia", "de": "Germania", "it": "Italia", "es": "Spagna", "pt": "Portogallo",
    "gb": "Regno Unito", "ie": "Irlanda", "be": "Belgio", "nl": "Paesi Bassi",
    "lu": "Lussemburgo", "ch": "Svizzera", "at": "Austria", "mc": "Monaco",
    "ad": "Andorra", "li": "Liechtenstein", "sm": "San Marino", "va": "Citta del Vaticano",
    "mt": "Malta", "is": "Islanda", "no": "Norvegia", "se": "Svezia", "dk": "Danimarca",
    "fi": "Finlandia", "pl": "Polonia", "cz": "Cechia", "sk": "Slovacchia", "hu": "Ungheria",
    "si": "Slovenia", "hr": "Croazia", "ba": "Bosnia ed Erzegovina", "rs": "Serbia",
    "me": "Montenegro", "mk": "Macedonia del Nord", "al": "Albania", "gr": "Grecia",
    "bg": "Bulgaria", "ro": "Romania", "md": "Moldavia", "ua": "Ucraina", "by": "Bielorussia",
    "ru": "Russia", "ee": "Estonia", "lv": "Lettonia", "lt": "Lituania", "cy": "Cipro",
    "tr": "Turchia", "il": "Israele", "ps": "Palestina", "lb": "Libano", "sy": "Siria",
    "jo": "Giordania", "iq": "Iraq", "ir": "Iran", "sa": "Arabia Saudita", "ye": "Yemen",
    "om": "Oman", "ae": "Emirati Arabi Uniti", "qa": "Qatar", "bh": "Bahrein",
    "kw": "Kuwait", "ge": "Georgia", "am": "Armenia", "az": "Azerbaigian",
    "kz": "Kazakistan", "uz": "Uzbekistan", "tm": "Turkmenistan", "kg": "Kirghizistan",
    "tj": "Tagikistan", "af": "Afghanistan", "mn": "Mongolia", "cn": "Cina",
    "jp": "Giappone", "kr": "Corea del Sud", "kp": "Corea del Nord", "in": "India",
    "pk": "Pakistan", "bd": "Bangladesh", "lk": "Sri Lanka", "np": "Nepal",
    "bt": "Bhutan", "mv": "Maldive", "mm": "Birmania", "th": "Thailandia", "la": "Laos",
    "kh": "Cambogia", "vn": "Vietnam", "my": "Malesia", "sg": "Singapore",
    "id": "Indonesia", "bn": "Brunei", "ph": "Filippine", "tl": "Timor Est",
    "au": "Australia", "nz": "Nuova Zelanda", "pg": "Papua Nuova Guinea", "fj": "Figi",
    "sb": "Isole Salomone", "vu": "Vanuatu", "ws": "Samoa", "to": "Tonga",
    "tv": "Tuvalu", "ki": "Kiribati", "nr": "Nauru", "pw": "Palau", "fm": "Micronesia",
    "mh": "Isole Marshall", "ma": "Marocco", "dz": "Algeria", "tn": "Tunisia",
    "ly": "Libia", "eg": "Egitto", "sd": "Sudan", "ss": "Sudan del Sud", "et": "Etiopia",
    "er": "Eritrea", "dj": "Gibuti", "so": "Somalia", "ke": "Kenya", "ug": "Uganda",
    "tz": "Tanzania", "rw": "Ruanda", "bi": "Burundi", "cd": "RD Congo", "cg": "Congo",
    "ga": "Gabon", "gq": "Guinea Equatoriale", "cm": "Camerun",
    "cf": "Repubblica Centrafricana", "td": "Ciad", "ne": "Niger", "ng": "Nigeria",
    "bj": "Benin", "tg": "Togo", "gh": "Ghana", "ci": "Costa d'Avorio", "lr": "Liberia",
    "sl": "Sierra Leone", "gn": "Guinea", "gw": "Guinea-Bissau", "sn": "Senegal",
    "gm": "Gambia", "ml": "Mali", "bf": "Burkina Faso", "mr": "Mauritania",
    "cv": "Capo Verde", "st": "Sao Tome e Principe", "ao": "Angola", "zm": "Zambia",
    "zw": "Zimbabwe", "mw": "Malawi", "mz": "Mozambico", "mg": "Madagascar",
    "km": "Comore", "mu": "Mauritius", "sc": "Seychelles", "za": "Sudafrica",
    "na": "Namibia", "bw": "Botswana", "ls": "Lesotho", "sz": "Eswatini",
    "us": "Stati Uniti", "ca": "Canada", "mx": "Messico", "gt": "Guatemala",
    "bz": "Belize", "hn": "Honduras", "sv": "El Salvador", "ni": "Nicaragua",
    "cr": "Costa Rica", "pa": "Panama", "bs": "Bahamas", "cu": "Cuba", "jm": "Giamaica",
    "ht": "Haiti", "do": "Repubblica Dominicana", "kn": "Saint Kitts e Nevis",
    "ag": "Antigua e Barbuda", "dm": "Dominica", "lc": "Santa Lucia",
    "vc": "Saint Vincent", "bb": "Barbados", "gd": "Grenada",
    "tt": "Trinidad e Tobago", "co": "Colombia", "ve": "Venezuela", "gy": "Guyana",
    "sr": "Suriname", "ec": "Ecuador", "pe": "Peru", "br": "Brasile", "bo": "Bolivia",
    "py": "Paraguay", "uy": "Uruguay", "cl": "Cile", "ar": "Argentina",
}

# capitales IT uniquement si differentes du francais (base FR ascii)
CAP_IT = {
    "fr": "Parigi", "de": "Berlino", "it": "Roma", "pt": "Lisbona", "gb": "Londra",
    "ie": "Dublino", "ch": "Berna", "at": "Vienna", "lu": "Lussemburgo",
    "ad": "Andorra la Vella", "sm": "San Marino", "va": "Citta del Vaticano",
    "mt": "La Valletta", "se": "Stoccolma", "dk": "Copenaghen",
    "pl": "Varsavia", "cz": "Praga", "si": "Lubiana", "hr": "Zagabria",
    "rs": "Belgrado", "gr": "Atene", "ru": "Mosca", "cy": "Nicosia",
    "il": "Gerusalemme", "lb": "Beirut", "sy": "Damasco", "iq": "Baghdad",
    "sa": "Riad", "ae": "Abu Dhabi", "kw": "Kuwait City", "ge": "Tbilisi",
    "az": "Baku", "uz": "Tashkent", "tm": "Asgabat", "kg": "Bishkek",
    "tj": "Dushanbe", "af": "Kabul", "mn": "Ulan Bator", "cn": "Pechino",
    "kr": "Seul", "in": "Nuova Delhi", "np": "Katmandu", "bt": "Thimphu",
    "sg": "Singapore", "id": "Giacarta", "ph": "Manila",
    "vu": "Port Vila",
    "dz": "Algeri", "tn": "Tunisi", "eg": "Il Cairo", "sd": "Khartum",
    "ss": "Giuba", "et": "Addis Abeba", "dj": "Gibuti", "so": "Mogadiscio",
    "mu": "Port Louis", "st": "Sao Tome",
    "mx": "Citta del Messico", "gt": "Citta del Guatemala", "pa": "Citta di Panama",
    "cu": "L'Avana", "do": "Santo Domingo", "gd": "Saint George's",
    "tt": "Port of Spain",
}
