# Donnees espagnoles partagees par build_flags.py et build_capitals.py
# ES : nom espagnol du pays (ASCII, sans accents — convention du projet) ;
# CAP_ES : capitale espagnole SI differente du francais.

ES = {
    "fr": "Francia", "de": "Alemania", "it": "Italia", "es": "Espana", "pt": "Portugal",
    "gb": "Reino Unido", "ie": "Irlanda", "be": "Belgica", "nl": "Paises Bajos",
    "lu": "Luxemburgo", "ch": "Suiza", "at": "Austria", "mc": "Monaco",
    "ad": "Andorra", "li": "Liechtenstein", "sm": "San Marino", "va": "Ciudad del Vaticano",
    "mt": "Malta", "is": "Islandia", "no": "Noruega", "se": "Suecia", "dk": "Dinamarca",
    "fi": "Finlandia", "pl": "Polonia", "cz": "Chequia", "sk": "Eslovaquia", "hu": "Hungria",
    "si": "Eslovenia", "hr": "Croacia", "ba": "Bosnia y Herzegovina", "rs": "Serbia",
    "me": "Montenegro", "mk": "Macedonia del Norte", "al": "Albania", "gr": "Grecia",
    "bg": "Bulgaria", "ro": "Rumania", "md": "Moldavia", "ua": "Ucrania", "by": "Bielorrusia",
    "ru": "Rusia", "ee": "Estonia", "lv": "Letonia", "lt": "Lituania", "cy": "Chipre",
    "tr": "Turquia", "il": "Israel", "ps": "Palestina", "lb": "Libano", "sy": "Siria",
    "jo": "Jordania", "iq": "Irak", "ir": "Iran", "sa": "Arabia Saudita", "ye": "Yemen",
    "om": "Oman", "ae": "Emiratos Arabes Unidos", "qa": "Catar", "bh": "Barein",
    "kw": "Kuwait", "ge": "Georgia", "am": "Armenia", "az": "Azerbaiyan",
    "kz": "Kazajistan", "uz": "Uzbekistan", "tm": "Turkmenistan", "kg": "Kirguistan",
    "tj": "Tayikistan", "af": "Afganistan", "mn": "Mongolia", "cn": "China",
    "jp": "Japon", "kr": "Corea del Sur", "kp": "Corea del Norte", "in": "India",
    "pk": "Pakistan", "bd": "Banglades", "lk": "Sri Lanka", "np": "Nepal",
    "bt": "Butan", "mv": "Maldivas", "mm": "Birmania", "th": "Tailandia", "la": "Laos",
    "kh": "Camboya", "vn": "Vietnam", "my": "Malasia", "sg": "Singapur",
    "id": "Indonesia", "bn": "Brunei", "ph": "Filipinas", "tl": "Timor Oriental",
    "au": "Australia", "nz": "Nueva Zelanda", "pg": "Papua Nueva Guinea", "fj": "Fiyi",
    "sb": "Islas Salomon", "vu": "Vanuatu", "ws": "Samoa", "to": "Tonga",
    "tv": "Tuvalu", "ki": "Kiribati", "nr": "Nauru", "pw": "Palaos", "fm": "Micronesia",
    "mh": "Islas Marshall", "ma": "Marruecos", "dz": "Argelia", "tn": "Tunez",
    "ly": "Libia", "eg": "Egipto", "sd": "Sudan", "ss": "Sudan del Sur", "et": "Etiopia",
    "er": "Eritrea", "dj": "Yibuti", "so": "Somalia", "ke": "Kenia", "ug": "Uganda",
    "tz": "Tanzania", "rw": "Ruanda", "bi": "Burundi", "cd": "RD del Congo", "cg": "Congo",
    "ga": "Gabon", "gq": "Guinea Ecuatorial", "cm": "Camerun",
    "cf": "Republica Centroafricana", "td": "Chad", "ne": "Niger", "ng": "Nigeria",
    "bj": "Benin", "tg": "Togo", "gh": "Ghana", "ci": "Costa de Marfil", "lr": "Liberia",
    "sl": "Sierra Leona", "gn": "Guinea", "gw": "Guinea-Bisau", "sn": "Senegal",
    "gm": "Gambia", "ml": "Mali", "bf": "Burkina Faso", "mr": "Mauritania",
    "cv": "Cabo Verde", "st": "Santo Tome y Principe", "ao": "Angola", "zm": "Zambia",
    "zw": "Zimbabue", "mw": "Malaui", "mz": "Mozambique", "mg": "Madagascar",
    "km": "Comoras", "mu": "Mauricio", "sc": "Seychelles", "za": "Sudafrica",
    "na": "Namibia", "bw": "Botsuana", "ls": "Lesoto", "sz": "Esuatini",
    "us": "Estados Unidos", "ca": "Canada", "mx": "Mexico", "gt": "Guatemala",
    "bz": "Belice", "hn": "Honduras", "sv": "El Salvador", "ni": "Nicaragua",
    "cr": "Costa Rica", "pa": "Panama", "bs": "Bahamas", "cu": "Cuba", "jm": "Jamaica",
    "ht": "Haiti", "do": "Republica Dominicana", "kn": "San Cristobal y Nieves",
    "ag": "Antigua y Barbuda", "dm": "Dominica", "lc": "Santa Lucia",
    "vc": "San Vicente", "bb": "Barbados", "gd": "Granada",
    "tt": "Trinidad y Tobago", "co": "Colombia", "ve": "Venezuela", "gy": "Guyana",
    "sr": "Surinam", "ec": "Ecuador", "pe": "Peru", "br": "Brasil", "bo": "Bolivia",
    "py": "Paraguay", "uy": "Uruguay", "cl": "Chile", "ar": "Argentina",
}

# capitales ES uniquement si differentes du francais (base FR ascii)
CAP_ES = {
    "pt": "Lisboa", "be": "Bruselas", "ch": "Berna", "at": "Viena",
    "ad": "Andorra la Vieja", "sm": "San Marino", "va": "Ciudad del Vaticano",
    "mt": "La Valeta", "se": "Estocolmo", "it": "Roma",
    "pl": "Varsovia", "cz": "Praga", "si": "Liubliana", "rs": "Belgrado",
    "gr": "Atenas", "ru": "Moscu", "cy": "Nicosia",
    "il": "Jerusalen", "lb": "Beirut", "sy": "Damasco", "sa": "Riad",
    "ae": "Abu Dabi", "kw": "Ciudad de Kuwait", "ge": "Tiflis", "az": "Baku",
    "uz": "Taskent", "tm": "Asjabad", "kg": "Biskek", "tj": "Dusambe",
    "af": "Kabul", "mn": "Ulan Bator",
    "jp": "Tokio", "kr": "Seul", "kp": "Pionyang", "in": "Nueva Delhi",
    "bd": "Daca", "np": "Katmandu", "bt": "Timbu", "sg": "Singapur",
    "id": "Yakarta", "ph": "Manila", "vu": "Port Vila",
    "dz": "Argel", "tn": "Tunez", "eg": "El Cairo", "sd": "Jartum",
    "ss": "Yuba", "et": "Adis Abeba", "dj": "Yibuti", "cm": "Yaunde",
    "td": "Yamena", "ng": "Abuya", "bj": "Porto Novo", "gh": "Acra",
    "ci": "Yamusukro", "gw": "Bisau", "bf": "Uagadugu", "mr": "Nuakchot",
    "st": "Santo Tome", "mu": "Port Louis",
    "mx": "Ciudad de Mexico", "gt": "Ciudad de Guatemala", "pa": "Ciudad de Panama",
    "cu": "La Habana", "do": "Santo Domingo", "gd": "Saint George's",
    "tt": "Puerto Espana",
}
